// generated by `denext migrate` — safe to edit; re-running may overwrite
import type { DenextConfig } from "denext/server";
import { effect } from "@denext/effect";

export default {
  compatibilityMode: true,
  trailingSlash: true,
  // effect(): pass your app Layer to provide services — effect({ layer: AppLayer }).
  plugins: [effect()],
} satisfies DenextConfig;
