// @generated by scripts/gen-config-schema.ts — do not edit.
//
// Derived from the `DenextConfig` and `ExperimentalConfig` interfaces in ./config.ts via
// `deno doc --json`. Regenerate with `deno task gen:config-schema` (also part of
// `deno task docs:api`); tests/config-schema.test.ts fails when this file is stale.
// Import-free on purpose: it is the runtime validator's and config loader's key list.

/**
 * Every top-level `DenextConfig` property name, in declaration order (a readonly tuple,
 * assignable to `readonly string[]`). The config loader copies exactly these fields and
 * the validator warns on any other, so a field exists at runtime only if it is listed here —
 * which is why the list is generated from the type rather than maintained by hand.
 */
export const CONFIG_KEYS = [
  "mode",
  "spa",
  "i18n",
  "basePath",
  "trailingSlash",
  "assetPrefix",
  "redirects",
  "rewrites",
  "headers",
  "images",
  "tailwind",
  "mdx",
  "cache",
  "hsts",
  "csp",
  "publicEnv",
  "streaming",
  "live",
  "cacheComponents",
  "experimental",
  "classComponents",
  "compatibilityMode",
  "plugins",
] as const;

/**
 * Every `ExperimentalConfig` property name — the recognized `experimental.*` sub-keys —
 * in declaration order. The validator warns on any other `experimental.*` key.
 */
export const EXPERIMENTAL_KEYS = [
  "compiler",
  "asyncContext",
  "nodeResolve",
] as const;
