/**
 * `@denext/openapi/types` — TypeScript types from an OpenAPI 3.1 document, for a project that
 * is NOT the denext app: a separate frontend, a script, another repo. The app itself needs none
 * of this — its `.denext/api.ts` types `createApiClient()` straight from the route modules — but
 * that file re-reads the app's own sources, so it cannot leave the repo. This one can: the
 * emitted module is a single `.ts` with no imports.
 *
 * Two views of the same document:
 * - `paths` / `components` — the openapi-typescript shape, for openapi-fetch-style clients;
 * - `ApiSchema` — denext's {@link https://jsr.io/@denext/denext | `ApiSchema`} shape keyed by
 *   route pattern (`/api/pets/[id]`) and upper-cased method, so
 *   `createApiClient<ApiSchema>({ base })` from `jsr:@denext/denext` is a fully typed client
 *   (wire codec, dedupe, batching, `isApiClientError(err).code` narrowing) from anywhere.
 *
 * Types only. The JSON Schema subset understood is the one the spec builder authors and the
 * one Standard JSON Schema exporters (Zod 4, ArkType, Valibot) and TypeBox emit: `$ref` into
 * `components` or an inline `$defs`, `type` (string or array), `enum`/`const`, `object` with
 * `properties`/`required`/`additionalProperties`, `array` with `items`/`prefixItems`,
 * `oneOf`/`anyOf`/`allOf`, `nullable`, `description` (→ JSDoc). Anything else — an opaque
 * `{}` schema included — is `unknown`; a recursive `$defs` reference is `unknown` at the cycle.
 *
 * @module
 */

import type { JsonSchema } from "./json-schema.ts";
import type { OpenApiDocument, OpenApiOperation } from "./spec.ts";

/** Options for {@linkcode emitTypes}. */
export interface EmitTypesOptions {
  /** Emit the openapi-typescript `paths` + `components` interfaces (default `true`). */
  paths?: boolean;
  /** Emit the denext `ApiSchema` type (default `true`). */
  denextSchema?: boolean;
}

/** `$defs` scopes in effect (innermost first) and the definitions being expanded (cycle guard). */
interface Scope {
  defs: Record<string, JsonSchema>[];
  expanding: Set<string>;
}

const IDENT = /^[A-Za-z_$][\w$]*$/;
const HTTP_METHODS = ["get", "put", "post", "delete", "options", "head", "patch", "trace"];

/**
 * Render an OpenAPI 3.1 document as a TypeScript module.
 *
 * @param doc The document (`buildOpenApi(...).document`, or a parsed `openapi.json`).
 * @param options Which views to emit.
 * @returns The module source, ending in a newline.
 */
export function emitTypes(doc: OpenApiDocument, options: EmitTypesOptions = {}): string {
  const parts = [header(doc)];
  if (options.paths ?? true) parts.push(emitPaths(doc), emitComponents(doc));
  if (options.denextSchema ?? true) parts.push(emitApiSchema(doc));
  return parts.join("\n") + "\n";
}

function header(doc: OpenApiDocument): string {
  return [
    `// Generated by \`denext openapi types\` from ${
      JSON.stringify(doc.info.title)
    } ${doc.info.version}.`,
    "// Do not edit — regenerate. Types only; no imports.",
    "//",
    "// `paths`/`components` is the openapi-typescript shape (openapi-fetch and friends).",
    "// `ApiSchema` is denext's shape — a typed client from any TypeScript project:",
    '//   import { createApiClient } from "jsr:@denext/denext";',
    '//   const api = createApiClient<ApiSchema>({ base: "https://api.example.com" });',
    "//",
    "// Wire format: plain JSON, except a value holding a Date, Map, Set, BigInt, URL, undefined,",
    '// NaN or -0, which arrives `$`-tagged ({"$":"D","v":"…"}) with the response header',
    "// `x-denext-wire: 1`. `createApiClient` decodes those; a plain fetch must do so itself.",
    "",
  ].join("\n");
}

// ── paths / components ───────────────────────────────────────────────────────

function emitPaths(doc: OpenApiDocument): string {
  const lines = ["export interface paths {"];
  for (const [path, item] of Object.entries(doc.paths)) {
    lines.push(`  ${key(path)}: {`);
    for (const method of HTTP_METHODS) {
      const op = item[method];
      if (!op) continue;
      lines.push(`    ${method}: {`);
      lines.push(...operationMembers(op, "      "));
      lines.push("    };");
    }
    lines.push("  };");
  }
  lines.push("}");
  return lines.join("\n") + "\n";
}

/** `parameters`, `requestBody`, `responses` of one operation, at `indent`. */
function operationMembers(op: OpenApiOperation, indent: string): string[] {
  const out: string[] = [];
  const params = parametersOf(op);
  const scope = freshScope();
  const inner = indent + "  ";
  const paramLines: string[] = [];
  if (params.path.length) {
    paramLines.push(`${inner}path: ${parameterObject(params.path, inner, scope)};`);
  }
  if (params.query.length) {
    const optional = params.query.every((p) => p.required !== true) ? "?" : "";
    paramLines.push(`${inner}query${optional}: ${parameterObject(params.query, inner, scope)};`);
  }
  out.push(
    paramLines.length
      ? `${indent}parameters: {\n${paramLines.join("\n")}\n${indent}};`
      : `${indent}parameters: Record<never, never>;`,
  );
  const body = op.requestBody as
    | { required?: boolean; content?: Record<string, { schema?: JsonSchema }> }
    | undefined;
  if (body) {
    const optional = body.required === true ? "" : "?";
    out.push(`${indent}requestBody${optional}: ${mediaBlock(jsonSchemaOf(body), indent, scope)};`);
  }
  const responses = (op.responses ?? {}) as Record<string, MediaHolder>;
  out.push(`${indent}responses: {`);
  for (const [status, response] of Object.entries(responses)) {
    out.push(`${inner}${key(status)}: ${mediaBlock(jsonSchemaOf(response), inner, scope)};`);
  }
  out.push(`${indent}};`);
  return out;
}

/** A request body or response: something with (maybe) an `application/json` schema. */
interface MediaHolder {
  content?: Record<string, { schema?: JsonSchema }>;
}

function jsonSchemaOf(holder: MediaHolder | undefined): JsonSchema | undefined {
  return holder?.content?.["application/json"]?.schema;
}

/** `{ content: { "application/json": T } }` laid out over lines, or `{ content?: never }` for no body. */
function mediaBlock(schema: JsonSchema | undefined, indent: string, scope: Scope): string {
  if (schema === undefined) return "{ content?: never }";
  const inner = indent + "  ";
  return [
    "{",
    `${inner}content: {`,
    `${inner}  "application/json": ${tsType(schema, inner + "  ", scope)};`,
    `${inner}};`,
    `${indent}}`,
  ].join("\n");
}

interface Parameter {
  name: string;
  in: string;
  required?: boolean;
  schema?: JsonSchema;
  description?: string;
}

function parametersOf(op: OpenApiOperation): { path: Parameter[]; query: Parameter[] } {
  const all = (Array.isArray(op.parameters) ? op.parameters : []) as Parameter[];
  return { path: all.filter((p) => p.in === "path"), query: all.filter((p) => p.in === "query") };
}

/** An object type whose members are the given parameters. */
function parameterObject(params: Parameter[], indent: string, scope: Scope): string {
  const inner = indent + "  ";
  const members = params.map((p) => {
    const doc = p.description ? `${inner}/** ${jsdoc(p.description)} */\n` : "";
    return `${doc}${inner}${key(p.name)}${p.required === true ? "" : "?"}: ${
      tsType(p.schema, inner, scope)
    };`;
  });
  return `{\n${members.join("\n")}\n${indent}}`;
}

function emitComponents(doc: OpenApiDocument): string {
  const lines = ["export interface components {", "  schemas: {"];
  for (const [name, schema] of Object.entries(doc.components?.schemas ?? {})) {
    lines.push(`    ${key(name)}: ${tsType(schema, "    ", freshScope())};`);
  }
  lines.push("  };", "}");
  return lines.join("\n") + "\n";
}

// ── ApiSchema (denext) ───────────────────────────────────────────────────────

/**
 * denext's `ApiSchema`: route pattern → METHOD → `{ params?, query?, body?, response?, errors? }`.
 * The route pattern is the operation's `x-denext-path` (the spec builder stamps it); a document
 * from another producer falls back to `{id}` → `[id]`. Two OpenAPI paths may map to one route
 * (an optional catch-all's bare and parameterised variants) — the first operation wins and the
 * pattern decides which params exist and whether the catch-all is optional.
 */
function emitApiSchema(doc: OpenApiDocument): string {
  const lines = ["export type ApiSchema = {"];
  for (const [route, methods] of groupByRoute(doc)) {
    lines.push(`  ${key(route)}: {`);
    for (const [method, op] of methods) {
      const members = endpointMembers(route, op, "      ");
      lines.push(
        members.length
          ? `    ${method}: {\n${members.join("\n")}\n    };`
          : `    ${method}: Record<never, never>;`,
      );
    }
    lines.push("  };");
  }
  lines.push("};");
  return lines.join("\n") + "\n";
}

/** Operations by denext route pattern (sorted) and upper-cased method; the first per method wins. */
function groupByRoute(doc: OpenApiDocument): [string, Map<string, OpenApiOperation>][] {
  const routes = new Map<string, Map<string, OpenApiOperation>>();
  for (const [path, item] of Object.entries(doc.paths)) {
    for (const method of HTTP_METHODS) {
      const op = item[method];
      if (!op) continue;
      const route = typeof op["x-denext-path"] === "string"
        ? op["x-denext-path"] as string
        : path.replace(/\{([^}]+)\}/g, "[$1]");
      const methods = routes.get(route) ?? new Map<string, OpenApiOperation>();
      if (!methods.has(method.toUpperCase())) methods.set(method.toUpperCase(), op);
      routes.set(route, methods);
    }
  }
  return [...routes].sort(([a], [b]) => a.localeCompare(b));
}

/** `params`/`query`/`body`/`response`/`errors` members of one endpoint, at `indent`. */
function endpointMembers(route: string, op: OpenApiOperation, indent: string): string[] {
  const out: string[] = [];
  const scope = freshScope();
  const { path, query } = parametersOf(op);
  const params = routeParams(route, path, indent, scope);
  if (params) out.push(`${indent}params: ${params};`);
  if (query.length) out.push(`${indent}query: ${parameterObject(query, indent, scope)};`);
  const body = jsonSchemaOf(op.requestBody as MediaHolder | undefined);
  if (body !== undefined) out.push(`${indent}body: ${tsType(body, indent, scope)};`);
  const ok = jsonSchemaOf((op.responses as Record<string, MediaHolder> | undefined)?.["200"]);
  if (ok !== undefined) out.push(`${indent}response: ${tsType(ok, indent, scope)};`);
  const codes = errorCodesOf(op);
  if (codes.length) {
    out.push(`${indent}errors: ${codes.map((c) => JSON.stringify(c)).join(" | ")};`);
  }
  return out;
}

/**
 * The `params` object for a route pattern: `[id]` → `id: string`, `[...rest]` → `rest: string[]`,
 * `[[...rest]]` → `rest?: string[]`; a plain segment's type comes from its path parameter's
 * schema when the document has one. `null` for a static route.
 */
function routeParams(
  route: string,
  path: Parameter[],
  indent: string,
  scope: Scope,
): string | null {
  const members: string[] = [];
  const inner = indent + "  ";
  for (const segment of route.split("/")) {
    const m = /^\[(\[)?(\.\.\.)?([^\]]+)\]?\]$/.exec(segment);
    if (!m) continue;
    const [, optional, spread, name] = m;
    const param = path.find((p) => p.name === name);
    const type = spread ? "string[]" : tsType(param?.schema ?? { type: "string" }, inner, scope);
    members.push(`${inner}${key(name)}${optional ? "?" : ""}: ${type};`);
  }
  return members.length ? `{\n${members.join("\n")}\n${indent}}` : null;
}

/** The error codes an operation declares: `x-denext-errors` keys, else the enums of its error responses. */
function errorCodesOf(op: OpenApiOperation): string[] {
  const stamped = op["x-denext-errors"];
  if (stamped && typeof stamped === "object") return Object.keys(stamped as Record<string, number>);
  const codes: string[] = [];
  const responses = (op.responses ?? {}) as Record<string, MediaHolder>;
  for (const [status, response] of Object.entries(responses)) {
    if (!/^[45]\d\d$/.test(status)) continue;
    const schema = jsonSchemaOf(response);
    for (const part of (schema?.allOf as JsonSchema[] | undefined) ?? []) {
      const code = (((part.properties as JsonSchema | undefined)?.error as JsonSchema | undefined)
        ?.properties as JsonSchema | undefined)?.code as JsonSchema | undefined;
      if (Array.isArray(code?.enum)) {
        codes.push(...code.enum.filter((c): c is string => typeof c === "string"));
      }
    }
  }
  return codes;
}

// ── JSON Schema → TypeScript ─────────────────────────────────────────────────

function freshScope(): Scope {
  return { defs: [], expanding: new Set() };
}

/** The TypeScript type for a JSON Schema, with object members indented below `indent`. */
function tsType(schema: JsonSchema | undefined, indent: string, scope: Scope): string {
  if (!schema || typeof schema !== "object") return "unknown";
  const defs = (schema.$defs ?? schema.definitions) as Record<string, JsonSchema> | undefined;
  if (defs && typeof defs === "object") {
    scope = { defs: [defs, ...scope.defs], expanding: scope.expanding };
  }
  if (typeof schema.$ref === "string") return refType(schema.$ref, indent, scope);
  let type = coreType(schema, indent, scope);
  if (schema.nullable === true && type !== "unknown" && !/\bnull\b/.test(type)) {
    type = `${type} | null`;
  }
  return type;
}

function refType(ref: string, indent: string, scope: Scope): string {
  const component = /^#\/components\/schemas\/(.+)$/.exec(ref);
  if (component) return `components["schemas"][${JSON.stringify(component[1])}]`;
  const local = /^#\/(?:\$defs|definitions)\/(.+)$/.exec(ref);
  if (!local) return "unknown";
  const name = local[1];
  if (scope.expanding.has(name)) return "unknown"; // recursive definition: cut the cycle
  const def = scope.defs.find((d) => name in d)?.[name];
  if (!def) return "unknown";
  scope.expanding.add(name);
  try {
    return tsType(def, indent, scope);
  } finally {
    scope.expanding.delete(name);
  }
}

function coreType(schema: JsonSchema, indent: string, scope: Scope): string {
  if (Array.isArray(schema.enum)) return literalUnion(schema.enum);
  if ("const" in schema) return literalUnion([schema.const]);
  const combined = combinatorType(schema, indent, scope);
  if (combined !== null) return combined;
  const types = schemaTypes(schema);
  if (!types.length) return "unknown";
  return types.map((t) => typedAs(t, schema, indent, scope)).join(" | ");
}

/** `oneOf`/`anyOf` → a union, `allOf` → an intersection (parenthesised); `null` when none applies. */
function combinatorType(schema: JsonSchema, indent: string, scope: Scope): string | null {
  const combinator = (["oneOf", "anyOf", "allOf"] as const).find((k) => Array.isArray(schema[k]));
  if (!combinator) return null;
  const members = (schema[combinator] as JsonSchema[]).map((m) => tsType(m, indent, scope));
  if (!members.length) return "unknown";
  return `(${members.join(combinator === "allOf" ? " & " : " | ")})`;
}

/** The schema's `type` list; an untyped schema with object or array keywords is inferred. */
function schemaTypes(schema: JsonSchema): string[] {
  if (Array.isArray(schema.type)) return schema.type as string[];
  if (typeof schema.type === "string") return [schema.type];
  if (schema.properties || schema.additionalProperties !== undefined) return ["object"];
  if (schema.items || schema.prefixItems) return ["array"];
  return [];
}

function typedAs(type: string, schema: JsonSchema, indent: string, scope: Scope): string {
  switch (type) {
    case "string":
      return "string";
    case "number":
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "array":
      return arrayType(schema, indent, scope);
    case "object":
      return objectType(schema, indent, scope);
    default:
      return "unknown";
  }
}

function arrayType(schema: JsonSchema, indent: string, scope: Scope): string {
  const items = schema.items as JsonSchema | undefined;
  if (Array.isArray(schema.prefixItems)) {
    const fixed = (schema.prefixItems as JsonSchema[]).map((s) => tsType(s, indent, scope));
    const rest = items && typeof items === "object"
      ? [`...${wrap(tsType(items, indent, scope))}[]`]
      : [];
    return `[${[...fixed, ...rest].join(", ")}]`;
  }
  return `${wrap(items && typeof items === "object" ? tsType(items, indent, scope) : "unknown")}[]`;
}

function objectType(schema: JsonSchema, indent: string, scope: Scope): string {
  const props = (schema.properties ?? {}) as Record<string, JsonSchema>;
  const required = new Set(Array.isArray(schema.required) ? schema.required as string[] : []);
  const inner = indent + "  ";
  const members = Object.entries(props).map(([name, s]) => {
    const doc = typeof s?.description === "string"
      ? `${inner}/** ${jsdoc(s.description)} */\n`
      : "";
    return `${doc}${inner}${key(name)}${required.has(name) ? "" : "?"}: ${
      tsType(s, inner, scope)
    };`;
  });
  const additional = schema.additionalProperties;
  if (additional !== undefined && additional !== false) {
    const value = additional === true ? "unknown" : tsType(additional as JsonSchema, inner, scope);
    if (!members.length) return `Record<string, ${value}>`;
    members.push(`${inner}[key: string]: ${value};`);
  }
  if (!members.length) {
    return additional === false ? "Record<string, never>" : "Record<string, unknown>";
  }
  return `{\n${members.join("\n")}\n${indent}}`;
}

/** A union of JSON literals; a non-primitive member (an object enum) is `unknown`. */
function literalUnion(values: unknown[]): string {
  const literals = values.map((v) =>
    v === null || ["string", "number", "boolean"].includes(typeof v) ? JSON.stringify(v) : "unknown"
  );
  return [...new Set(literals)].join(" | ") || "never";
}

/** Parenthesise a union/intersection so a following `[]` binds to the whole. */
function wrap(type: string): string {
  return /[|&]/.test(type) && !/^\(.*\)$/.test(type) && !type.startsWith("{") ? `(${type})` : type;
}

/** A property/interface key: bare when it is an identifier, quoted otherwise. */
function key(name: string): string {
  return IDENT.test(name) ? name : JSON.stringify(name);
}

/** A description on one JSDoc line; a comment terminator inside it is escaped so it cannot end the JSDoc. */
function jsdoc(text: string): string {
  return text.replace(/\s+/g, " ").replace(/\*\//g, "*\\/").trim();
}
