// denext-app-extension-template: 5 sha256=600e104550ff0fab1e82bbad78d4028d41bda5271d7c856a1c2721407878101c
// Generated by denext mobile add share-extension (denext app extensions). Safe to commit;
// re-run it after upgrading denext (then ship a new binary). See https://denext.dev/docs/desktop.

package dev.denext.sharereceive;

import android.app.Activity;
import android.content.ContentResolver;
import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.util.Log;
import android.util.Patterns;
import android.webkit.MimeTypeMap;
import androidx.annotation.Nullable;
import com.getcapacitor.JSArray;
import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * The native side of {@code onShareReceived()} from {@code denext/mobile}, reached from the web
 * app as {@code window.Capacitor.Plugins.DenextShareReceive}. {@code MainActivity} registers it.
 *
 * <p>The launcher activity's SEND / SEND_MULTIPLE intent filters (text/plain, image/*, written
 * by {@code denext mobile add share-extension}) bring shares here: the cold-start intent in
 * {@link #load}, later ones through {@link #handleOnNewIntent}. Text that is a single http(s)
 * URL becomes {@code url}, other text {@code text}; each shared {@code content:} stream is copied
 * into the app's cache ({@code denext-share/}) and listed in {@code files} with its MIME type.
 * {@code file:} streams are refused (another app could name this app's private files).
 *
 * <ul>
 *   <li>{@code consume() → { items }}: the shares received so far, oldest first, removed.
 *   <li>event {@code shareReceived}: a share is waiting; the web side then calls consume().
 * </ul>
 */
@CapacitorPlugin(name = "DenextShareReceive")
public class DenextShareReceivePlugin extends Plugin {

    private static final String TAG = "DenextShareReceive";
    /** Guarded by {@code this}. Shares not yet consumed. */
    private final List<JSObject> inbox = new ArrayList<>();

    @Override
    public void load() {
        Activity activity = getActivity();
        if (activity != null) capture(activity.getIntent());
    }

    @Override
    protected void handleOnNewIntent(Intent intent) {
        super.handleOnNewIntent(intent);
        capture(intent);
    }

    @PluginMethod
    public void consume(PluginCall call) {
        JSArray items = new JSArray();
        synchronized (this) {
            for (JSObject item : inbox) items.put(item);
            inbox.clear();
        }
        JSObject result = new JSObject();
        result.put("items", items);
        call.resolve(result);
    }

    /** Take a SEND / SEND_MULTIPLE intent: read it off the main thread, then notify. */
    private void capture(@Nullable Intent intent) {
        if (intent == null) return;
        String action = intent.getAction();
        if (!Intent.ACTION_SEND.equals(action) && !Intent.ACTION_SEND_MULTIPLE.equals(action)) return;
        CharSequence text = intent.getCharSequenceExtra(Intent.EXTRA_TEXT);
        List<Uri> streams = streams(intent, action);
        String type = intent.getType();
        Activity activity = getActivity();
        // Consumed: an activity recreated later (rotation, process restore) must not see it again.
        if (activity != null && activity.getIntent() == intent) {
            activity.setIntent(new Intent(Intent.ACTION_MAIN));
        }
        Context context = getContext().getApplicationContext();
        new Thread(() -> {
            JSObject item = item(context, text, streams, type);
            if (item == null) return;
            synchronized (this) {
                inbox.add(item);
            }
            notifyListeners("shareReceived", new JSObject(), true);
        }, "denext-share-receive").start();
    }

    @SuppressWarnings("deprecation")
    private static List<Uri> streams(Intent intent, String action) {
        List<Uri> out = new ArrayList<>();
        if (Intent.ACTION_SEND.equals(action)) {
            Uri uri = intent.getParcelableExtra(Intent.EXTRA_STREAM);
            if (uri != null) out.add(uri);
        } else {
            ArrayList<Uri> uris = intent.getParcelableArrayListExtra(Intent.EXTRA_STREAM);
            if (uris != null) out.addAll(uris);
        }
        return out;
    }

    /** The shared item, or null when nothing usable was shared. */
    @Nullable
    private static JSObject item(Context context, @Nullable CharSequence text, List<Uri> streams, @Nullable String type) {
        JSObject item = new JSObject();
        if (text != null && text.length() > 0) {
            String value = text.toString();
            String trimmed = value.trim();
            if (isWebUrl(trimmed)) item.put("url", trimmed);
            else item.put("text", value);
        }
        JSArray files = new JSArray();
        pruneShareCache(context);
        long[] budget = { MAX_SHARE_TOTAL_BYTES };
        int taken = 0;
        for (Uri uri : streams) {
            // A hostile sender may list thousands of streams: copy the first few only.
            if (taken++ >= MAX_SHARED_STREAMS) {
                Log.w(TAG, "ignored shared streams past " + MAX_SHARED_STREAMS);
                break;
            }
            JSObject file = copy(context, uri, type, budget);
            if (file != null) files.put(file);
        }
        if (files.length() > 0) item.put("files", files);
        if (item.length() == 0) return null;
        item.put("receivedAt", System.currentTimeMillis());
        return item;
    }

    private static boolean isWebUrl(String value) {
        return (value.startsWith("https://") || value.startsWith("http://"))
            && !value.contains(" ") && Patterns.WEB_URL.matcher(value).matches();
    }

    /** The most one shared stream may copy (a hostile sender must not fill the cache dir). */
    private static final long MAX_SHARED_BYTES = 256L * 1024 * 1024;
    /** The most streams one share copies. */
    private static final int MAX_SHARED_STREAMS = 32;
    /** The most one share copies across all its streams. */
    private static final long MAX_SHARE_TOTAL_BYTES = 512L * 1024 * 1024;
    /** Copies older than this are deleted at the next share (the app has long taken them). */
    private static final long SHARE_CACHE_MAX_AGE_MS = 24L * 60 * 60 * 1000;

    /** Delete earlier shares' copies older than {@link #SHARE_CACHE_MAX_AGE_MS}. */
    private static void pruneShareCache(Context context) {
        File[] old = new File(context.getCacheDir(), "denext-share").listFiles();
        if (old == null) return;
        long cutoff = System.currentTimeMillis() - SHARE_CACHE_MAX_AGE_MS;
        for (File f : old) {
            //noinspection ResultOfMethodCallIgnored
            if (f.isFile() && f.lastModified() < cutoff) f.delete();
        }
    }

    /**
     * Whether the content: URI is served by one of THIS app's own providers. A share intent is
     * resolved with the app's permissions, so another app could name this app's (non-exported)
     * FileProvider and have its private files copied into the share inbox: refuse those.
     */
    private static boolean isOwnProvider(Context context, Uri uri) {
        String authority = uri.getAuthority();
        if (authority == null) return true;
        String pkg = context.getPackageName();
        // The conventional authorities (appId.fileprovider, Capacitor's) are this app's.
        if (authority.equals(pkg) || authority.startsWith(pkg + ".")) return true;
        try {
            android.content.pm.ProviderInfo info =
                context.getPackageManager().resolveContentProvider(authority, 0);
            // null: a provider of a package this app cannot see (package visibility) — not ours.
            return info != null && pkg.equals(info.packageName);
        } catch (Exception e) {
            return false;
        }
    }

    /**
     * Copy a content: stream into the cache, within what is left of the share's {@code budget}
     * (bytes, decremented); null for any other scheme, this app's own provider, an oversized
     * stream or share, or on failure.
     */
    @Nullable
    private static JSObject copy(Context context, Uri uri, @Nullable String fallbackType, long[] budget) {
        if (!ContentResolver.SCHEME_CONTENT.equals(uri.getScheme())) return null;
        if (isOwnProvider(context, uri)) {
            Log.w(TAG, "refused a shared stream from this app's own provider");
            return null;
        }
        ContentResolver resolver = context.getContentResolver();
        String mimeType = resolver.getType(uri);
        if (mimeType == null) mimeType = fallbackType != null && !fallbackType.endsWith("/*") ? fallbackType : "application/octet-stream";
        String ext = MimeTypeMap.getSingleton().getExtensionFromMimeType(mimeType);
        File dir = new File(context.getCacheDir(), "denext-share");
        if (!dir.isDirectory() && !dir.mkdirs()) return null;
        File target = new File(dir, UUID.randomUUID() + (ext == null ? ".bin" : "." + ext));
        try (InputStream in = resolver.openInputStream(uri); OutputStream out = new FileOutputStream(target)) {
            if (in == null) return null;
            byte[] buffer = new byte[64 * 1024];
            long total = 0;
            for (int n = in.read(buffer); n >= 0; n = in.read(buffer)) {
                total += n;
                if (total > MAX_SHARED_BYTES) throw new java.io.IOException("shared stream too large");
                if (total > budget[0]) throw new java.io.IOException("share too large");
                out.write(buffer, 0, n);
            }
            budget[0] -= total;
        } catch (Exception e) {
            Log.w(TAG, "could not copy a shared stream", e);
            //noinspection ResultOfMethodCallIgnored
            target.delete();
            return null;
        }
        JSObject file = new JSObject();
        file.put("path", target.getAbsolutePath());
        file.put("mimeType", mimeType);
        return file;
    }
}
