// denext-app-extension-template: 1 sha256=b91daefad55a4145a07bcac860adb726cc5a386fe9b407352e89751f43138159
// Generated by denext mobile add share-extension (denext app extensions). Safe to commit;
// re-run it after upgrading denext (then ship a new binary). See https://denext.dev/docs/desktop.

package dev.denext.sharereceive;

import android.app.Activity;
import android.content.ContentResolver;
import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.util.Log;
import android.util.Patterns;
import android.webkit.MimeTypeMap;
import androidx.annotation.Nullable;
import com.getcapacitor.JSArray;
import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * The native side of {@code onShareReceived()} from {@code denext/mobile}, reached from the web
 * app as {@code window.Capacitor.Plugins.DenextShareReceive}. {@code MainActivity} registers it.
 *
 * <p>The launcher activity's SEND / SEND_MULTIPLE intent filters (text/plain, image/*, written
 * by {@code denext mobile add share-extension}) bring shares here: the cold-start intent in
 * {@link #load}, later ones through {@link #handleOnNewIntent}. Text that is a single http(s)
 * URL becomes {@code url}, other text {@code text}; each shared {@code content:} stream is copied
 * into the app's cache ({@code denext-share/}) and listed in {@code files} with its MIME type.
 * {@code file:} streams are refused (another app could name this app's private files).
 *
 * <ul>
 *   <li>{@code consume() → { items }}: the shares received so far, oldest first, removed.
 *   <li>event {@code shareReceived}: a share is waiting; the web side then calls consume().
 * </ul>
 */
@CapacitorPlugin(name = "DenextShareReceive")
public class DenextShareReceivePlugin extends Plugin {

    private static final String TAG = "DenextShareReceive";
    /** Guarded by {@code this}. Shares not yet consumed. */
    private final List<JSObject> inbox = new ArrayList<>();

    @Override
    public void load() {
        Activity activity = getActivity();
        if (activity != null) capture(activity.getIntent());
    }

    @Override
    protected void handleOnNewIntent(Intent intent) {
        super.handleOnNewIntent(intent);
        capture(intent);
    }

    @PluginMethod
    public void consume(PluginCall call) {
        JSArray items = new JSArray();
        synchronized (this) {
            for (JSObject item : inbox) items.put(item);
            inbox.clear();
        }
        JSObject result = new JSObject();
        result.put("items", items);
        call.resolve(result);
    }

    /** Take a SEND / SEND_MULTIPLE intent: read it off the main thread, then notify. */
    private void capture(@Nullable Intent intent) {
        if (intent == null) return;
        String action = intent.getAction();
        if (!Intent.ACTION_SEND.equals(action) && !Intent.ACTION_SEND_MULTIPLE.equals(action)) return;
        CharSequence text = intent.getCharSequenceExtra(Intent.EXTRA_TEXT);
        List<Uri> streams = streams(intent, action);
        String type = intent.getType();
        Activity activity = getActivity();
        // Consumed: an activity recreated later (rotation, process restore) must not see it again.
        if (activity != null && activity.getIntent() == intent) {
            activity.setIntent(new Intent(Intent.ACTION_MAIN));
        }
        Context context = getContext().getApplicationContext();
        new Thread(() -> {
            JSObject item = item(context, text, streams, type);
            if (item == null) return;
            synchronized (this) {
                inbox.add(item);
            }
            notifyListeners("shareReceived", new JSObject(), true);
        }, "denext-share-receive").start();
    }

    @SuppressWarnings("deprecation")
    private static List<Uri> streams(Intent intent, String action) {
        List<Uri> out = new ArrayList<>();
        if (Intent.ACTION_SEND.equals(action)) {
            Uri uri = intent.getParcelableExtra(Intent.EXTRA_STREAM);
            if (uri != null) out.add(uri);
        } else {
            ArrayList<Uri> uris = intent.getParcelableArrayListExtra(Intent.EXTRA_STREAM);
            if (uris != null) out.addAll(uris);
        }
        return out;
    }

    /** The shared item, or null when nothing usable was shared. */
    @Nullable
    private static JSObject item(Context context, @Nullable CharSequence text, List<Uri> streams, @Nullable String type) {
        JSObject item = new JSObject();
        if (text != null && text.length() > 0) {
            String value = text.toString();
            String trimmed = value.trim();
            if (isWebUrl(trimmed)) item.put("url", trimmed);
            else item.put("text", value);
        }
        JSArray files = new JSArray();
        for (Uri uri : streams) {
            JSObject file = copy(context, uri, type);
            if (file != null) files.put(file);
        }
        if (files.length() > 0) item.put("files", files);
        if (item.length() == 0) return null;
        item.put("receivedAt", System.currentTimeMillis());
        return item;
    }

    private static boolean isWebUrl(String value) {
        return (value.startsWith("https://") || value.startsWith("http://"))
            && !value.contains(" ") && Patterns.WEB_URL.matcher(value).matches();
    }

    /** Copy a content: stream into the cache; null for any other scheme or on failure. */
    @Nullable
    private static JSObject copy(Context context, Uri uri, @Nullable String fallbackType) {
        if (!ContentResolver.SCHEME_CONTENT.equals(uri.getScheme())) return null;
        ContentResolver resolver = context.getContentResolver();
        String mimeType = resolver.getType(uri);
        if (mimeType == null) mimeType = fallbackType != null && !fallbackType.endsWith("/*") ? fallbackType : "application/octet-stream";
        String ext = MimeTypeMap.getSingleton().getExtensionFromMimeType(mimeType);
        File dir = new File(context.getCacheDir(), "denext-share");
        if (!dir.isDirectory() && !dir.mkdirs()) return null;
        File target = new File(dir, UUID.randomUUID() + (ext == null ? ".bin" : "." + ext));
        try (InputStream in = resolver.openInputStream(uri); OutputStream out = new FileOutputStream(target)) {
            if (in == null) return null;
            byte[] buffer = new byte[64 * 1024];
            for (int n = in.read(buffer); n >= 0; n = in.read(buffer)) out.write(buffer, 0, n);
        } catch (Exception e) {
            Log.w(TAG, "could not copy a shared stream", e);
            //noinspection ResultOfMethodCallIgnored
            target.delete();
            return null;
        }
        JSObject file = new JSObject();
        file.put("path", target.getAbsolutePath());
        file.put("mimeType", mimeType);
        return file;
    }
}
