/**
 * Deterministic, seeded, LAZY bench data. `makeItems(kind, n, seed)` returns a {@link BenchList}:
 * a snapshot whose item at any position is generated on demand from `(seed, index)` alone, so
 * 10M rows cost nothing until they are drawn, and the web app and the React Native app draw
 * byte-identical content for the same `(kind, n, seed)`.
 *
 * Plain TypeScript: no React, no platform imports (Deno, the browser and Metro all load it).
 */

import { FIXED, HEADER } from "./theme.ts";

export type Kind = "fixed" | "chat" | "images" | "sections";

/** A `fixed` row, and every non-header row of `sections`. */
export interface RowItem {
  type: "row";
  id: string;
  title: string;
  subtitle: string;
  time: string;
  initials: string;
  color: number;
}

/** A `sections` header. */
export interface HeaderItem {
  type: "header";
  id: string;
  title: string;
  count: number;
}

/** One run of inline text: plain, bold, a link or inline code. */
export interface Span {
  text: string;
  bold?: boolean;
  href?: string;
  code?: boolean;
}

export type ChatBlock =
  | { type: "p"; spans: Span[] }
  | { type: "code"; lang: string; lines: string[] };

export interface ChatItem {
  type: "chat";
  id: string;
  role: "user" | "assistant";
  blocks: ChatBlock[];
}

export interface ImageItem {
  type: "image";
  id: string;
  /** Index into {@link IMAGE_ASSETS}. */
  image: number;
  caption: string;
}

export type Item = RowItem | HeaderItem | ChatItem | ImageItem;

/**
 * The placeholder images both apps bundle (generated by shared/gen-images.ts into
 * web/public/img/ and native/assets/img/). Rows reserve `width / height` of space up front.
 */
export const IMAGE_ASSETS: readonly { file: string; w: number; h: number }[] = [
  { file: "img-00.png", w: 480, h: 270 },
  { file: "img-01.png", w: 480, h: 360 },
  { file: "img-02.png", w: 480, h: 320 },
  { file: "img-03.png", w: 400, h: 400 },
  { file: "img-04.png", w: 480, h: 270 },
  { file: "img-05.png", w: 480, h: 360 },
  { file: "img-06.png", w: 480, h: 320 },
  { file: "img-07.png", w: 400, h: 400 },
  { file: "img-08.png", w: 480, h: 270 },
  { file: "img-09.png", w: 480, h: 360 },
  { file: "img-10.png", w: 480, h: 320 },
  { file: "img-11.png", w: 400, h: 400 },
];

// ─── randomness ──────────────────────────────────────────────────────────────────────────

/** A 32-bit hash of two integers (murmur3 finaliser); negative indices are fine. */
export function mix(a: number, b: number): number {
  let h = Math.imul(a ^ 0x9e3779b9, 0x85ebca6b) ^ (b | 0);
  h = Math.imul(h ^ (h >>> 16), 0x7feb352d);
  h = Math.imul(h ^ (h >>> 15), 0x846ca68b);
  return (h ^ (h >>> 16)) >>> 0;
}

/** mulberry32: a small, fast, seeded PRNG in [0, 1). */
export function rng(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const int = (r: () => number, lo: number, hi: number) => lo + Math.floor(r() * (hi - lo + 1));
const pick = <T>(r: () => number, xs: readonly T[]): T => xs[Math.floor(r() * xs.length)];
/** Skewed towards `lo`: most values small, a long tail up to `hi`. */
const skew = (r: () => number, lo: number, hi: number) =>
  lo + Math.floor(r() * r() * (hi - lo + 1));

// ─── word lists ──────────────────────────────────────────────────────────────────────────

const WORDS = (
  "the a to of and in is it that for on with as this be are by from or an at not we can " +
  "you should will function component render state list scroll layout frame index cache " +
  "value request response server client build bundle module import export type error test " +
  "row item height offset measure virtual window range update commit effect hook memo key " +
  "data query page route handler stream buffer async await promise event thread worker " +
  "native bridge view text image style theme token parser compiler runtime deploy config " +
  "because then when if only each every other before after while again instead however"
).split(" ");

const FIRST = [
  "Ada",
  "Alan",
  "Grace",
  "Linus",
  "Margaret",
  "Dennis",
  "Barbara",
  "Ken",
  "Frances",
  "Edsger",
  "Radia",
  "Guido",
  "Katherine",
  "Bjarne",
  "Hedy",
  "Tim",
];
const LAST = [
  "Lovelace",
  "Turing",
  "Hopper",
  "Torvalds",
  "Hamilton",
  "Ritchie",
  "Liskov",
  "Thompson",
  "Allen",
  "Dijkstra",
  "Perlman",
  "van Rossum",
  "Johnson",
  "Stroustrup",
  "Lamarr",
  "Berners-Lee",
];

const LANGS = ["ts", "tsx", "rust", "sh", "json"] as const;
const IDENTS = [
  "items",
  "offset",
  "measure",
  "range",
  "cache",
  "row",
  "index",
  "size",
  "viewport",
  "anchor",
  "result",
  "node",
];

function sentence(r: () => number, words: number): string {
  const out: string[] = [];
  for (let i = 0; i < words; i++) out.push(pick(r, WORDS));
  const s = out.join(" ");
  return s.charAt(0).toUpperCase() + s.slice(1);
}

/** ~8 words per rendered line at 15px on a phone-width column. */
const WORDS_PER_LINE = 8;

function codeLine(r: () => number, depth: number): string {
  const pad = "  ".repeat(depth);
  const a = pick(r, IDENTS), b = pick(r, IDENTS), n = int(r, 0, 999);
  switch (int(r, 0, 6)) {
    case 0:
      return `${pad}const ${a} = await ${b}.get(${n});`;
    case 1:
      return `${pad}if (${a}.length > ${n % 17}) {`;
    case 2:
      return `${pad}return ${a}.map((x) => x.${b} + ${n});`;
    case 3:
      return `${pad}// ${sentence(r, int(r, 3, 9)).toLowerCase()}`;
    case 4:
      return `${pad}${a}[${b}] = ${n} * ${b}.${pick(r, IDENTS)};`;
    case 5:
      return `${pad}let ${a}Total = ${n}; ${a}Total += ${b}.size;`;
    default:
      return `${"  ".repeat(Math.max(0, depth - 1))}}`;
  }
}

/** An unbroken token (a hash / URL / base64 run) of 120–300 chars. */
function longToken(r: () => number): string {
  const alphabet = "abcdef0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_-/";
  let s = "sha256:";
  const len = int(r, 120, 300);
  for (let i = 0; i < len; i++) {
    s += alphabet[Math.floor(r() * alphabet.length)];
  }
  return s;
}

function paragraph(r: () => number, lines: number, allowLong: boolean): Span[] {
  const spans: Span[] = [];
  let words = Math.max(2, lines * WORDS_PER_LINE - int(r, 0, 4));
  let plain: string[] = [];
  const flush = () => {
    if (plain.length) spans.push({ text: plain.join(" ") + " " });
    plain = [];
  };
  while (words > 0) {
    const roll = r();
    if (roll < 0.03) {
      flush();
      const w = int(r, 1, 3);
      spans.push({ text: sentence(r, w).toLowerCase(), bold: true });
      spans.push({ text: " " });
      words -= w;
    } else if (roll < 0.045) {
      flush();
      const w = int(r, 1, 3);
      spans.push({
        text: sentence(r, w).toLowerCase(),
        href: `https://example.com/docs/${pick(r, IDENTS)}`,
      });
      spans.push({ text: " " });
      words -= w;
    } else if (roll < 0.065) {
      flush();
      spans.push({ text: `${pick(r, IDENTS)}()`, code: true });
      spans.push({ text: " " });
      words -= 1;
    } else {
      plain.push(pick(r, WORDS));
      words -= 1;
    }
  }
  flush();
  if (allowLong && r() < 0.05) spans.push({ text: longToken(r) });
  return spans;
}

// ─── generators ──────────────────────────────────────────────────────────────────────────

function genRow(seed: number, v: number): RowItem {
  const r = rng(mix(seed, v));
  const first = pick(r, FIRST), last = pick(r, LAST);
  const minutes = ((v % 1440) + 1440) % 1440;
  return {
    type: "row",
    id: `r${v}`,
    title: `${first} ${last}`,
    subtitle: sentence(r, int(r, 4, 12)),
    time: `${String(Math.floor(minutes / 60)).padStart(2, "0")}:${
      String(minutes % 60).padStart(2, "0")
    }`,
    initials: first[0] + last[0],
    color: int(r, 0, 9),
  };
}

/** Nesting after one code line: `{` opens a level (max 4), a lone `}` closes one. */
function nextDepth(line: string, depth: number): number {
  if (line.endsWith("{")) return Math.min(depth + 1, 4);
  return line.trim() === "}" ? Math.max(depth - 1, 0) : depth;
}

/** A code block of 3–60 lines (skewed short). */
function codeBlock(r: () => number): ChatBlock {
  const count = skew(r, 3, 60);
  const lines: string[] = [];
  let depth = 0;
  for (let i = 0; i < count; i++) {
    const line = codeLine(r, depth);
    lines.push(line);
    depth = nextDepth(line, depth);
  }
  return { type: "code", lang: pick(r, LANGS), lines };
}

/** A user message: 1–6 lines of prose, sometimes a few shell commands. */
function userBlocks(r: () => number): ChatBlock[] {
  const blocks: ChatBlock[] = [{ type: "p", spans: paragraph(r, skew(r, 1, 6), true) }];
  if (r() < 0.06) {
    const lines = Array.from({ length: int(r, 1, 4) }, () => `$ deno task ${pick(r, IDENTS)}`);
    blocks.push({ type: "code", lang: "sh", lines });
  }
  return blocks;
}

/** 0 code blocks (65%), 1 (28%) or 2 (7%). */
const codeBlockCount = (r: () => number) => (r() < 0.35 ? (r() < 0.2 ? 2 : 1) : 0);

/** An assistant message: 1–40 lines of prose in paragraphs, with 0–2 code blocks between. */
function assistantBlocks(r: () => number): ChatBlock[] {
  const blocks: ChatBlock[] = [];
  let prose = skew(r, 1, 40);
  let code = codeBlockCount(r);
  while (prose > 0 || code > 0) {
    if (prose > 0) {
      const lines = Math.min(prose, int(r, 1, 6));
      blocks.push({ type: "p", spans: paragraph(r, lines, true) });
      prose -= lines;
    }
    if (code > 0 && (prose <= 0 || r() < 0.3)) {
      blocks.push(codeBlock(r));
      code--;
    }
  }
  return blocks;
}

function genChat(seed: number, v: number): ChatItem {
  const r = rng(mix(seed, v));
  const role = (v % 2 + 2) % 2 === 0 ? "user" : "assistant";
  const blocks = role === "user" ? userBlocks(r) : assistantBlocks(r);
  return { type: "chat", id: `c${v}`, role, blocks };
}

function genImage(seed: number, v: number): ImageItem {
  const r = rng(mix(seed, v));
  return {
    type: "image",
    id: `i${v}`,
    image: int(r, 0, IMAGE_ASSETS.length - 1),
    caption: sentence(r, int(r, 4, 24)),
  };
}

// ─── sections layout ─────────────────────────────────────────────────────────────────────

/**
 * Flat positions of the section headers for `n` flat entries (headers + rows), each section
 * 20–200 rows. `n` = 1M is ~9k sections; computed once per (seed, n).
 */
export function sectionStarts(seed: number, n: number): Int32Array {
  const r = rng(mix(seed, 0x5ec7));
  const starts: number[] = [];
  let pos = 0;
  while (pos < n) {
    starts.push(pos);
    pos += 1 + int(r, 20, 200);
  }
  return Int32Array.from(starts);
}

/** Index of the last header at or before `pos` (binary search). */
export function sectionOf(starts: ArrayLike<number>, pos: number): number {
  let lo = 0, hi = starts.length - 1;
  while (lo < hi) {
    const mid = (lo + hi + 1) >> 1;
    if (starts[mid] <= pos) lo = mid;
    else hi = mid - 1;
  }
  return lo;
}

// ─── the list snapshot ───────────────────────────────────────────────────────────────────

/** A small cache of generated items, so re-renders of the same row do not re-generate it. */
class ItemCache {
  private map = new Map<number, Item>();
  constructor(readonly cap: number) {}
  get(v: number, make: () => Item): Item {
    let it = this.map.get(v);
    if (it === undefined) {
      if (this.map.size >= this.cap) this.map.clear();
      it = make();
      this.map.set(v, it);
    }
    return it;
  }
}

/** One section of {@link BenchList.sections}: rows as VIRTUAL indices. */
export interface SectionSpec {
  key: string;
  header: HeaderItem;
  data: number[];
}

/**
 * An immutable snapshot of a bench list: positions `0 … count-1` map to virtual indices
 * `start … end-1`. `withAppended` / `withPrepended` return a new snapshot that shares the
 * generator (and its cache), so keys stay stable across appends/prepends.
 */
export class BenchList {
  private readonly cache: ItemCache;
  private readonly starts: Int32Array | null;
  private indexes: number[] | null = null;

  constructor(
    readonly kind: Kind,
    readonly seed: number,
    readonly start: number,
    readonly end: number,
    shared?: { cache: ItemCache; starts: Int32Array | null },
  ) {
    this.cache = shared?.cache ?? new ItemCache(4096);
    this.starts = shared?.starts ??
      (kind === "sections" ? sectionStarts(seed, end) : null);
  }

  get count(): number {
    return this.end - this.start;
  }

  /** Whether append/prepend are supported (not for `sections`, whose layout is fixed). */
  get canGrow(): boolean {
    return this.kind !== "sections";
  }

  /** The item at virtual index `v`. */
  itemAt(v: number): Item {
    return this.cache.get(v, () => this.generate(v));
  }

  /** The item at position `pos` (0-based within this snapshot). */
  getItem(pos: number): Item {
    return this.itemAt(this.start + pos);
  }

  /** Stable key of virtual index `v`. */
  keyOf(v: number): string {
    return `${this.kind[0]}${v}`;
  }

  /**
   * Virtual indices `[start, end)` as an array, for lists that need a `data` array. Built on
   * first use and kept (10M entries is ~40 MB of small integers: the lists that cannot take a
   * count pay it, the lists that can never build it).
   */
  indexArray(): number[] {
    if (!this.indexes) {
      const a = new Array<number>(this.count);
      for (let i = 0; i < a.length; i++) a[i] = this.start + i;
      this.indexes = a;
    }
    return this.indexes;
  }

  /** Whether every entry's size is known without measuring (`fixed`, `sections`). */
  get fixedLayout(): boolean {
    return this.kind === "fixed" || this.kind === "sections";
  }

  /** Whether position `pos` is a section header. */
  isHeader(pos: number): boolean {
    const starts = this.starts;
    if (!starts) return false;
    const v = this.start + pos;
    return starts[sectionOf(starts, v)] === v;
  }

  /** Exact size of position `pos` for the fixed-layout kinds; null for measured kinds. */
  fixedSize(pos: number): number | null {
    if (!this.fixedLayout) return null;
    return this.isHeader(pos) ? HEADER.height : FIXED.height;
  }

  /** Exact offset of position `pos` for the fixed-layout kinds; null for measured kinds. */
  fixedOffset(pos: number): number | null {
    if (!this.fixedLayout) return null;
    const starts = this.starts;
    if (!starts) return pos * FIXED.height;
    const v = this.start + pos;
    const s = sectionOf(starts, v);
    const headersBefore = starts[s] === v ? s : s + 1;
    return pos * FIXED.height - headersBefore * (FIXED.height - HEADER.height);
  }

  /** Positions of the section headers (`sections` only; else empty). */
  stickyIndices(): number[] {
    return this.starts ? Array.from(this.starts) : [];
  }

  /** The list as sections (`sections` only; else one section holding everything). */
  sections(): SectionSpec[] {
    const starts = this.starts;
    if (!starts) {
      return [{
        key: "all",
        header: {
          type: "header",
          id: "h-all",
          title: "All",
          count: this.count,
        },
        data: this.indexArray(),
      }];
    }
    const out: SectionSpec[] = [];
    for (let s = 0; s < starts.length; s++) {
      const from = starts[s] + 1;
      const to = s + 1 < starts.length ? starts[s + 1] : this.end;
      const data = new Array<number>(Math.max(0, to - from));
      for (let i = 0; i < data.length; i++) data[i] = from + i;
      out.push({
        key: `h${starts[s]}`,
        header: this.itemAt(starts[s]) as HeaderItem,
        data,
      });
    }
    return out;
  }

  withAppended(k: number): BenchList {
    if (!this.canGrow) return this;
    return new BenchList(
      this.kind,
      this.seed,
      this.start,
      this.end + k,
      this.shared(),
    );
  }

  withPrepended(k: number): BenchList {
    if (!this.canGrow) return this;
    return new BenchList(
      this.kind,
      this.seed,
      this.start - k,
      this.end,
      this.shared(),
    );
  }

  private shared() {
    return { cache: this.cache, starts: this.starts };
  }

  private generate(v: number): Item {
    switch (this.kind) {
      case "fixed":
        return genRow(this.seed, v);
      case "chat":
        return genChat(this.seed, v);
      case "images":
        return genImage(this.seed, v);
      case "sections": {
        const starts = this.starts as Int32Array;
        const s = sectionOf(starts, v);
        if (starts[s] === v) {
          const next = s + 1 < starts.length ? starts[s + 1] : this.end;
          return {
            type: "header",
            id: `h${v}`,
            title: `Group ${s + 1}`,
            count: next - v - 1,
          };
        }
        return genRow(this.seed, v);
      }
    }
  }
}

/** The bench data for `(kind, n, seed)`: a lazy snapshot of `n` entries. */
export function makeItems(kind: Kind, n: number, seed = 1): BenchList {
  return new BenchList(kind, seed, 0, n);
}
