// denext-ota-template: 8 sha256=08e44e9ad013d0995d7425047c5aeb5504280339a026f5d8e3fbb0af8587853e
// Generated by `denext mobile add-ota` (denext over-the-air UI updates). Safe to commit;
// re-run `denext mobile add-ota` after upgrading denext (then ship a new binary). See
// https://denext.dev/docs/desktop.

package dev.denext.ota;

import android.content.Context;
import com.getcapacitor.Bridge;
import com.getcapacitor.ServerPath;
import java.io.File;

/**
 * Wires denext's over-the-air UI into a Capacitor {@code BridgeActivity}. Call it from
 * {@code MainActivity.onCreate} BEFORE {@code super.onCreate}, which builds the bridge:
 *
 * <pre>{@code
 * public class MainActivity extends BridgeActivity {
 *     @Override
 *     protected void onCreate(Bundle savedInstanceState) {
 *         DenextOta.prepare(this, bridgeBuilder);
 *         super.onCreate(savedInstanceState);
 *     }
 * }
 * }</pre>
 *
 * It registers {@link DenextOtaPlugin} and points the bridge at the UI to start from: a
 * confirmed or trial over-the-air UI, else the bundled {@code public/}. A trial the app died
 * in twice is rolled back here, before the first page loads. {@code bridgeBuilder} is the
 * activity's own protected field, which is why the activity passes it in.
 *
 * <p>A WebView renderer that dies is recovered by the {@code MainActivity} denext composes: it
 * recreates the activity in the same process, which calls this again and keeps the same UI (a
 * launch's trial attempt is counted once per process). A renderer that dies three times within a
 * minute ends the app instead, and the next launch counts that as a failed trial attempt.
 */
public final class DenextOta {

    private DenextOta() {}

    /**
     * Registers the plugin and picks the start directory.
     *
     * @param context the activity (any context of the app works)
     * @param bridgeBuilder the activity's {@code bridgeBuilder}
     */
    public static void prepare(Context context, Bridge.Builder bridgeBuilder) {
        bridgeBuilder.addPlugin(DenextOtaPlugin.class);
        File directory = DenextOtaStore.get(context).startDirectory();
        if (directory != null) {
            bridgeBuilder.setServerPath(new ServerPath(ServerPath.PathType.BASE_PATH, directory.getAbsolutePath()));
        }
    }
}
