// Generated by `denext mobile add native-module`, which adds a line here per module. This is
// your file: register your own plugins here too. See https://denext.dev/docs/native-code.

package dev.denext.nativemodules;

import com.getcapacitor.BridgeActivity;

/**
 * Registers the app's own native modules. {@code MainActivity} calls {@link #register} in
 * {@code onCreate}, before {@code super.onCreate} builds the bridge.
 */
public final class DenextNativeModules {
    private DenextNativeModules() {}

    public static void register(BridgeActivity activity) {
        activity.registerPlugin(ScannerPlugin.class);
        // denext mobile add native-module adds registrations above this line.
    }
}
