// denext-native-module-template: 1 sha256=c7effab3d1bf1f7e79350bec3cf81ae8ea4bb3774a7bc5a30386810f5372b75b
// Generated by `denext mobile add native-module --name Scanner`. This is your code: edit it
// freely (an edited file is never replaced). See https://denext.dev/docs/native-code.

package dev.denext.nativemodules

import com.getcapacitor.JSObject
import com.getcapacitor.Plugin
import com.getcapacitor.PluginCall
import com.getcapacitor.PluginMethod
import com.getcapacitor.annotation.CapacitorPlugin

/**
 * The native module `Scanner`: reached from the web app as `nativeModule("Scanner")`
 * (denext/mobile), `native/NativeScanner.ts`, or in React Native mode as
 * `TurboModuleRegistry.getEnforcing("Scanner")` / `NativeModules.Scanner`.
 * `DenextNativeModules.register` (called from MainActivity) registers it.
 *
 * Every method is asynchronous: resolve the call (`call.resolve(...)`) or reject it. React
 * Native mode passes positional arguments as `args` and unwraps a `value` result.
 *
 * - `echo(message)`: resolves `{ value: message }` and sends the `echoed` event.
 */
@CapacitorPlugin(name = "Scanner")
class ScannerPlugin : Plugin() {
    @PluginMethod
    fun echo(call: PluginCall) {
        val args = call.getArray("args")
        val message = if (args != null && args.length() > 0) {
            args.optString(0)
        } else {
            call.getString("message") ?: ""
        }
        call.resolve(JSObject().put("value", message))
        notifyListeners("echoed", JSObject().put("message", message))
    }
}
