// denext-context-menu-template: 2 sha256=f5ae4fea3a54fbbe4387278b0acef83cc2f46bc7c29f6aa3f099896be7154a2d
// Generated by `denext mobile add context-menu` (denext native menus). Safe to commit;
// re-run it after upgrading denext (then ship a new binary). See https://denext.dev/docs/mobile.

package dev.denext.contextmenu;

import android.graphics.Color;
import android.os.Build;
import android.text.SpannableString;
import android.text.Spanned;
import android.text.style.ForegroundColorSpan;
import android.view.Gravity;
import android.view.HapticFeedbackConstants;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.view.ViewGroup;
import android.webkit.WebView;
import android.widget.PopupMenu;
import com.getcapacitor.JSArray;
import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;
import java.util.ArrayList;
import java.util.List;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * The native side of {@code showContextMenu()} / {@code useContextMenu()} from
 * {@code denext/mobile}, reached from the web app as
 * {@code window.Capacitor.Plugins.DenextContextMenu}. {@code MainActivity} registers it
 * ({@code registerPlugin(DenextContextMenuPlugin.class)} before {@code super.onCreate}).
 *
 * <p>{@code show({ items, title?, x, y, haptic? })} opens a Material {@link PopupMenu} anchored
 * at the page point (CSS px from the viewport's top-left) and resolves {@code { selectedId }},
 * {@code null} when it is dismissed. Disabled items are shown but not selectable, destructive
 * ones are drawn in the Material error color, and a submenu's items are listed as a group
 * under a header with its label (so none is ever out of reach). {@code haptic} plays the
 * long-press haptic as the menu opens.
 *
 * <p>{@code dismiss({ target })}: {@code "menu"} closes the menu {@code show} opened (answered as
 * dismissed); {@code "sheet"} closes the system action sheet {@code @capacitor/action-sheet}
 * shows (its {@code BottomSheetDialogFragment}), for React Native mode's
 * {@code ActionSheetIOS.dismissActionSheet()}. Resolves {@code { dismissed }}.
 */
@CapacitorPlugin(name = "DenextContextMenu")
public class DenextContextMenuPlugin extends Plugin {

    /** Material 3's error color (light scheme), for destructive items. */
    private static final int DESTRUCTIVE = Color.rgb(0xb3, 0x26, 0x1e);

    /** The tag {@code @capacitor/action-sheet} shows its sheet fragment under. */
    private static final String CAPACITOR_ACTION_SHEET = "capacitorModalsActionSheet";

    /** The open menu's call (answered once), its anchor view and the menu. */
    private PluginCall pending;
    private View anchor;
    private PopupMenu popup;

    @PluginMethod
    public void show(PluginCall call) {
        JSArray items = call.getArray("items", new JSArray());
        if (items.length() == 0) {
            JSObject none = new JSObject();
            none.put("selectedId", JSObject.NULL);
            call.resolve(none);
            return;
        }
        double x = call.getDouble("x", 0.0);
        double y = call.getDouble("y", 0.0);
        boolean haptic = Boolean.TRUE.equals(call.getBoolean("haptic", false));
        getActivity().runOnUiThread(() -> present(call, items, x, y, haptic));
    }

    private void present(PluginCall call, JSArray items, double x, double y, boolean haptic) {
        finish(null);
        WebView web = getBridge().getWebView();
        if (web == null || !(web.getParent() instanceof ViewGroup)) {
            call.reject("the web view is not ready", "unavailable");
            return;
        }
        ViewGroup parent = (ViewGroup) web.getParent();
        float density = web.getResources().getDisplayMetrics().density;
        View point = new View(getContext());
        parent.addView(point, new ViewGroup.LayoutParams(1, 1));
        point.setX(web.getX() + (float) (x * density));
        point.setY(web.getY() + (float) (y * density));
        pending = call;
        anchor = point;

        PopupMenu popup = new PopupMenu(getContext(), point, Gravity.NO_GRAVITY);
        List<String> ids = new ArrayList<>();
        try {
            addItems(popup.getMenu(), items, ids, false, 0);
        } catch (JSONException e) {
            finish(null);
            return;
        }
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) popup.getMenu().setGroupDividerEnabled(true);
        popup.setOnMenuItemClickListener((MenuItem item) -> {
            int index = item.getItemId();
            if (index < 0 || index >= ids.size() || ids.get(index) == null) return false;
            finish(ids.get(index));
            return true;
        });
        // A dismissal also follows a choice; finish() answers only the first.
        popup.setOnDismissListener((PopupMenu menu) -> web.post(() -> finish(null)));
        if (haptic) web.performHapticFeedback(HapticFeedbackConstants.LONG_PRESS);
        this.popup = popup;
        popup.show();
    }

    @PluginMethod
    public void dismiss(PluginCall call) {
        boolean sheet = "sheet".equals(call.getString("target", "menu"));
        getActivity().runOnUiThread(() -> {
            JSObject result = new JSObject();
            result.put("dismissed", sheet ? dismissSheet() : dismissMenu());
            call.resolve(result);
        });
    }

    /** Close the menu {@code show} opened; its dismiss listener answers the call. */
    private boolean dismissMenu() {
        PopupMenu open = popup;
        if (open == null || pending == null) return false;
        popup = null;
        open.dismiss();
        return true;
    }

    /** Close {@code @capacitor/action-sheet}'s sheet when it is up. */
    private boolean dismissSheet() {
        androidx.fragment.app.Fragment sheet =
            getActivity().getSupportFragmentManager().findFragmentByTag(CAPACITOR_ACTION_SHEET);
        if (!(sheet instanceof androidx.fragment.app.DialogFragment) || !sheet.isAdded()) return false;
        ((androidx.fragment.app.DialogFragment) sheet).dismissAllowingStateLoss();
        return true;
    }

    /**
     * Add {@code items} to {@code menu} in group {@code group}; a submenu becomes a disabled
     * header item with its label, followed by its items, in a group of their own.
     */
    private int addItems(Menu menu, JSONArray items, List<String> ids, boolean disabled, int group)
        throws JSONException {
        int next = group;
        for (int i = 0; i < items.length(); i++) {
            JSONObject item = items.getJSONObject(i);
            String label = item.optString("label", "");
            boolean off = disabled || item.optBoolean("disabled", false);
            if (item.has("subtitle")) label = label + " — " + item.optString("subtitle", "");
            JSONArray children = item.optJSONArray("children");
            if (children != null) {
                int sub = ++next;
                ids.add(null);
                MenuItem header = menu.add(sub, ids.size() - 1, Menu.NONE, label);
                header.setEnabled(false);
                next = addItems(menu, children, ids, off, sub);
                continue;
            }
            ids.add(item.optString("id", ""));
            CharSequence title = label;
            if (item.optBoolean("destructive", false)) {
                SpannableString red = new SpannableString(label);
                red.setSpan(new ForegroundColorSpan(DESTRUCTIVE), 0, label.length(), Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);
                title = red;
            }
            MenuItem entry = menu.add(group, ids.size() - 1, Menu.NONE, title);
            entry.setEnabled(!off);
        }
        return next;
    }

    /** Answer the open menu's call once (and remove its anchor). */
    private void finish(String id) {
        PluginCall call = pending;
        pending = null;
        popup = null;
        if (anchor != null && anchor.getParent() instanceof ViewGroup) {
            ((ViewGroup) anchor.getParent()).removeView(anchor);
        }
        anchor = null;
        if (call == null) return;
        JSObject result = new JSObject();
        result.put("selectedId", id == null ? JSObject.NULL : id);
        call.resolve(result);
    }
}
