/** The "backend": a static list, so the example runs with no server and no network. */
export interface Post {
  id: string;
  title: string;
  body: string;
}

const POSTS: Post[] = [
  {
    id: "1",
    title: "Library mode is just SPA mode",
    body:
      "TanStack Router mounts in the browser; denext bundles the entry, serves the shell for every URL, and stays out of the way.",
  },
  {
    id: "2",
    title: "Loaders run in the browser",
    body:
      "A route loader here is plain client code. For server data, add a denext route handler under app/api and fetch it.",
  },
  {
    id: "3",
    title: "One codegen step",
    body:
      "src/routeTree.gen.ts is generated by the TanStack Router CLI — run `deno task routes` after adding a route file.",
  },
];

export function listPosts(): Post[] {
  return POSTS;
}

export function getPost(id: string): Post | undefined {
  return POSTS.find((p) => p.id === id);
}
