import { createRoot } from "react-dom/client";
import { createRouter, RouterProvider } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen.ts";
import "./styles.css";

// File-based routing: `src/routes/**` → `routeTree.gen.ts`, generated by the TanStack
// Router CLI (`deno task routes`), the same tree the Vite plugin would generate.
const router = createRouter({ routeTree, defaultPreload: "intent", scrollRestoration: true });

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}

createRoot(document.getElementById("app")!).render(<RouterProvider router={router} />);
