// `denext generate migration | seed | ci` (src/build/generate-ops.ts): what each writes, the
// flavor detection, and — because a scaffold that does not run is worse than none — the
// generated migrate and seed tasks executed against a real `node:sqlite` file.

import { assert, assertEquals, assertMatch, assertRejects } from "@std/assert";
import { join, toFileUrl } from "@std/path";
import { parse as parseYaml } from "@std/yaml";
import { generateArtifact, OPTIONAL_NAME_KINDS } from "../src/build/generate.ts";
import { migrationPlan, slugName } from "../src/build/generate-ops.ts";

const SERVER_MOD = toFileUrl(join(Deno.cwd(), "src/server/mod.ts")).href;

async function project(files: Record<string, string> = {}): Promise<string> {
  const dir = await Deno.makeTempDir({ prefix: "denext_gen_ops_" });
  await Deno.writeTextFile(join(dir, "deno.json"), files["deno.json"] ?? "{}");
  for (const [rel, text] of Object.entries(files)) {
    if (rel === "deno.json") continue;
    await Deno.mkdir(join(dir, rel, ".."), { recursive: true });
    await Deno.writeTextFile(join(dir, rel), text);
  }
  return dir;
}

/** Import a generated task file with `denext/server` pointed at this checkout. */
async function runGeneratedTask(path: string): Promise<unknown> {
  const text = await Deno.readTextFile(path);
  const runnable = path.replace(/\.ts$/, ".run.ts");
  await Deno.writeTextFile(runnable, text.replace('"denext/server"', JSON.stringify(SERVER_MOD)));
  const mod = await import(toFileUrl(runnable).href);
  const signal = new AbortController().signal;
  return await mod.default.handler({ name: "t", trigger: "manual", signal, attempt: 1 });
}

Deno.test("slugName: a file-safe migration name", () => {
  assertEquals(slugName("Add users"), "add_users");
  assertEquals(slugName("  create-Posts table!! "), "create_posts_table");
  assertEquals(slugName("../x"), "x");
});

Deno.test("generate migration: a timestamped SQL file and, the first time, tasks/migrate.ts", async () => {
  const dir = await project();
  try {
    const first = await generateArtifact(dir, "migration", "add users");
    assertEquals(first.written.length, 2);
    assertMatch(first.written[0], /migrations[\\/]\d{14}_add_users\.sql$/);
    assertEquals(first.written[1], join(dir, "tasks", "migrate.ts"));
    const plan = await migrationPlan(dir, "add posts", new Date("2026-10-07T09:30:05Z"));
    assertEquals(plan.map((f) => f.path), [
      join(dir, "migrations", "20261007093005_add_posts.sql"),
    ]);
    assert(plan[0].contents.startsWith("-- Generated by `denext generate migration`"));
    await assertRejects(() => generateArtifact(dir, "migration", "!!!"), Error, "no letters");
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test("generate migration: a Prisma or Drizzle project is pointed at its own tool", async () => {
  const prisma = await project({ "prisma/schema.prisma": "datasource db {}" });
  const drizzle = await project({ "drizzle.config.ts": "export default {};" });
  try {
    await assertRejects(() => generateArtifact(prisma, "migration", "x"), Error, "prisma migrate");
    await assertRejects(() => generateArtifact(drizzle, "migration", "x"), Error, "drizzle-kit");
  } finally {
    await Deno.remove(prisma, { recursive: true });
    await Deno.remove(drizzle, { recursive: true });
  }
});

Deno.test("the generated migrate and seed tasks run on node:sqlite, once each migration", async () => {
  const dir = await project();
  const before = Deno.env.get("DB_PATH");
  Deno.env.set("DB_PATH", join(dir, "app.db"));
  try {
    await generateArtifact(dir, "migration", "create example");
    await generateArtifact(dir, "seed", "");
    const migrate = join(dir, "tasks", "migrate.ts");
    assertMatch(String(await runGeneratedTask(migrate)), /^applied \d{14}_create_example\.sql$/);
    assertEquals(await runGeneratedTask(migrate), "up to date", "a migration runs once");
    assertEquals(await runGeneratedTask(join(dir, "tasks", "seed.ts")), "seeded");
    assertEquals(await runGeneratedTask(join(dir, "tasks", "seed.ts")), "seeded", "idempotent");
    const { DatabaseSync } = await import("node:sqlite");
    const db = new DatabaseSync(join(dir, "app.db"));
    try {
      assertEquals(db.prepare("SELECT COUNT(*) AS n FROM example").get()?.n, 3);
      assertEquals(db.prepare("SELECT COUNT(*) AS n FROM _migrations").get()?.n, 1);
    } finally {
      db.close();
    }
    // A failing migration rolls back and names itself.
    await Deno.writeTextFile(join(dir, "migrations", "99999999999999_bad.sql"), "NOT SQL;");
    await assertRejects(() => runGeneratedTask(migrate), Error, "99999999999999_bad.sql");
  } finally {
    if (before === undefined) Deno.env.delete("DB_PATH");
    else Deno.env.set("DB_PATH", before);
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test("generate seed: Prisma flavor detected or forced; an unknown flavor throws", async () => {
  const dir = await project({ "prisma/schema.prisma": "datasource db {}" });
  try {
    await generateArtifact(dir, "seed", "");
    const seed = await Deno.readTextFile(join(dir, "tasks", "seed.ts"));
    assert(seed.includes('from "@prisma/client"'), seed);
    const forced = await generateArtifact(dir, "seed", "sqlite", { dryRun: true, force: true });
    assert(forced.preview?.[0].contents.includes('from "node:sqlite"'));
    await assertRejects(() => generateArtifact(dir, "seed", "mongo"), Error, "unknown seed flavor");
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test("generate ci: the project's check + build tasks, Deno pinned, valid YAML", async () => {
  const dir = await project({
    "deno.json": '{ "tasks": { "check": "deno fmt --check", "build": "denext build ." } }',
  });
  try {
    const { written } = await generateArtifact(dir, "ci", "");
    assertEquals(written, [join(dir, ".github", "workflows", "ci.yml")]);
    const text = await Deno.readTextFile(written[0]);
    assert(text.startsWith("# Generated by `denext generate ci`"));
    const doc = parseYaml(text) as {
      jobs: { check: { steps: { run?: string; with?: Record<string, unknown> }[] } };
    };
    const steps = doc.jobs.check.steps;
    assertEquals(steps.filter((s) => s.run).map((s) => s.run), [
      "deno task check",
      "deno task build",
    ]);
    assertEquals(steps[1].with?.["deno-version"], `v${Deno.version.deno}`);
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test("generate ci: no check task → fmt/lint/test; a SPA builds with export", async () => {
  const dir = await project({
    "deno.json": '{ "tasks": { "export": "denext export ." } }',
    "denext.config.ts": 'export default { mode: "spa" };',
  });
  try {
    await generateArtifact(dir, "ci", "github");
    const doc = parseYaml(await Deno.readTextFile(join(dir, ".github/workflows/ci.yml"))) as {
      jobs: { check: { steps: { run?: string }[] } };
    };
    assertEquals(doc.jobs.check.steps.filter((s) => s.run).map((s) => s.run), [
      "deno fmt --check",
      "deno lint",
      "deno test -A",
      "deno task export",
    ]);
    await assertRejects(() => generateArtifact(dir, "ci", "jenkins"), Error, "unknown CI provider");
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test("seed and ci take no required name; migration does", () => {
  assert(OPTIONAL_NAME_KINDS.has("seed"));
  assert(OPTIONAL_NAME_KINDS.has("ci"));
  assert(!OPTIONAL_NAME_KINDS.has("migration"));
});
