// Drift checks for generated docs-site artifacts. Each test re-derives the artifact from
// its live source of truth and compares byte-for-byte with the committed file, so a change
// that isn't regenerated fails here instead of shipping a stale docs page.

import { assertEquals } from "@std/assert";
import { CLI_OUT, generateCliReference } from "../scripts/gen-cli-reference.ts";
import { generateMcpReference, MCP_OUT } from "../scripts/gen-mcp-reference.ts";
import { LLMS_FULL_OUT, LLMS_OUT, llmsFull, llmsIndex } from "../scripts/gen-llms-txt.ts";

Deno.test("docs: cli.json is regenerated from the command registry", async () => {
  // Adding/removing a verb, flag or positional (or editing its help text) without running
  // `deno task docs:cli` fails here.
  assertEquals(
    await Deno.readTextFile(CLI_OUT),
    generateCliReference(),
    "site/app/docs/cli/cli.json is stale — run `deno task docs:cli` (or `deno task docs:build`) and commit",
  );
});

Deno.test("docs: mcp.json is regenerated from the MCP tool registry", async () => {
  // Adding a tool, a parameter or an enum value to a description (a `denext_generate` kind)
  // without running `deno task docs:mcp` fails here.
  assertEquals(
    await Deno.readTextFile(MCP_OUT),
    generateMcpReference(),
    "site/app/docs/mcp/mcp.json is stale — run `deno task docs:mcp` (or `deno task docs:build`) and commit",
  );
});

Deno.test("docs: llms.txt and llms-full.txt are regenerated from AGENTS.md + the API reference", async () => {
  // Editing AGENTS.md, a public symbol (through the committed reference.json, itself
  // regenerated by `deno task docs:api`) or the MCP tool list without running
  // `deno task docs:llms` fails here.
  const stale = (name: string) =>
    `site/public/${name} is stale — run \`deno task docs:llms\` (or \`deno task docs:build\`) and commit`;
  assertEquals(await Deno.readTextFile(LLMS_OUT), llmsIndex(), stale("llms.txt"));
  assertEquals(await Deno.readTextFile(LLMS_FULL_OUT), await llmsFull(), stale("llms-full.txt"));
});

Deno.test("docs: the served install.sh matches the one in scripts/", async () => {
  // `curl -fsSL https://denext.dev/install.sh | sh` serves site/public/install.sh (the
  // static export copies public/ to the site root), but the file people read and review lives
  // in scripts/. Nothing generates the copy, so this is what stops the served installer —
  // the one that actually runs on someone's machine — from drifting away from the reviewed one.
  const root = new URL("../", import.meta.url);
  assertEquals(
    await Deno.readTextFile(new URL("site/public/install.sh", root)),
    await Deno.readTextFile(new URL("scripts/install.sh", root)),
    "site/public/install.sh is stale — `cp scripts/install.sh site/public/install.sh` and commit",
  );
});
