import { assert, assertEquals, assertStringIncludes } from "@std/assert";
import { deleteJsonValue, readJson, setJsonValue } from "../src/build/json-edit.ts";

const DENO_JSON = `{
  "//": "generated by denext migrate — safe to edit",
  "name": "my-app",
  "tasks": {
    // the dev server
    "dev": "deno run -A jsr:@denext/denext/cli dev ."
  },
  "imports": { "denext": "jsr:@denext/denext" },
  "nodeModulesDir": "auto"
}
`;

Deno.test("readJson: parses JSONC, comments and all", () => {
  const parsed = readJson(DENO_JSON) as Record<string, unknown>;
  assertEquals(Object.keys(parsed)[0], "//");
  assertEquals(
    (parsed.tasks as Record<string, string>).dev,
    "deno run -A jsr:@denext/denext/cli dev .",
  );
});

Deno.test("setJsonValue: adds a nested task, keeping comments, order and the `//` key", async () => {
  const r = await setJsonValue(DENO_JSON, ["tasks", "build"], "deno run -A cli.ts build .");
  assert(r.ok);
  assertEquals(
    r.source,
    `{
  "//": "generated by denext migrate — safe to edit",
  "name": "my-app",
  "tasks": {
    // the dev server
    "dev": "deno run -A jsr:@denext/denext/cli dev .",
    "build": "deno run -A cli.ts build ."
  },
  "imports": { "denext": "jsr:@denext/denext" },
  "nodeModulesDir": "auto"
}
`,
  );
  // Still strict JSON: no trailing comma was introduced.
  const parsed = readJson(r.source) as Record<string, Record<string, string>>;
  assertEquals(Object.keys(parsed), ["//", "name", "tasks", "imports", "nodeModulesDir"]);
  assertEquals(Object.keys(parsed.tasks), ["dev", "build"]);
});

Deno.test("setJsonValue: updates an existing value in place", async () => {
  const r = await setJsonValue(DENO_JSON, ["tasks", "dev"], "deno task dev");
  assert(r.ok);
  assertEquals(
    r.source,
    DENO_JSON.replace("deno run -A jsr:@denext/denext/cli dev .", "deno task dev"),
  );
  assertStringIncludes(r.diff, '+    "dev": "deno task dev"');
});

Deno.test("setJsonValue: creates a missing key and missing parents, with quoted keys", async () => {
  const top = await setJsonValue(DENO_JSON, ["lock"], false);
  assert(top.ok);
  assertStringIncludes(top.source, `  "nodeModulesDir": "auto",\n  "lock": false\n}`);

  const nested = await setJsonValue(DENO_JSON, ["compilerOptions", "jsx"], "react-jsx");
  assert(nested.ok);
  assertStringIncludes(nested.source, `  "compilerOptions": { "jsx": "react-jsx" }\n}`);
  assertEquals(
    (readJson(nested.source) as { compilerOptions: Record<string, string> }).compilerOptions.jsx,
    "react-jsx",
  );

  const inline = await setJsonValue(DENO_JSON, ["imports", "@std/path"], "jsr:@std/path@^1.0.0");
  assert(inline.ok);
  assertStringIncludes(
    inline.source,
    `  "imports": { "denext": "jsr:@denext/denext", "@std/path": "jsr:@std/path@^1.0.0" },\n`,
  );
});

Deno.test("deleteJsonValue: removes a member and refuses an absent one", async () => {
  const r = await deleteJsonValue(DENO_JSON, ["nodeModulesDir"]);
  assert(r.ok);
  assertStringIncludes(r.source, `  "imports": { "denext": "jsr:@denext/denext" }\n}`);
  assertEquals(readJson(r.source) as Record<string, unknown>, {
    "//": "generated by denext migrate — safe to edit",
    name: "my-app",
    tasks: { dev: "deno run -A jsr:@denext/denext/cli dev ." },
    imports: { denext: "jsr:@denext/denext" },
  });

  const absent = await deleteJsonValue(DENO_JSON, ["lock"]);
  assert(!absent.ok);
  assertStringIncludes(absent.reason, "`lock` is not set");
});

Deno.test("json-edit: byte offsets survive multi-byte characters, and a non-object bails", async () => {
  const src = `{\n  "//": "généré ☕",\n  "name": "café"\n}\n`;
  const r = await setJsonValue(src, ["name"], "thé");
  assert(r.ok);
  assertEquals(r.source, src.replace(`"café"`, `"thé"`));

  const list = await setJsonValue(`[1, 2]\n`, ["a"], 1);
  assert(!list.ok);
  assertStringIncludes(list.reason, "not a JSON object document");
});
