// denext-context-menu-template: 2 sha256=e097a7d1d54c6fd9f72677cfdedb0a799b55d8a6c5a1e57e43dd31749edbe267
// Generated by `denext mobile add context-menu` (denext native menus). Safe to commit;
// re-run it after upgrading denext (then ship a new binary). See https://denext.dev/docs/mobile.

@preconcurrency import Capacitor
import Foundation
import UIKit
import WebKit

/// The native side of `showContextMenu()` / `useContextMenu()` from `denext/mobile`, reached
/// from the web app as `window.Capacitor.Plugins.DenextContextMenu`.
/// `DenextBridgeViewController` registers it.
///
/// - `show({ items, title?, x, y, haptic? })`: a `UIMenu` at the page point (the edit-menu
///   presentation on iOS 16+, an action sheet on iOS 15). Resolves `{ selectedId }`, `null`
///   when it was dismissed.
/// - `arm({ token, items, title?, rect, cornerRadius })` / `disarm({ token })`: the element a
///   press just landed on. The web view's `UIContextMenuInteraction` shows that element's menu
///   on the system long press (or a secondary click), lifting a snapshot of the element as the
///   preview, and sends `menuAction` `{ token, id }` for the chosen item.
/// - `dismiss({ target })`: `"menu"` closes the menu `show` opened (answered as dismissed);
///   `"sheet"` closes a system action sheet another plugin presented (`@capacitor/action-sheet`,
///   for React Native mode's `ActionSheetIOS.dismissActionSheet()`). Resolves `{ dismissed }`.
///
/// Items are `{ id, label, systemIcon?, subtitle?, destructive?, disabled?, children? }`:
/// `systemIcon` is an SF Symbol name and `children` a submenu.
@objc(DenextContextMenuPlugin)
public class DenextContextMenuPlugin: CAPPlugin, CAPBridgedPlugin, @unchecked Sendable {
    public let identifier = "DenextContextMenuPlugin"
    public let jsName = "DenextContextMenu"
    public let pluginMethods: [CAPPluginMethod] = [
        CAPPluginMethod(name: "show", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "arm", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "disarm", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "dismiss", returnType: CAPPluginReturnPromise)
    ]

    /// Main-thread only. Owns the interactions on the web view.
    private var controller: DenextContextMenuController?

    override public func load() {
        // Attach the long-press interaction now, so the first press already finds it.
        DispatchQueue.main.async {
            _ = self.menuController()
        }
    }

    /// The controller for the bridge's web view (created on first use). Main thread.
    @MainActor private func menuController() -> DenextContextMenuController? {
        if let controller { return controller }
        guard let webView = bridge?.webView else { return nil }
        let made = DenextContextMenuController(webView: webView) { [weak self] token, id in
            self?.notifyListeners("menuAction", data: ["token": token, "id": id])
        }
        controller = made
        return made
    }

    private static func number(_ value: Any?) -> CGFloat {
        CGFloat((value as? NSNumber)?.doubleValue ?? 0)
    }

    @objc func show(_ call: CAPPluginCall) {
        let options = call.options ?? [:]
        let items = options["items"] as? [[String: Any]] ?? []
        if items.isEmpty {
            call.resolve(["selectedId": NSNull()])
            return
        }
        let title = options["title"] as? String
        let x = Self.number(options["x"])
        let y = Self.number(options["y"])
        let haptic = options["haptic"] as? Bool ?? false
        DispatchQueue.main.async {
            guard let controller = self.menuController() else {
                call.reject("the web view is not ready", "unavailable")
                return
            }
            if haptic { UIImpactFeedbackGenerator(style: .medium).impactOccurred() }
            controller.present(
                items: items,
                title: title,
                at: controller.viewPoint(x: x, y: y),
                from: self.bridge?.viewController
            ) { id in
                if let id {
                    call.resolve(["selectedId": id])
                } else {
                    call.resolve(["selectedId": NSNull()])
                }
            }
        }
    }

    @objc func arm(_ call: CAPPluginCall) {
        let options = call.options ?? [:]
        guard let token = options["token"] as? String,
              let items = options["items"] as? [[String: Any]],
              let rect = options["rect"] as? [String: Any] else {
            call.reject("token, items and rect are required", "invalid")
            return
        }
        let title = options["title"] as? String
        let radius = Self.number(options["cornerRadius"])
        let css = CGRect(
            x: Self.number(rect["x"]),
            y: Self.number(rect["y"]),
            width: Self.number(rect["width"]),
            height: Self.number(rect["height"])
        )
        DispatchQueue.main.async {
            guard let controller = self.menuController() else {
                call.reject("the web view is not ready", "unavailable")
                return
            }
            controller.arm(token: token, items: items, title: title, cssRect: css, cornerRadius: radius)
            call.resolve()
        }
    }

    @objc func disarm(_ call: CAPPluginCall) {
        let token = call.getString("token") ?? ""
        DispatchQueue.main.async {
            self.controller?.disarm(token: token)
            call.resolve()
        }
    }

    @objc func dismiss(_ call: CAPPluginCall) {
        let sheet = call.getString("target") == "sheet"
        DispatchQueue.main.async {
            let dismissed = sheet ? self.dismissSystemSheet() : (self.controller?.dismissMenu() ?? false)
            call.resolve(["dismissed": dismissed])
        }
    }

    /// The action sheet another plugin presented over the bridge (`@capacitor/action-sheet`).
    @MainActor private func dismissSystemSheet() -> Bool {
        guard let sheet = bridge?.viewController?.presentedViewController as? UIAlertController,
              sheet.preferredStyle == .actionSheet, !sheet.isBeingDismissed else { return false }
        sheet.dismiss(animated: true)
        return true
    }
}

/// Builds `UIMenu` elements from the page's items.
@MainActor
enum DenextMenuBuilder {
    static func elements(
        _ items: [[String: Any]],
        disabled: Bool = false,
        onSelect: @escaping (String) -> Void
    ) -> [UIMenuElement] {
        items.compactMap { item -> UIMenuElement? in
            guard let id = item["id"] as? String, let label = item["label"] as? String else {
                return nil
            }
            let image = (item["systemIcon"] as? String).flatMap { UIImage(systemName: $0) }
            let off = disabled || item["disabled"] as? Bool == true
            if let children = item["children"] as? [[String: Any]] {
                var options: UIMenu.Options = []
                if item["destructive"] as? Bool == true { options.insert(.destructive) }
                return UIMenu(
                    title: label,
                    image: image,
                    options: options,
                    children: elements(children, disabled: off, onSelect: onSelect)
                )
            }
            var attributes: UIMenuElement.Attributes = []
            if item["destructive"] as? Bool == true { attributes.insert(.destructive) }
            if off { attributes.insert(.disabled) }
            let action = UIAction(title: label, image: image, attributes: attributes) { _ in
                onSelect(id)
            }
            if let subtitle = item["subtitle"] as? String { action.subtitle = subtitle }
            return action
        }
    }

    /// Every selectable item, submenus flattened to `Parent › Child` (the iOS 15 action sheet).
    static func flatten(
        _ items: [[String: Any]],
        prefix: String = "",
        disabled: Bool = false
    ) -> [(id: String, label: String, destructive: Bool, disabled: Bool)] {
        items.flatMap { item -> [(id: String, label: String, destructive: Bool, disabled: Bool)] in
            guard let id = item["id"] as? String, let label = item["label"] as? String else {
                return []
            }
            let off = disabled || item["disabled"] as? Bool == true
            if let children = item["children"] as? [[String: Any]] {
                return flatten(children, prefix: prefix + label + " › ", disabled: off)
            }
            return [(id, prefix + label, item["destructive"] as? Bool == true, off)]
        }
    }
}

/// The web view's context-menu interaction (armed per press from the page) and the
/// programmatic menu presentation.
@MainActor
final class DenextContextMenuController: NSObject, UIContextMenuInteractionDelegate {
    /// The element a press armed: its menu, its rect in web view points, and when.
    struct Armed {
        let token: String
        let items: [[String: Any]]
        let title: String?
        let rect: CGRect
        let cornerRadius: CGFloat
        let at: Date
    }

    private weak var webView: WKWebView?
    private let send: (String, String) -> Void
    private var armed: Armed?
    /// The armed element whose menu is up (its preview is also the dismissal target).
    private var shown: Armed?
    private var presenter: AnyObject?
    /// The iOS 15 sheet `present` put up, and its answer, for `dismissMenu()`.
    private weak var sheet: UIAlertController?
    private var sheetComplete: ((String?) -> Void)?

    init(webView: WKWebView, send: @escaping (String, String) -> Void) {
        self.webView = webView
        self.send = send
        super.init()
        webView.addInteraction(UIContextMenuInteraction(delegate: self))
    }

    /// A page point (CSS px from the viewport's top-left) in the web view's coordinates.
    func viewPoint(x: CGFloat, y: CGFloat) -> CGPoint {
        viewRect(CGRect(x: x, y: y, width: 0, height: 0)).origin
    }

    private func viewRect(_ css: CGRect) -> CGRect {
        guard let scroll = webView?.scrollView else { return css }
        let inset = scroll.adjustedContentInset
        let zoom = scroll.zoomScale
        return CGRect(
            x: inset.left + css.minX * zoom,
            y: inset.top + css.minY * zoom,
            width: css.width * zoom,
            height: css.height * zoom
        )
    }

    func arm(token: String, items: [[String: Any]], title: String?, cssRect: CGRect, cornerRadius: CGFloat) {
        armed = Armed(
            token: token,
            items: items,
            title: title,
            rect: viewRect(cssRect),
            cornerRadius: cornerRadius,
            at: Date()
        )
    }

    func disarm(token: String) {
        if armed?.token == token { armed = nil }
    }

    // MARK: UIContextMenuInteractionDelegate

    func contextMenuInteraction(
        _ interaction: UIContextMenuInteraction,
        configurationForMenuAtLocation location: CGPoint
    ) -> UIContextMenuConfiguration? {
        // Only a press the page armed just now, on the element it armed; anything else is left
        // to WebKit (links, images, text).
        guard let current = armed, Date().timeIntervalSince(current.at) < 5,
              current.rect.insetBy(dx: -12, dy: -12).contains(location) else { return nil }
        shown = current
        let send = self.send
        return UIContextMenuConfiguration(identifier: current.token as NSString, previewProvider: nil) { _ in
            let children = DenextMenuBuilder.elements(current.items) { id in send(current.token, id) }
            return UIMenu(title: current.title ?? "", children: children)
        }
    }

    func contextMenuInteraction(
        _ interaction: UIContextMenuInteraction,
        previewForHighlightingMenuWithConfiguration configuration: UIContextMenuConfiguration
    ) -> UITargetedPreview? {
        targetedPreview()
    }

    func contextMenuInteraction(
        _ interaction: UIContextMenuInteraction,
        previewForDismissingMenuWithConfiguration configuration: UIContextMenuConfiguration
    ) -> UITargetedPreview? {
        targetedPreview()
    }

    func contextMenuInteraction(
        _ interaction: UIContextMenuInteraction,
        willEndFor configuration: UIContextMenuConfiguration,
        animator: UIContextMenuInteractionAnimating?
    ) {
        armed = nil
        animator?.addCompletion { [weak self] in self?.shown = nil }
    }

    /// The pressed element lifted out of the page: a snapshot of its rect, clipped to its
    /// corner radius (the web view itself clipped to the rect when no snapshot is available).
    private func targetedPreview() -> UITargetedPreview? {
        guard let current = shown, let webView, current.rect.width > 0, current.rect.height > 0 else {
            return nil
        }
        let rect = current.rect
        let parameters = UIPreviewParameters()
        parameters.backgroundColor = .clear
        if let snapshot = webView.resizableSnapshotView(
            from: rect,
            afterScreenUpdates: false,
            withCapInsets: .zero
        ) {
            snapshot.frame = CGRect(origin: .zero, size: rect.size)
            parameters.visiblePath = UIBezierPath(
                roundedRect: snapshot.bounds,
                cornerRadius: current.cornerRadius
            )
            let target = UIPreviewTarget(container: webView, center: CGPoint(x: rect.midX, y: rect.midY))
            return UITargetedPreview(view: snapshot, parameters: parameters, target: target)
        }
        parameters.visiblePath = UIBezierPath(roundedRect: rect, cornerRadius: current.cornerRadius)
        return UITargetedPreview(view: webView, parameters: parameters)
    }

    // MARK: programmatic menus

    func present(
        items: [[String: Any]],
        title: String?,
        at point: CGPoint,
        from viewController: UIViewController?,
        finish: @escaping (String?) -> Void
    ) {
        guard let webView else { return finish(nil) }
        if #available(iOS 16.0, *) {
            let menus = (presenter as? DenextEditMenuPresenter) ?? {
                let made = DenextEditMenuPresenter(view: webView)
                presenter = made
                return made
            }()
            menus.present(items: items, title: title, at: point, finish: finish)
            return
        }
        presentSheet(items: items, title: title, at: point, in: webView, from: viewController, finish: finish)
    }

    /// Close the menu `present` put up, answering it as dismissed; false when none is up.
    func dismissMenu() -> Bool {
        if #available(iOS 16.0, *), let menus = presenter as? DenextEditMenuPresenter, menus.dismiss() {
            return true
        }
        guard let sheet, let complete = sheetComplete else { return false }
        sheetComplete = nil
        sheet.dismiss(animated: true) { complete(nil) }
        return true
    }

    /// iOS 15: the items as an action sheet (a popover at the point on iPad).
    private func presentSheet(
        items: [[String: Any]],
        title: String?,
        at point: CGPoint,
        in webView: WKWebView,
        from viewController: UIViewController?,
        finish: @escaping (String?) -> Void
    ) {
        guard let viewController else { return finish(nil) }
        var done = false
        let complete = { (id: String?) in
            if done { return }
            done = true
            finish(id)
        }
        let sheet = UIAlertController(title: title, message: nil, preferredStyle: .actionSheet)
        for item in DenextMenuBuilder.flatten(items) {
            let action = UIAlertAction(title: item.label, style: item.destructive ? .destructive : .default) { _ in
                complete(item.id)
            }
            action.isEnabled = !item.disabled
            sheet.addAction(action)
        }
        sheet.addAction(UIAlertAction(title: "Cancel", style: .cancel) { _ in complete(nil) })
        sheet.popoverPresentationController?.sourceView = webView
        sheet.popoverPresentationController?.sourceRect = CGRect(origin: point, size: .zero)
        self.sheet = sheet
        sheetComplete = complete
        viewController.present(sheet, animated: true)
    }
}

/// iOS 16+: a `UIMenu` presented at a point through `UIEditMenuInteraction`.
@available(iOS 16.0, *)
@MainActor
final class DenextEditMenuPresenter: NSObject, @preconcurrency UIEditMenuInteractionDelegate {
    private var interaction: UIEditMenuInteraction?
    private var pending: (items: [[String: Any]], title: String?, finish: (String?) -> Void)?

    init(view: UIView) {
        super.init()
        let interaction = UIEditMenuInteraction(delegate: self)
        view.addInteraction(interaction)
        self.interaction = interaction
    }

    func present(items: [[String: Any]], title: String?, at point: CGPoint, finish: @escaping (String?) -> Void) {
        complete(nil) // a menu still up is answered as dismissed
        pending = (items, title, finish)
        interaction?.presentEditMenu(with: UIEditMenuConfiguration(identifier: nil, sourcePoint: point))
    }

    /// Close the menu that is up, answering it as dismissed; false when none is.
    func dismiss() -> Bool {
        guard pending != nil else { return false }
        interaction?.dismissMenu()
        complete(nil)
        return true
    }

    private func complete(_ id: String?) {
        guard let current = pending else { return }
        pending = nil
        current.finish(id)
    }

    func editMenuInteraction(
        _ interaction: UIEditMenuInteraction,
        menuFor configuration: UIEditMenuConfiguration,
        suggestedActions: [UIMenuElement]
    ) -> UIMenu? {
        guard let current = pending else { return nil }
        let children = DenextMenuBuilder.elements(current.items) { [weak self] id in self?.complete(id) }
        return UIMenu(title: current.title ?? "", children: children)
    }

    func editMenuInteraction(
        _ interaction: UIEditMenuInteraction,
        willDismissMenuFor configuration: UIEditMenuConfiguration,
        animator: UIEditMenuInteractionAnimating
    ) {
        // A chosen action runs before the dismissal finishes; anything else is a dismissal.
        animator.addCompletion { [weak self] in
            DispatchQueue.main.async { self?.complete(nil) }
        }
    }
}
