// denext-native-views-template: 1 sha256=828aa5de3a34ca6b3a8a0c4946e799aa576fc1c27e1562f10732b3a4a8d8246c
// Generated by denext mobile add native-views (denext native views). Safe to commit; re-run it
// after upgrading denext (then ship a new binary). See https://denext.dev/docs/mobile.

import AVFoundation
import AVKit
import UIKit

/// The built-in "video" native view: an AVPlayerViewController with the system controls.
///
/// Props: src (an absolute http(s) or file URL), autoplay, loop, muted, controls (default true),
/// fit ("contain" or "cover"). Events: ready { duration }, play, pause, ended, error { message }.
/// Commands: play, pause, seek { seconds }, status -> { currentTime, duration, playing }.
@objc(DenextVideoViewFactory)
public final class DenextVideoViewFactory: NSObject, DenextNativeViewFactory {
    private var players: [ObjectIdentifier: DenextVideoController] = [:]

    public func makeView(context: DenextNativeViewContext, props: [String: Any]) -> UIView {
        let player = DenextVideoController(context: context)
        let view: UIView = player.controller.view
        players[ObjectIdentifier(view)] = player
        player.apply(props)
        return view
    }

    public func updateView(_ view: UIView, props: [String: Any]) {
        players[ObjectIdentifier(view)]?.apply(props)
    }

    public func command(_ view: UIView, name: String, args: [String: Any]) -> [String: Any]? {
        return players[ObjectIdentifier(view)]?.command(name, args: args)
    }

    public func destroyView(_ view: UIView) {
        players.removeValue(forKey: ObjectIdentifier(view))?.tearDown()
    }
}

/// One video view. Main-thread only.
final class DenextVideoController: NSObject {
    let controller = AVPlayerViewController()
    private let player = AVPlayer()
    private let context: DenextNativeViewContext
    private var src: String?
    private var loop = false
    private var ended: NSObjectProtocol?
    private var statusObservation: NSKeyValueObservation?
    private var itemObservation: NSKeyValueObservation?

    init(context: DenextNativeViewContext) {
        self.context = context
        super.init()
        controller.player = player
        controller.view.backgroundColor = .black
        if let parent = context.viewController {
            parent.addChild(controller)
            controller.didMove(toParent: parent)
        }
        statusObservation = player.observe(\.timeControlStatus, options: [.new]) { [weak self] player, _ in
            let status = player.timeControlStatus
            DispatchQueue.main.async {
                self?.statusChanged(status)
            }
        }
    }

    func apply(_ props: [String: Any]) {
        loop = props["loop"] as? Bool ?? false
        player.isMuted = props["muted"] as? Bool ?? false
        controller.showsPlaybackControls = props["controls"] as? Bool ?? true
        controller.videoGravity = (props["fit"] as? String) == "cover" ? .resizeAspectFill : .resizeAspect
        guard let src = props["src"] as? String, src != self.src else {
            return
        }
        self.src = src
        guard let url = URL(string: src) else {
            context.emit("error", ["message": "src is not a URL"])
            return
        }
        let item = AVPlayerItem(url: url)
        observe(item)
        player.replaceCurrentItem(with: item)
        if props["autoplay"] as? Bool ?? false {
            player.play()
        }
    }

    private func observe(_ item: AVPlayerItem) {
        itemObservation = item.observe(\.status, options: [.new]) { [weak self] item, _ in
            let status = item.status
            let duration = item.duration.seconds
            let message = item.error?.localizedDescription ?? "the video could not be played"
            DispatchQueue.main.async {
                guard let self else {
                    return
                }
                if status == .readyToPlay {
                    self.context.emit("ready", ["duration": duration.isFinite ? duration : 0])
                } else if status == .failed {
                    self.context.emit("error", ["message": message])
                }
            }
        }
        if let ended {
            NotificationCenter.default.removeObserver(ended)
        }
        ended = NotificationCenter.default.addObserver(
            forName: .AVPlayerItemDidPlayToEndTime, object: item, queue: .main
        ) { [weak self] _ in
            self?.didEnd()
        }
    }

    private func didEnd() {
        context.emit("ended")
        if loop {
            player.seek(to: .zero)
            player.play()
        }
    }

    private func statusChanged(_ status: AVPlayer.TimeControlStatus) {
        if status == .playing {
            context.emit("play")
        } else if status == .paused {
            context.emit("pause")
        }
    }

    func command(_ name: String, args: [String: Any]) -> [String: Any]? {
        switch name {
        case "play":
            player.play()
        case "pause":
            player.pause()
        case "seek":
            let seconds = (args["seconds"] as? NSNumber)?.doubleValue ?? 0
            player.seek(to: CMTime(seconds: seconds, preferredTimescale: 600))
        default:
            break
        }
        let duration = player.currentItem?.duration.seconds ?? 0
        return [
            "currentTime": player.currentTime().seconds,
            "duration": duration.isFinite ? duration : 0,
            "playing": player.timeControlStatus == .playing
        ]
    }

    func tearDown() {
        player.pause()
        player.replaceCurrentItem(with: nil)
        statusObservation = nil
        itemObservation = nil
        if let ended {
            NotificationCenter.default.removeObserver(ended)
        }
        controller.willMove(toParent: nil)
        controller.view.removeFromSuperview()
        controller.removeFromParent()
    }
}
