// denext-native-views-template: 1 sha256=7f9c41f5eaf08a908efc4e7cacbfcc5ec0d7eb39790bfb96dc9caa90d2fa7345
// Generated by denext mobile add native-views (denext native views). Safe to commit; re-run it
// after upgrading denext (then ship a new binary). See https://denext.dev/docs/mobile.

@preconcurrency import Capacitor
import UIKit
import WebKit

/// What a factory gets to make a view: its id, the bridge's view controller (for views that need
/// a parent controller, such as AVPlayerViewController) and a way to send events to the page.
public final class DenextNativeViewContext {
    public let id: String
    public private(set) weak var viewController: UIViewController?
    private let sink: (String, [String: Any]) -> Void

    init(id: String, viewController: UIViewController?, sink: @escaping (String, [String: Any]) -> Void) {
        self.id = id
        self.viewController = viewController
        self.sink = sink
    }

    /// Send an event to the page: NativeViewSlot's onEvent(name, data).
    public func emit(_ name: String, _ data: [String: Any] = [:]) {
        sink(name, data)
    }
}

/// A native view type the page places with NativeViewSlot. Every method runs on the main thread.
/// Register one with DenextNativeViews.register("chart", ChartViewFactory()) before the page
/// makes a view (AppDelegate), or list its @objc class name under
/// plugins.DenextNativeViews.factories in capacitor.config.
public protocol DenextNativeViewFactory: AnyObject {
    /// Make the view for props (the slot's props, JSON values).
    func makeView(context: DenextNativeViewContext, props: [String: Any]) -> UIView
    /// Apply new props to a view this factory made.
    func updateView(_ view: UIView, props: [String: Any])
    /// Run a command from the page (the slot's command(name, args)); the result resolves it.
    func command(_ view: UIView, name: String, args: [String: Any]) -> [String: Any]?
    /// The view is leaving the page: stop what it runs.
    func destroyView(_ view: UIView)
}

public extension DenextNativeViewFactory {
    func command(_ view: UIView, name: String, args: [String: Any]) -> [String: Any]? {
        return nil
    }

    func destroyView(_ view: UIView) {}
}

/// The registry of native view types. Main-thread only.
public enum DenextNativeViews {
    private static var factories: [String: DenextNativeViewFactory] = [:]

    /// Make type available to NativeViewSlot (replacing a factory registered for it before).
    public static func register(_ type: String, _ factory: DenextNativeViewFactory) {
        factories[type] = factory
    }

    /// The factory for type, if one is registered.
    public static func factory(for type: String) -> DenextNativeViewFactory? {
        return factories[type]
    }

    /// Every registered type.
    public static var types: [String] {
        return factories.keys.sorted()
    }
}

/// A native view's host: clips it to the slot's visible part and decides which touches it takes.
final class DenextNativeViewHost: UIView {
    /// Whether touches over the host reach the view (false while page content covers the slot).
    var interactive = true
    /// Regions (host coordinates) that belong to the page: DOM overlays drawn over the view.
    var passthrough: [CGRect] = []

    override init(frame: CGRect) {
        super.init(frame: frame)
        clipsToBounds = true
        backgroundColor = .clear
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) is not used")
    }

    override func hitTest(_ point: CGPoint, with event: UIEvent?) -> UIView? {
        if isHidden || !interactive || !bounds.contains(point) {
            return nil
        }
        if passthrough.contains(where: { $0.contains(point) }) {
            return nil
        }
        return super.hitTest(point, with: event)
    }
}

/// The layer above the WebView: it draws the "over" views and routes a touch over any visible
/// "under" or "over" view to it. Everywhere else it takes no touch, so the WebView gets it.
///
/// It routes embedded views too: WebKit's own hit testing stops at the scroll view it made for
/// the slot and never reaches views it did not make, so without the router an embedded view's
/// controls would get no touch. The view's ancestors (the page's scroll views) still see the
/// touch, so a drag that starts on it scrolls the page.
final class DenextNativeViewsRouter: UIView {
    var hosts: () -> [DenextNativeViewHost] = { [] }

    override func hitTest(_ point: CGPoint, with event: UIEvent?) -> UIView? {
        for host in hosts() where host.window != nil && !host.isHidden {
            let local = convert(point, to: host)
            guard Self.unclipped(host, local) else {
                continue
            }
            if let hit = host.hitTest(local, with: event) {
                return hit
            }
        }
        return nil
    }

    /// Whether point (host coordinates) is inside every clipping ancestor of host: the part of an
    /// embedded view a scrolled page leaves visible.
    static func unclipped(_ host: UIView, _ point: CGPoint) -> Bool {
        var view = host.superview
        while let ancestor = view {
            if ancestor.clipsToBounds && !ancestor.bounds.contains(host.convert(point, to: ancestor)) {
                return false
            }
            view = ancestor.superview
        }
        return true
    }
}

/// A view on the page, as the plugin tracks it.
final class DenextNativeViewSlot {
    let id: String
    var placement: String
    let marker: CGFloat
    let factory: DenextNativeViewFactory
    let view: UIView
    let host = DenextNativeViewHost(frame: .zero)
    /// "under" / "over": the slot's box in its scroller's content coordinates (CSS px).
    var content = CGRect.zero
    /// The part of the slot (slot coordinates) left by clips between it and its scroller.
    var localClip: CGRect?
    /// The page asks for nothing to be drawn (inactive, or covered while "over").
    var hiddenByPage = true
    /// The page's overlays over the slot (slot coordinates): touches there go to the page.
    var passthrough: [CGRect] = []
    /// The UIScrollView the slot scrolls with (the WebView's own for the document).
    weak var scroller: UIScrollView?
    var scrollerIsDocument = false
    /// The last measured box and visible part on screen: used while the scroller is not found.
    var screenBox = CGRect.zero
    var screenClip: CGRect?

    init(id: String, placement: String, marker: CGFloat, factory: DenextNativeViewFactory, view: UIView) {
        self.id = id
        self.placement = placement
        self.marker = marker
        self.factory = factory
        self.view = view
    }
}

/// A scroll view held weakly (WebKit replaces the ones it makes).
struct DenextWeakScrollView {
    weak var view: UIScrollView?
}

/// The native side of NativeViewSlot / useNativeViewSlot from denext/mobile, reached from the web
/// app as window.Capacitor.Plugins.DenextNativeViews. DenextBridgeViewController registers it.
///
/// - types() -> { types }: the registered view types.
/// - create({ id, type, props, placement, embedMarker }) -> { placement }: makes the view.
///   "embed" falls back to "over" when the slot's scroll view is not found within 2 s.
/// - update({ frames, dpr }): each slot's box in its scroller's content coordinates, with the
///   scroller identified; the plugin follows that UIScrollView's contentOffset itself (KVO, in the
///   same frame as the scroll), so a scroll sends nothing.
/// - setProps({ id, props }), command({ id, name, args }) -> result, destroy({ id }).
/// - Event nativeViewEvent { id, name, data }: what a view emits.
@objc(DenextNativeViewsPlugin)
public class DenextNativeViewsPlugin: CAPPlugin, CAPBridgedPlugin, @unchecked Sendable {
    public let identifier = "DenextNativeViewsPlugin"
    public let jsName = "DenextNativeViews"
    public let pluginMethods: [CAPPluginMethod] = [
        CAPPluginMethod(name: "types", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "create", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "update", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "setProps", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "command", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "destroy", returnType: CAPPluginReturnPromise)
    ]

    /// Factories denext may install, found by class name when present (native-map).
    private static let builtIn: [String: String] = ["map": "DenextMapViewFactory"]
    /// How long "embed" looks for the slot's scroll view before falling back to "over".
    private static let embedAttempts = 40

    /// Main-thread only.
    private var slots: [String: DenextNativeViewSlot] = [:]
    /// Main-thread only. Creation order: the last one is on top.
    private var order: [String] = []
    private var underLayer: UIView?
    private var router: DenextNativeViewsRouter?
    /// Main-thread only. The page's scroll containers by the page's id for them.
    private var scrollers: [Int: DenextWeakScrollView] = [:]
    /// Main-thread only. contentOffset observations of every scroll view a slot moves with.
    private var observations: [ObjectIdentifier: NSKeyValueObservation] = [:]

    override public func load() {
        if DenextNativeViews.factory(for: "video") == nil {
            DenextNativeViews.register("video", DenextVideoViewFactory())
        }
        var classes = Self.builtIn
        for (type, value) in getConfig().getObject("factories") ?? [:] {
            if let name = value as? String {
                classes[type] = name
            }
        }
        for (type, name) in classes where DenextNativeViews.factory(for: type) == nil {
            if let factory = Self.instantiate(name) {
                DenextNativeViews.register(type, factory)
            }
        }
    }

    /// An NSObject factory class by its Objective-C name (or Swift name in the app module).
    private static func instantiate(_ name: String) -> DenextNativeViewFactory? {
        let module = (Bundle.main.infoDictionary?["CFBundleExecutable"] as? String ?? "App")
            .replacingOccurrences(of: " ", with: "_")
        let found: AnyClass? = NSClassFromString(name) ?? NSClassFromString(module + "." + name)
        guard let cls = found as? NSObject.Type else {
            return nil
        }
        return cls.init() as? DenextNativeViewFactory
    }

    @objc func types(_ call: CAPPluginCall) {
        DispatchQueue.main.async {
            call.resolve(["types": DenextNativeViews.types])
        }
    }

    @objc func create(_ call: CAPPluginCall) {
        guard let id = call.getString("id"), let type = call.getString("type") else {
            call.reject("id and type are required", "invalid")
            return
        }
        let props = Self.plain(call.getObject("props") ?? [:])
        let placement = call.getString("placement") ?? "over"
        let marker = CGFloat(call.getDouble("embedMarker") ?? 0)
        DispatchQueue.main.async {
            self.make(call, id: id, type: type, props: props, placement: placement, marker: marker)
        }
    }

    @objc func update(_ call: CAPPluginCall) {
        let frames = (call.getArray("frames") ?? []).compactMap { $0 as? JSObject }
        DispatchQueue.main.async {
            CATransaction.begin()
            CATransaction.setDisableActions(true)
            for frame in frames {
                self.apply(frame)
            }
            CATransaction.commit()
            call.resolve()
        }
    }

    @objc func setProps(_ call: CAPPluginCall) {
        let id = call.getString("id") ?? ""
        let props = Self.plain(call.getObject("props") ?? [:])
        DispatchQueue.main.async {
            guard let slot = self.slots[id] else {
                call.reject("no native view " + id, "not-found")
                return
            }
            slot.factory.updateView(slot.view, props: props)
            call.resolve()
        }
    }

    @objc func command(_ call: CAPPluginCall) {
        let id = call.getString("id") ?? ""
        let name = call.getString("name") ?? ""
        let args = Self.plain(call.getObject("args") ?? [:])
        DispatchQueue.main.async {
            guard let slot = self.slots[id] else {
                call.reject("no native view " + id, "not-found")
                return
            }
            if name == "__frame" {
                call.resolve(self.debugFrame(slot))
                return
            }
            call.resolve(slot.factory.command(slot.view, name: name, args: args) ?? [:])
        }
    }

    @objc func destroy(_ call: CAPPluginCall) {
        let id = call.getString("id") ?? ""
        DispatchQueue.main.async {
            if let slot = self.slots.removeValue(forKey: id) {
                self.order.removeAll { $0 == id }
                slot.host.removeFromSuperview()
                slot.factory.destroyView(slot.view)
            }
            if self.slots.isEmpty {
                self.observations.removeAll()
                self.scrollers.removeAll()
            }
            call.resolve()
        }
    }

    // MARK: - Making and placing views (main thread)

    private func make(_ call: CAPPluginCall, id: String, type: String, props: [String: Any], placement: String, marker: CGFloat) {
        guard let factory = DenextNativeViews.factory(for: type) else {
            call.reject("no native view type " + type + " is registered", "unknown-type")
            return
        }
        if slots[id] != nil {
            call.reject("a native view " + id + " already exists", "busy")
            return
        }
        let context = DenextNativeViewContext(id: id, viewController: bridge?.viewController) { [weak self] name, data in
            self?.notifyListeners("nativeViewEvent", data: ["id": id, "name": name, "data": data])
        }
        let view = factory.makeView(context: context, props: props)
        let slot = DenextNativeViewSlot(id: id, placement: placement, marker: marker, factory: factory, view: view)
        slot.host.addSubview(view)
        slots[id] = slot
        order.append(id)
        if placement == "embed" {
            embed(slot, call: call, attempt: 0)
            return
        }
        if placement != "under" {
            slot.placement = "over"
        }
        layer(slot)
        call.resolve(["placement": slot.placement])
    }

    /// Attach slot to its scroll view, retrying while WebKit has not made it yet.
    private func embed(_ slot: DenextNativeViewSlot, call: CAPPluginCall, attempt: Int) {
        guard slots[slot.id] === slot else {
            call.reject("the native view was destroyed", "cancelled")
            return
        }
        if attach(slot) {
            ensureRouter()
            call.resolve(["placement": "embed"])
            return
        }
        if attempt >= Self.embedAttempts {
            slot.placement = "over"
            layer(slot)
            call.resolve(["placement": "over"])
            return
        }
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.05) {
            self.embed(slot, call: call, attempt: attempt + 1)
        }
    }

    /// Add slot's host to the WebKit scroll view whose content is marker px taller than its box.
    private func attach(_ slot: DenextNativeViewSlot) -> Bool {
        guard let root = bridge?.webView?.scrollView else {
            return false
        }
        var stack: [UIView] = [root]
        while let view = stack.popLast() {
            if let scroller = view as? UIScrollView, scroller !== root,
               abs(scroller.contentSize.height - scroller.bounds.height - slot.marker) < 1,
               !scroller.subviews.contains(where: { $0 is DenextNativeViewHost && $0 !== slot.host }) {
                scroller.isScrollEnabled = false
                scroller.bounces = false
                scroller.showsVerticalScrollIndicator = false
                scroller.showsHorizontalScrollIndicator = false
                scroller.contentOffset = .zero
                slot.host.frame = CGRect(origin: .zero, size: scroller.bounds.size)
                slot.host.autoresizingMask = [.flexibleWidth, .flexibleHeight]
                slot.view.frame = slot.host.bounds
                slot.view.autoresizingMask = [.flexibleWidth, .flexibleHeight]
                scroller.addSubview(slot.host)
                return true
            }
            if !(view is DenextNativeViewHost) {
                stack.append(contentsOf: view.subviews)
            }
        }
        return false
    }

    /// Put slot's host in the layer under or over the WebView, hidden until its first frame.
    private func layer(_ slot: DenextNativeViewSlot) {
        guard let webView = bridge?.webView, let parent = webView.superview else {
            return
        }
        ensureRouter()
        slot.host.isHidden = true
        slot.view.autoresizingMask = []
        if slot.placement == "under" {
            if underLayer == nil {
                let below = UIView(frame: parent.bounds)
                below.autoresizingMask = [.flexibleWidth, .flexibleHeight]
                below.isUserInteractionEnabled = true
                parent.insertSubview(below, belowSubview: webView)
                underLayer = below
            }
            webView.isOpaque = false
            webView.backgroundColor = .clear
            webView.scrollView.backgroundColor = .clear
            underLayer?.addSubview(slot.host)
        } else {
            router?.addSubview(slot.host)
        }
    }

    /// The touch router above the WebView, added the first time a view is placed.
    private func ensureRouter() {
        guard router == nil, let webView = bridge?.webView, let parent = webView.superview else {
            return
        }
        let top = DenextNativeViewsRouter(frame: parent.bounds)
        top.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        top.backgroundColor = .clear
        top.hosts = { [weak self] in self?.routedHosts() ?? [] }
        parent.insertSubview(top, aboveSubview: webView)
        router = top
    }

    /// Every host, top-most first.
    private func routedHosts() -> [DenextNativeViewHost] {
        return order.reversed().compactMap { slots[$0]?.host }
    }

    /// Apply one frame from the page.
    private func apply(_ frame: JSObject) {
        guard let id = frame["id"] as? String, let slot = slots[id] else {
            return
        }
        slot.host.interactive = frame["interactive"] as? Bool ?? true
        slot.passthrough = Self.rects(frame["passthrough"])
        if slot.placement == "embed" {
            // The compositor moves and clips it; only a scroll view WebKit replaced needs work.
            if slot.host.window == nil {
                slot.host.removeFromSuperview()
                _ = attach(slot)
            }
            slot.host.isHidden = !(frame["active"] as? Bool ?? true)
            slot.host.passthrough = slot.passthrough
            return
        }
        slot.content = Self.rect(frame["content"] as? JSObject ?? [:])
        slot.localClip = (frame["localClip"] as? JSObject).map(Self.rect)
        slot.hiddenByPage = frame["hidden"] as? Bool ?? false
        slot.screenBox = Self.rect(frame)
        slot.screenClip = (frame["clip"] as? JSObject).map(Self.rect)
        if let scroller = frame["scroller"] as? JSObject {
            resolveScroller(slot, scroller)
        }
        layout(slot)
    }

    /// The "__frame" command (device tests): where the view is, in the page's coordinates, to
    /// compare with the slot's DOM box.
    private func debugFrame(_ slot: DenextNativeViewSlot) -> [String: Any] {
        var out: [String: Any] = [
            "placement": slot.placement,
            "hidden": slot.host.isHidden,
            "attached": slot.host.window != nil,
            "scrollerFound": slot.scroller != nil
        ]
        if let webView = bridge?.webView {
            let inset = webView.scrollView.adjustedContentInset
            let r = slot.view.convert(slot.view.bounds, to: webView).offsetBy(dx: -inset.left, dy: -inset.top)
            out["x"] = r.minX
            out["y"] = r.minY
            out["width"] = r.width
            out["height"] = r.height
        }
        return out
    }

    // MARK: - Following the page's scrolling (main thread)

    /// Find the UIScrollView the slot scrolls with, and observe it and every scroll view above it.
    private func resolveScroller(_ slot: DenextNativeViewSlot, _ info: JSObject) {
        guard let webView = bridge?.webView else {
            return
        }
        if info["kind"] as? String == "document" {
            slot.scroller = webView.scrollView
            slot.scrollerIsDocument = true
        } else {
            let key = Int(Self.number(info["id"]))
            let size = CGSize(width: Self.number(info["width"]), height: Self.number(info["height"]))
            if let cached = scrollers[key]?.view, cached.window != nil, Self.close(cached.bounds.size, size) {
                slot.scroller = cached
            } else {
                slot.scroller = findScroller(info, in: webView)
                scrollers[key] = DenextWeakScrollView(view: slot.scroller)
            }
            slot.scrollerIsDocument = false
        }
        var view: UIView? = slot.scroller
        while let current = view {
            if let scrollView = current as? UIScrollView, observations[ObjectIdentifier(scrollView)] == nil {
                observations[ObjectIdentifier(scrollView)] = scrollView.observe(\.contentOffset, options: []) { [weak self] _, _ in
                    // Called synchronously with the scroll: the views move in the same frame.
                    self?.layoutAll()
                }
            }
            if current === webView {
                break
            }
            view = current.superview
        }
    }

    /// The WebKit scroll view for a page scroll container: the one of its size whose content size
    /// and position are closest to what the page measured.
    private func findScroller(_ info: JSObject, in webView: WKWebView) -> UIScrollView? {
        let size = CGSize(width: Self.number(info["width"]), height: Self.number(info["height"]))
        let content = CGSize(width: Self.number(info["scrollWidth"]), height: Self.number(info["scrollHeight"]))
        let inset = webView.scrollView.adjustedContentInset
        let expected = CGPoint(x: Self.number(info["x"]) + inset.left, y: Self.number(info["y"]) + inset.top)
        var best: (UIScrollView, CGFloat)?
        var stack: [UIView] = [webView.scrollView]
        while let view = stack.popLast() {
            if view is DenextNativeViewHost {
                continue
            }
            stack.append(contentsOf: view.subviews)
            guard let candidate = view as? UIScrollView, candidate !== webView.scrollView,
                  Self.close(candidate.bounds.size, size) else {
                continue
            }
            let origin = candidate.convert(candidate.bounds.origin, to: webView)
            let score = abs(candidate.contentSize.width - content.width) + abs(candidate.contentSize.height - content.height)
                + abs(origin.x - expected.x) + abs(origin.y - expected.y)
            if best == nil || score < best!.1 {
                best = (candidate, score)
            }
        }
        return best?.0
    }

    /// Re-place every "under" and "over" view (a scroll view moved).
    private func layoutAll() {
        for id in order {
            if let slot = slots[id], slot.placement != "embed" {
                layout(slot)
            }
        }
    }

    /// Place a view from its content box and its scroller's current offset.
    private func layout(_ slot: DenextNativeViewSlot) {
        guard let webView = bridge?.webView, let container = slot.host.superview else {
            return
        }
        guard let scroller = slot.scroller, scroller.window != nil else {
            // Not found: the page's last measurement (a frame behind a scroll).
            let inset = webView.scrollView.adjustedContentInset
            let origin = webView.convert(CGPoint(x: inset.left, y: inset.top), to: container)
            let box = slot.screenBox.offsetBy(dx: origin.x, dy: origin.y)
            place(slot, box: box, visible: slot.screenClip?.offsetBy(dx: origin.x, dy: origin.y) ?? .null)
            return
        }
        var content = slot.content
        if slot.scrollerIsDocument {
            let zoom = scroller.zoomScale
            content = CGRect(x: content.minX * zoom, y: content.minY * zoom, width: content.width * zoom, height: content.height * zoom)
        }
        let box = scroller.convert(content, to: container)
        var visible = slot.localClip.map { $0.offsetBy(dx: box.minX, dy: box.minY).intersection(box) } ?? .null
        var view: UIView? = scroller
        while let current = view, !visible.isNull {
            if current.clipsToBounds || current is UIScrollView {
                visible = visible.intersection(current.convert(current.bounds, to: container))
            }
            if current === webView {
                break
            }
            view = current.superview
        }
        place(slot, box: box, visible: visible)
    }

    private func place(_ slot: DenextNativeViewSlot, box: CGRect, visible: CGRect) {
        if slot.hiddenByPage || visible.isNull || visible.isEmpty {
            slot.host.isHidden = true
            return
        }
        slot.host.frame = visible
        slot.view.frame = box.offsetBy(dx: -visible.minX, dy: -visible.minY)
        slot.host.passthrough = slot.passthrough.map {
            $0.offsetBy(dx: box.minX - visible.minX, dy: box.minY - visible.minY)
        }
        slot.host.isHidden = false
    }

    private static func close(_ a: CGSize, _ b: CGSize) -> Bool {
        return abs(a.width - b.width) < 2 && abs(a.height - b.height) < 2
    }

    /// A JS array of { x, y, width, height } as CGRects.
    static func rects(_ value: Any?) -> [CGRect] {
        return (value as? JSArray ?? []).compactMap { ($0 as? JSObject).map(rect) }
    }

    // MARK: - JSON helpers

    /// A JS number as CGFloat (0 when it is not one).
    static func number(_ value: Any?) -> CGFloat {
        if let n = value as? NSNumber {
            return CGFloat(n.doubleValue)
        }
        if let d = value as? Double {
            return CGFloat(d)
        }
        return 0
    }

    /// { x, y, width, height } as a CGRect.
    static func rect(_ o: JSObject) -> CGRect {
        return CGRect(x: number(o["x"]), y: number(o["y"]), width: number(o["width"]), height: number(o["height"]))
    }

    /// A JS object as a plain dictionary (nested objects and arrays converted too).
    static func plain(_ o: JSObject) -> [String: Any] {
        var out: [String: Any] = [:]
        for (key, value) in o {
            out[key] = plainValue(value)
        }
        return out
    }

    private static func plainValue(_ value: Any) -> Any {
        if let o = value as? JSObject {
            return plain(o)
        }
        if let a = value as? JSArray {
            return a.map { plainValue($0) }
        }
        return value
    }
}
