// Generated by `denext mobile add native-module`, which adds a line here per module. This is
// your file: register your own plugins here too. See https://denext.dev/docs/native-code.

@preconcurrency import Capacitor
import Foundation

/// Registers the app's own native modules with the bridge. `DenextBridgeViewController`
/// calls `register` from `capacitorDidLoad()`, before the first page loads.
@MainActor
enum DenextNativeModules {
    static func register(_ bridge: CAPBridgeProtocol?) {
        bridge?.registerPluginInstance(ScannerPlugin())
        // denext mobile add native-module adds registrations above this line.
    }
}
