// denext-app-extension-template: 2 sha256=b7a71361dfbac8afeabe1e0b11e6217c473dc5b4a82d9040b85f279eef555feb
// Generated by denext (denext mobile add). Safe to commit; re-run it after upgrading denext
// (then ship a new binary). denext mobile add-ota replaces this file with one that also serves
// the over-the-air UI. See https://denext.dev/docs/desktop.

@preconcurrency import Capacitor
import UIKit

/// A CAPBridgeViewController that registers denext's native plugins before the first page.
///
/// Use it where the app would use CAPBridgeViewController: Main.storyboard's view controller
/// class and SceneDelegate's root view controller (the installer sets both when they still name
/// CAPBridgeViewController). An app with its own bridge subclass changes that subclass's
/// superclass to DenextBridgeViewController and calls super from any capacitorDidLoad()
/// override.
class DenextBridgeViewController: CAPBridgeViewController {
    override func capacitorDidLoad() {
        super.capacitorDidLoad()
        // denext native menus: showContextMenu() / useContextMenu() in denext/mobile.
        bridge?.registerPluginInstance(DenextContextMenuPlugin())
        // denext SF Symbols: <SystemIcon> in denext/mobile.
        bridge?.registerPluginInstance(DenextSystemIconPlugin())
        // denext native views: NativeViewSlot in denext/mobile.
        bridge?.registerPluginInstance(DenextNativeViewsPlugin())
        // The app's own native modules (denext mobile add native-module).
        DenextNativeModules.register(bridge)
        // denext durable storage: openKeyValueStore() in denext/mobile.
        bridge?.registerPluginInstance(DenextStoragePlugin())
    }
}
