// denext-native-views-template: 3 sha256=06add5d670ee2ccee21bdcd8d5edb3bdcf05c190dd564e4acc8606c172b262d8
// Generated by denext mobile add native-map (denext native views). Safe to commit; re-run it
// after upgrading denext (then ship a new binary). See https://denext.dev/docs/mobile.

import MapKit
import UIKit

/// The "map" native view on iOS: an MKMapView (Apple Maps, no API key).
///
/// Props: latitude, longitude, zoom (web-map zoom levels, 0-20; default 12), markers
/// [{ latitude, longitude, title }], mapType ("standard", "satellite", "hybrid"), interactive
/// (default true). The region moves only when latitude, longitude or zoom change, so a pan is
/// never undone by other props. Events: regionChange { latitude, longitude, zoom },
/// markerPress { index, title }. Commands: setRegion { latitude, longitude, zoom, animated }.
/// DenextNativeViewsPlugin finds this class by its Objective-C name and registers it as "map".
@objc(DenextMapViewFactory)
public final class DenextMapViewFactory: NSObject, DenextNativeViewFactory, MKMapViewDelegate {
    private var contexts: [ObjectIdentifier: DenextNativeViewContext] = [:]
    private var regions: [ObjectIdentifier: [Double]] = [:]

    public func makeView(context: DenextNativeViewContext, props: [String: Any]) -> UIView {
        let map = MKMapView(frame: CGRect(x: 0, y: 0, width: 320, height: 240))
        map.delegate = self
        contexts[ObjectIdentifier(map)] = context
        apply(map, props, animated: false)
        return map
    }

    public func updateView(_ view: UIView, props: [String: Any]) {
        if let map = view as? MKMapView {
            apply(map, props, animated: true)
        }
    }

    public func command(_ view: UIView, name: String, args: [String: Any]) -> [String: Any]? {
        guard let map = view as? MKMapView, name == "setRegion" else {
            return nil
        }
        setRegion(map, args, animated: args["animated"] as? Bool ?? true)
        return [:]
    }

    public func destroyView(_ view: UIView) {
        if let map = view as? MKMapView {
            map.delegate = nil
            contexts.removeValue(forKey: ObjectIdentifier(map))
            regions.removeValue(forKey: ObjectIdentifier(map))
        }
    }

    private static func number(_ value: Any?) -> Double? {
        if let n = value as? NSNumber {
            return n.doubleValue
        }
        return value as? Double
    }

    private func apply(_ map: MKMapView, _ props: [String: Any], animated: Bool) {
        let key: [Double] = [Self.number(props["latitude"]) ?? Double.nan, Self.number(props["longitude"]) ?? Double.nan, Self.number(props["zoom"]) ?? 12]
        let last = regions[ObjectIdentifier(map)]
        if last == nil || zip(key, last ?? []).contains(where: { $0 != $1 && !($0.isNaN && $1.isNaN) }) {
            regions[ObjectIdentifier(map)] = key
            setRegion(map, props, animated: animated)
        }
        let interactive = props["interactive"] as? Bool ?? true
        map.isScrollEnabled = interactive
        map.isZoomEnabled = interactive
        map.isRotateEnabled = interactive
        map.isPitchEnabled = interactive
        switch props["mapType"] as? String {
        case "satellite":
            map.mapType = .satellite
        case "hybrid":
            map.mapType = .hybrid
        default:
            map.mapType = .standard
        }
        map.removeAnnotations(map.annotations)
        for (index, value) in (props["markers"] as? [Any] ?? []).enumerated() {
            guard let marker = value as? [String: Any],
                  let lat = Self.number(marker["latitude"]), let lon = Self.number(marker["longitude"]) else {
                continue
            }
            let pin = DenextMapMarker(index: index)
            pin.coordinate = CLLocationCoordinate2D(latitude: lat, longitude: lon)
            pin.title = marker["title"] as? String
            map.addAnnotation(pin)
        }
    }

    private func setRegion(_ map: MKMapView, _ props: [String: Any], animated: Bool) {
        guard let lat = Self.number(props["latitude"]), let lon = Self.number(props["longitude"]) else {
            return
        }
        let zoom = Self.number(props["zoom"]) ?? 12
        let width = max(Double(map.bounds.width), 256)
        let lonDelta = min(360, 360 / pow(2, zoom) * width / 256)
        let latDelta = min(170, lonDelta * cos(lat * .pi / 180))
        let region = MKCoordinateRegion(
            center: CLLocationCoordinate2D(latitude: lat, longitude: lon),
            span: MKCoordinateSpan(latitudeDelta: latDelta, longitudeDelta: lonDelta)
        )
        map.setRegion(region, animated: animated)
    }

    public func mapView(_ mapView: MKMapView, regionDidChangeAnimated animated: Bool) {
        let region = mapView.region
        let width = max(Double(mapView.bounds.width), 1)
        let zoom = log2(360 / max(region.span.longitudeDelta, 0.000001) * width / 256)
        contexts[ObjectIdentifier(mapView)]?.emit("regionChange", [
            "latitude": region.center.latitude,
            "longitude": region.center.longitude,
            "zoom": zoom
        ])
    }

    public func mapView(_ mapView: MKMapView, didSelect view: MKAnnotationView) {
        guard let pin = view.annotation as? DenextMapMarker else {
            return
        }
        contexts[ObjectIdentifier(mapView)]?.emit("markerPress", ["index": pin.index, "title": pin.title ?? ""])
    }
}

/// A marker that remembers its index in the markers prop.
final class DenextMapMarker: MKPointAnnotation {
    let index: Int

    init(index: Int) {
        self.index = index
        super.init()
    }
}
