// denext-native-module-template: 1 sha256=e7fbdbfafc46827395a6c1e293d50fb15421226f035ea5919688887884eda738
// Generated by `denext mobile add native-module --name Scanner`. This is your code: edit it
// freely (an edited file is never replaced). See https://denext.dev/docs/native-code.

@preconcurrency import Capacitor
import Foundation

/// The native module `Scanner`: reached from the web app as `nativeModule("Scanner")`
/// (denext/mobile), `native/NativeScanner.ts`, or in React Native mode as
/// `TurboModuleRegistry.getEnforcing("Scanner")` / `NativeModules.Scanner`.
/// `DenextNativeModules.register` registers it with the bridge.
///
/// Every method is asynchronous: resolve the call (`call.resolve([...])`) or reject it.
/// React Native mode passes positional arguments as `args` and unwraps a `value` result.
///
/// - `echo(message)`: resolves `{ value: message }` and sends the `echoed` event.
@objc(ScannerPlugin)
public class ScannerPlugin: CAPPlugin, CAPBridgedPlugin, @unchecked Sendable {
    public let identifier = "ScannerPlugin"
    public let jsName = "Scanner"
    public let pluginMethods: [CAPPluginMethod] = [
        CAPPluginMethod(name: "echo", returnType: CAPPluginReturnPromise)
    ]

    @objc func echo(_ call: CAPPluginCall) {
        let message = (call.getArray("args")?.first as? String) ?? call.getString("message") ?? ""
        call.resolve(["value": message])
        notifyListeners("echoed", data: ["message": message])
    }
}
