// denext-app-extension-template: 1 sha256=58249f6448ef0827a5e66224c8a8fc2125672e85124c12c80baad4a22be0a929
// Generated by denext mobile add live-activity (denext app extensions). Safe to commit and to
// edit (denext then keeps your version); re-run it after upgrading denext (then ship a new binary).
// See https://denext.dev/docs/desktop.

import ActivityKit
import SwiftUI
import WidgetKit

/// The Build Live Activity's UI: startLiveActivity("Build", attributes, state) shows it, and
/// context.state holds the latest state object (updateLiveActivity, or an ActivityKit push).
@available(iOS 16.1, *)
enum BuildLiveActivity {
    /// The Lock Screen / banner presentation.
    @ViewBuilder
    static func lockScreen(_ context: ActivityViewContext<DenextActivityAttributes>) -> some View {
        VStack(alignment: .leading, spacing: 6) {
            Text(context.state["title"]?.text ?? "Build").font(.headline)
            if let text = context.state["body"]?.text {
                Text(text).font(.subheadline).foregroundColor(.secondary)
            }
            if let progress = context.state["progress"]?.number {
                ProgressView(value: min(max(progress, 0), 1))
            }
        }
        .padding()
    }

    /// The Dynamic Island presentations.
    static func dynamicIsland(_ context: ActivityViewContext<DenextActivityAttributes>) -> DynamicIsland {
        DynamicIsland {
            DynamicIslandExpandedRegion(.leading) {
                Text(context.state["title"]?.text ?? "Build").font(.headline)
            }
            DynamicIslandExpandedRegion(.bottom) {
                Text(context.state["body"]?.text ?? "").font(.subheadline)
            }
        } compactLeading: {
            Text("Build".prefix(1))
        } compactTrailing: {
            if let progress = context.state["progress"]?.number {
                Text("\(Int(min(max(progress, 0), 1) * 100))%")
            }
        } minimal: {
            Text("Build".prefix(1))
        }
    }
}
