// denext-app-extension-template: 1 sha256=1e0dd53f320e45228a513745735331087ab81cf2b2eda20dddfa9044602bb891
// Generated by denext mobile add widget (denext app extensions). Safe to commit; re-run it after upgrading denext (then ship a new binary).
// See https://denext.dev/docs/desktop.

import Foundation
import SwiftUI

/// What setWidgetData(kind, data) from denext/mobile stored: the JSON the app wrote to the App
/// Group's shared defaults (key denext.widget.<kind>). The App Group is the extension's
/// Info.plist DenextAppGroup. A configurable widget passes the values the user chose as params:
/// setWidgetData(kind, data, { params }) stored the snapshot for exactly those values, and the
/// one stored without params is the fallback.
enum DenextWidgetStore {
    /// The App Group identifier from Info.plist, if set.
    static var appGroup: String? {
        guard let value = Bundle.main.object(forInfoDictionaryKey: "DenextAppGroup") as? String,
              !value.isEmpty else { return nil }
        return value
    }

    /// The defaults key: denext.widget.<kind>, or denext.widget.<kind>?<name>=<value>&… with
    /// the parameter names sorted.
    static func key(kind: String, params: [String: String] = [:]) -> String {
        let query = params.sorted { $0.key < $1.key }.map { "\($0.key)=\($0.value)" }
            .joined(separator: "&")
        return query.isEmpty ? "denext.widget.\(kind)" : "denext.widget.\(kind)?\(query)"
    }

    /// The raw JSON text for kind (and params, falling back to the snapshot stored without
    /// them), if the app stored any.
    static func json(kind: String, params: [String: String] = [:]) -> String? {
        guard let group = appGroup, let defaults = UserDefaults(suiteName: group) else { return nil }
        if !params.isEmpty, let text = defaults.string(forKey: key(kind: kind, params: params)) {
            return text
        }
        return defaults.string(forKey: key(kind: kind))
    }

    /// The stored JSON for kind (and params) as an object, if it is one.
    static func object(kind: String, params: [String: String] = [:]) -> [String: Any]? {
        guard let data = json(kind: kind, params: params)?.data(using: .utf8) else { return nil }
        return (try? JSONSerialization.jsonObject(with: data)) as? [String: Any]
    }

    /// The stored JSON for kind (and params) decoded as T.
    static func decode<T: Decodable>(
        _ type: T.Type,
        kind: String,
        params: [String: String] = [:]
    ) -> T? {
        guard let data = json(kind: kind, params: params)?.data(using: .utf8) else { return nil }
        return try? JSONDecoder().decode(type, from: data)
    }
}

extension View {
    /// The widget background: the system container background on iOS 17 and later, padding over
    /// the system background before.
    @ViewBuilder
    func denextWidgetBackground() -> some View {
        if #available(iOSApplicationExtension 17.0, *) {
            containerBackground(for: .widget) { Color(UIColor.systemBackground) }
        } else {
            padding().background(Color(UIColor.systemBackground))
        }
    }
}
