// denext-app-extension-template: 1 sha256=12fba00880133c2a17a2bfc4dffab6d82f878136a7fe97bce8c3fb564c93b04b
// Generated by denext mobile add live-activity (denext app extensions). Safe to commit; re-run it after upgrading denext (then ship a new binary).
// See https://denext.dev/docs/desktop.
// Rewritten while unedited whenever a Live Activity is added; if you edit it, add new names to
// both switches yourself.

import ActivityKit
import SwiftUI
import WidgetKit

/// Every denext Live Activity, dispatched on DenextActivityAttributes.name.
@available(iOS 16.1, *)
struct DenextLiveActivities: Widget {
    var body: some WidgetConfiguration {
        ActivityConfiguration(for: DenextActivityAttributes.self) { context in
            switch context.attributes.name {
            case "Build": BuildLiveActivity.lockScreen(context)
            default: DenextLiveActivities.fallback(context)
            }
        } dynamicIsland: { context in
            DenextLiveActivities.island(context)
        }
    }

    static func island(_ context: ActivityViewContext<DenextActivityAttributes>) -> DynamicIsland {
        switch context.attributes.name {
        case "Build": return BuildLiveActivity.dynamicIsland(context)
        default:
            return DynamicIsland {
                DynamicIslandExpandedRegion(.center) { fallback(context) }
            } compactLeading: {
                Text(context.attributes.name.prefix(1))
            } compactTrailing: {
                EmptyView()
            } minimal: {
                Text(context.attributes.name.prefix(1))
            }
        }
    }

    /// An activity whose name has no UI here: its name and state title.
    @ViewBuilder
    static func fallback(_ context: ActivityViewContext<DenextActivityAttributes>) -> some View {
        VStack(alignment: .leading) {
            Text(context.state["title"]?.text ?? context.attributes.name).font(.headline)
        }
        .padding()
    }
}
