// denext-app-extension-template: 1 sha256=ede5b5220be9aab8c0381f37d09e84b0376ac2a21d141d270e90ea78dc7deba4
// Generated by denext mobile add live-activity (denext app extensions). Safe to commit; re-run it after upgrading denext (then ship a new binary).
// See https://denext.dev/docs/desktop.
// Compiled into the widget extension AND the App target (both must agree on the type).

import Foundation
#if canImport(ActivityKit)
import ActivityKit
#endif

/// A JSON value: what startLiveActivity / updateLiveActivity pass from denext/mobile.
public enum DenextJSONValue: Codable, Hashable {
    case string(String)
    case number(Double)
    case bool(Bool)
    case array([DenextJSONValue])
    case object([String: DenextJSONValue])
    case null

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if container.decodeNil() {
            self = .null
        } else if let value = try? container.decode(Bool.self) {
            self = .bool(value)
        } else if let value = try? container.decode(Double.self) {
            self = .number(value)
        } else if let value = try? container.decode(String.self) {
            self = .string(value)
        } else if let value = try? container.decode([DenextJSONValue].self) {
            self = .array(value)
        } else {
            self = .object(try container.decode([String: DenextJSONValue].self))
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .string(let value): try container.encode(value)
        case .number(let value): try container.encode(value)
        case .bool(let value): try container.encode(value)
        case .array(let value): try container.encode(value)
        case .object(let value): try container.encode(value)
        case .null: try container.encodeNil()
        }
    }

    /// The value for display: a string as is, a number without a trailing .0, a bool as
    /// true/false; nil for null, arrays and objects.
    public var text: String? {
        switch self {
        case .string(let value): return value
        case .number(let value):
            return value.rounded() == value && abs(value) < 1e15 ? String(Int64(value)) : String(value)
        case .bool(let value): return value ? "true" : "false"
        default: return nil
        }
    }

    /// The number, if it is one.
    public var number: Double? {
        if case .number(let value) = self { return value }
        return nil
    }
}

/// The attributes of every denext Live Activity: its name (which UI renders it, see
/// DenextLiveActivities.swift) and the static values startLiveActivity passed. ContentState is
/// the dynamic state object, encoded as that plain JSON object, so an ActivityKit push update's
/// "content-state" is the same object updateLiveActivity takes.
@available(iOS 16.1, *)
public struct DenextActivityAttributes: ActivityAttributes {
    public struct ContentState: Codable, Hashable {
        public var values: [String: DenextJSONValue]

        public init(values: [String: DenextJSONValue]) {
            self.values = values
        }

        public init(from decoder: Decoder) throws {
            values = try decoder.singleValueContainer().decode([String: DenextJSONValue].self)
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.singleValueContainer()
            try container.encode(values)
        }

        public subscript(key: String) -> DenextJSONValue? {
            return values[key]
        }
    }

    public var name: String
    public var values: [String: DenextJSONValue]

    public init(name: String, values: [String: DenextJSONValue]) {
        self.name = name
        self.values = values
    }

    public subscript(key: String) -> DenextJSONValue? {
        return values[key]
    }
}
