// denext-app-extension-template: 1 sha256=01f4bea971cde45a5e4ccebc64cb9bf1cfe7f0c60fe3072991c6b678f559481c
// Generated by denext mobile add widget / live-activity (denext app extensions). Safe to commit; re-run it after upgrading denext (then ship a new binary).
// See https://denext.dev/docs/desktop.
// Rewritten while unedited whenever a widget or Live Activity is added; if you edit it, list new
// ones in body yourself.

import SwiftUI
import WidgetKit

/// The widget extension's entry point: every widget and the Live Activity UI.
@main
struct DenextWidgetsBundle: WidgetBundle {
    var body: some Widget {
        StatusWidget()
        if #available(iOSApplicationExtension 17.0, *) {
            StatusConfigurableWidget()
        }
        if #available(iOSApplicationExtension 16.1, *) {
            DenextLiveActivities()
        }
    }
}
