// denext-app-extension-template: 1 sha256=e6a0e8fab9fdd479f05944e26c1d0a541f5331c06c93ae027ee29c8b41860fef
// Generated by denext mobile add widget (denext app extensions). Safe to commit and to
// edit (denext then keeps your version); re-run it after upgrading denext (then ship a new binary).
// See https://denext.dev/docs/desktop.
// denext-widget-configurable: mode:enum=compact|detailed
// (re-running `denext mobile add widget --name Status` without --configurable keeps these).

import AppIntents
import SwiftUI
import WidgetKit

/// One timeline entry of the Status widget.
struct StatusEntry: TimelineEntry {
    let date: Date
    let title: String
    let text: String
    /// The values the user chose, by parameter name (the defaults on iOS 14–16).
    let params: [String: String]
}

/// Reads what setWidgetData("Status", data, { params }) stored for the chosen values, else what
/// setWidgetData("Status", data) stored; reloadWidgets("Status") (and every setWidgetData)
/// asks WidgetKit for new timelines.
enum StatusSnapshot {
    /// Each parameter's default: its first value.
    static let defaults: [String: String] = [
        "mode": "compact",
    ]

    static func placeholder() -> StatusEntry {
        StatusEntry(date: Date(), title: "Status", text: "", params: defaults)
    }

    static func entry(_ params: [String: String]) -> StatusEntry {
        let data = DenextWidgetStore.object(kind: "Status", params: params) ?? [:]
        return StatusEntry(
            date: Date(),
            title: data["title"] as? String ?? "Status",
            text: data["body"] as? String ?? "Open the app to load this widget.",
            params: params
        )
    }
}

/// The widget's view: edit it freely (entry.params holds the chosen values).
struct StatusWidgetView: View {
    let entry: StatusEntry

    var body: some View {
        VStack(alignment: .leading, spacing: 4) {
            Text(entry.title).font(.headline).lineLimit(2)
            Text(entry.text).font(.subheadline).foregroundColor(.secondary).lineLimit(4)
            Spacer(minLength: 0)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
        .denextWidgetBackground()
    }
}

/// iOS 14–16: the defaults' snapshot.
struct StatusStaticProvider: TimelineProvider {
    func placeholder(in context: Context) -> StatusEntry {
        StatusSnapshot.placeholder()
    }

    func getSnapshot(in context: Context, completion: @escaping (StatusEntry) -> Void) {
        completion(StatusSnapshot.entry(StatusSnapshot.defaults))
    }

    func getTimeline(in context: Context, completion: @escaping (Timeline<StatusEntry>) -> Void) {
        completion(Timeline(entries: [StatusSnapshot.entry(StatusSnapshot.defaults)], policy: .never))
    }
}

/// The Status widget before iOS 17 (kind "Status.static"): not configurable. On iOS 17 and
/// later it lists no family, so only StatusConfigurableWidget is offered.
struct StatusWidget: Widget {
    let kind = "Status.static"

    var body: some WidgetConfiguration {
        StaticConfiguration(kind: kind, provider: StatusStaticProvider()) { entry in
            StatusWidgetView(entry: entry)
        }
        .configurationDisplayName("Status")
        .description("Status")
        .supportedFamilies(StatusWidget.families)
    }

    static var families: [WidgetFamily] {
        if #available(iOSApplicationExtension 17.0, *) { return [] }
        return [.systemSmall, .systemMedium]
    }
}

/// The mode parameter's values.
@available(iOS 17.0, *)
enum StatusModeOption: String, AppEnum {
    case `compact`
    case `detailed`

    static let typeDisplayRepresentation: TypeDisplayRepresentation = "Mode"
    static let caseDisplayRepresentations: [StatusModeOption: DisplayRepresentation] = [
        .`compact`: "Compact",
        .`detailed`: "Detailed",
    ]
}

/// What the user picks when editing the widget.
@available(iOS 17.0, *)
struct StatusConfigurationIntent: WidgetConfigurationIntent {
    static let title: LocalizedStringResource = "Status"
    static let description: IntentDescription? = IntentDescription("Choose what the Status widget shows.")

    @Parameter(title: "Mode", default: .`compact`)
    var `mode`: StatusModeOption

    /// The chosen values by parameter name: the params setWidgetData stored the snapshot under.
    var params: [String: String] {
        [
            "mode": `mode`.rawValue,
        ]
    }
}

/// iOS 17 and later: the snapshot for the values the user chose.
@available(iOS 17.0, *)
struct StatusIntentProvider: AppIntentTimelineProvider {
    func placeholder(in context: Context) -> StatusEntry {
        StatusSnapshot.placeholder()
    }

    func snapshot(for configuration: StatusConfigurationIntent, in context: Context) async -> StatusEntry {
        StatusSnapshot.entry(configuration.params)
    }

    func timeline(for configuration: StatusConfigurationIntent, in context: Context) async -> Timeline<StatusEntry> {
        Timeline(entries: [StatusSnapshot.entry(configuration.params)], policy: .never)
    }
}

/// The configurable Status widget (kind "Status", iOS 17 and later).
@available(iOS 17.0, *)
struct StatusConfigurableWidget: Widget {
    let kind = "Status"

    var body: some WidgetConfiguration {
        AppIntentConfiguration(kind: kind, intent: StatusConfigurationIntent.self, provider: StatusIntentProvider()) { entry in
            StatusWidgetView(entry: entry)
        }
        .configurationDisplayName("Status")
        .description("Status")
        .supportedFamilies([.systemSmall, .systemMedium])
    }
}
