// denext-app-extension-template: 1 sha256=f43de91a0521dfc273197ff7ead28963e3b8aa6bddb8ecbc23c0fcb96c754ee0
// Generated by denext mobile add share-extension (denext app extensions). Safe to commit;
// re-run it after upgrading denext (then ship a new binary). See https://denext.dev/docs/desktop.
// Compiled into the share extension AND the App target.

import Foundation

/// The hand-off between the share extension and the app: every share is queued as one JSON
/// object in the App Group container (DenextShare/inbox.json), its files copied next to it
/// (DenextShare/files/). The App Group is the bundle's Info.plist DenextAppGroup (the app and
/// the extension both carry it, and both need the application-groups entitlement for it).
enum DenextShareInbox {
    /// Files older than this are removed when the next share arrives.
    static let fileLifetime: TimeInterval = 7 * 24 * 60 * 60

    /// The App Group identifier from Info.plist, if set.
    static var appGroup: String? {
        guard let value = Bundle.main.object(forInfoDictionaryKey: "DenextAppGroup") as? String,
              !value.isEmpty else { return nil }
        return value
    }

    /// DenextShare/ in the App Group container, or nil when the group is not available.
    static func container() -> URL? {
        guard let group = appGroup,
              let base = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: group)
        else { return nil }
        return base.appendingPathComponent("DenextShare", isDirectory: true)
    }

    /// Where shared files are copied.
    static func filesDirectory() -> URL? {
        return container()?.appendingPathComponent("files", isDirectory: true)
    }

    private static func inboxURL() -> URL? {
        return container()?.appendingPathComponent("inbox.json")
    }

    /// Whether a share is waiting.
    static func hasPending() -> Bool {
        guard let url = inboxURL() else { return false }
        return FileManager.default.fileExists(atPath: url.path)
    }

    /// Queue one shared item (a JSON object).
    static func append(_ item: [String: Any]) throws {
        guard let directory = container(), let url = inboxURL() else {
            throw CocoaError(.fileNoSuchFile)
        }
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        try coordinate(url) { target in
            var items = read(target)
            items.append(item)
            let data = try JSONSerialization.data(withJSONObject: items)
            try data.write(to: target, options: .atomic)
        }
    }

    /// Every queued item, oldest first, removing them from the queue.
    static func take() -> [[String: Any]] {
        guard let url = inboxURL(), FileManager.default.fileExists(atPath: url.path) else {
            return []
        }
        var items: [[String: Any]] = []
        try? coordinate(url) { target in
            items = read(target)
            try? FileManager.default.removeItem(at: target)
        }
        return items
    }

    /// Remove shared files older than fileLifetime.
    static func pruneFiles() {
        guard let directory = filesDirectory(),
              let names = try? FileManager.default.contentsOfDirectory(atPath: directory.path)
        else { return }
        let cutoff = Date().addingTimeInterval(-fileLifetime)
        for name in names {
            let file = directory.appendingPathComponent(name)
            let modified = (try? file.resourceValues(forKeys: [.contentModificationDateKey]))?
                .contentModificationDate ?? Date()
            if modified < cutoff { try? FileManager.default.removeItem(at: file) }
        }
    }

    private static func read(_ url: URL) -> [[String: Any]] {
        guard let data = try? Data(contentsOf: url),
              let items = try? JSONSerialization.jsonObject(with: data) as? [[String: Any]]
        else { return [] }
        return items
    }

    /// Run body with url under a file coordinator (the app and the extension are two processes).
    private static func coordinate(_ url: URL, _ body: (URL) throws -> Void) throws {
        var coordinationError: NSError?
        var bodyError: Error?
        NSFileCoordinator().coordinate(writingItemAt: url, options: .forMerging, error: &coordinationError) { target in
            do { try body(target) } catch { bodyError = error }
        }
        if let error = coordinationError ?? bodyError { throw error }
    }
}
