// denext-app-extension-template: 1 sha256=e7faf3bf636c4f767381aba72651f8f42d29c8a76be7907522cdebd6a53e2c39
// Generated by denext mobile add share-extension (denext app extensions). Safe to commit and to
// edit (denext then keeps your version); re-run it after upgrading denext (then ship a new
// binary). See https://denext.dev/docs/desktop.

import UIKit
import UniformTypeIdentifiers

/// The Share Extension's principal class: it collects what was shared (a web URL, text, images),
/// queues it in the App Group container (DenextShareInbox) and opens the app through its URL
/// scheme (Info.plist DenextAppScheme, as <scheme>://denext-share), where onShareReceived() in
/// denext/mobile delivers it. It shows no UI of its own.
@objc(ShareViewController)
class ShareViewController: UIViewController {
    private var started = false
    private let lock = NSLock()
    private var texts: [String] = []
    private var urls: [String] = []
    private var files: [[String: String]] = []

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        guard !started else { return }
        started = true
        DenextShareInbox.pruneFiles()
        let providers = (extensionContext?.inputItems as? [NSExtensionItem] ?? [])
            .flatMap { $0.attachments ?? [] }
        let group = DispatchGroup()
        for provider in providers {
            group.enter()
            load(provider) { group.leave() }
        }
        group.notify(queue: .main) { self.finish() }
    }

    /// Load one attachment: an image (copied into the container), a URL, or text.
    private func load(_ provider: NSItemProvider, done: @escaping () -> Void) {
        if provider.hasItemConformingToTypeIdentifier(UTType.image.identifier) {
            provider.loadItem(forTypeIdentifier: UTType.image.identifier, options: nil) { value, _ in
                self.addImage(value)
                done()
            }
        } else if provider.hasItemConformingToTypeIdentifier(UTType.url.identifier) {
            provider.loadItem(forTypeIdentifier: UTType.url.identifier, options: nil) { value, _ in
                if let url = value as? URL {
                    if url.isFileURL { self.addFile(url) } else { self.add(url: url.absoluteString) }
                } else if let data = value as? Data, let url = URL(dataRepresentation: data, relativeTo: nil) {
                    self.add(url: url.absoluteString)
                }
                done()
            }
        } else if provider.hasItemConformingToTypeIdentifier(UTType.text.identifier) {
            provider.loadItem(forTypeIdentifier: UTType.text.identifier, options: nil) { value, _ in
                if let text = value as? String {
                    self.add(text: text)
                } else if let data = value as? Data, let text = String(data: data, encoding: .utf8) {
                    self.add(text: text)
                }
                done()
            }
        } else {
            done()
        }
    }

    private func add(text: String) {
        lock.lock(); texts.append(text); lock.unlock()
    }

    private func add(url: String) {
        lock.lock(); urls.append(url); lock.unlock()
    }

    private func addImage(_ value: NSSecureCoding?) {
        if let url = value as? URL, url.isFileURL {
            addFile(url)
        } else if let data = value as? Data {
            addData(data, ext: "jpg")
        } else if let image = value as? UIImage, let data = image.pngData() {
            addData(data, ext: "png")
        }
    }

    /// Copy a shared file into the container.
    private func addFile(_ source: URL) {
        let ext = source.pathExtension.isEmpty ? "bin" : source.pathExtension.lowercased()
        guard let target = newFile(ext: ext) else { return }
        do {
            try FileManager.default.copyItem(at: source, to: target)
            record(target, ext: ext)
        } catch {
            NSLog("denext share extension: could not copy %@: %@", source.lastPathComponent, error.localizedDescription)
        }
    }

    private func addData(_ data: Data, ext: String) {
        guard let target = newFile(ext: ext) else { return }
        do {
            try data.write(to: target, options: .atomic)
            record(target, ext: ext)
        } catch {
            NSLog("denext share extension: could not write a shared image: %@", error.localizedDescription)
        }
    }

    private func newFile(ext: String) -> URL? {
        guard let directory = DenextShareInbox.filesDirectory() else { return nil }
        try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        return directory.appendingPathComponent("\(UUID().uuidString).\(ext)")
    }

    private func record(_ file: URL, ext: String) {
        let mimeType = UTType(filenameExtension: ext)?.preferredMIMEType ?? "application/octet-stream"
        lock.lock(); files.append(["path": file.path, "mimeType": mimeType]); lock.unlock()
    }

    /// Queue the item, open the app, and close the sheet.
    private func finish() {
        var item: [String: Any] = ["receivedAt": Int(Date().timeIntervalSince1970 * 1000)]
        if !texts.isEmpty { item["text"] = texts.joined(separator: "\n") }
        if let url = urls.first { item["url"] = url }
        if !files.isEmpty { item["files"] = files }
        if item.count > 1 {
            do {
                try DenextShareInbox.append(item)
                openApp()
            } catch {
                NSLog("denext share extension: the App Group container is unavailable (check DenextAppGroup and the application-groups entitlement): %@", error.localizedDescription)
            }
        }
        extensionContext?.completeRequest(returningItems: nil, completionHandler: nil)
    }

    /// Open <DenextAppScheme>://denext-share. An extension cannot reach UIApplication.shared, so
    /// this walks the responder chain to the application object and calls
    /// open(_:options:completionHandler:) through the Objective-C runtime.
    private func openApp() {
        guard let scheme = Bundle.main.object(forInfoDictionaryKey: "DenextAppScheme") as? String,
              !scheme.isEmpty, let url = URL(string: "\(scheme)://denext-share") else { return }
        let selector = sel_registerName("openURL:options:completionHandler:")
        var responder: UIResponder? = self
        while let current = responder {
            if current is UIApplication, current.responds(to: selector) {
                typealias Open = @convention(c) (AnyObject, Selector, NSURL, NSDictionary, AnyObject?) -> Void
                let open = unsafeBitCast(current.method(for: selector), to: Open.self)
                open(current, selector, url as NSURL, NSDictionary(), nil)
                return
            }
            responder = current.next
        }
    }
}
