// denext-app-extension-template: 1 sha256=4958ec68a93ce699ecbffa7467e261c3f6efe9e7ff631d6c6192fe2a8e5fa99e
// Generated by denext mobile add widget (denext app extensions). Safe to commit; re-run it after upgrading denext (then ship a new binary).
// See https://denext.dev/docs/desktop.

package dev.denext.widgets;

import android.appwidget.AppWidgetManager;
import android.appwidget.AppWidgetProviderInfo;
import android.content.ComponentName;
import android.content.Context;
import android.content.Intent;
import androidx.annotation.Nullable;
import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;
import java.util.Iterator;
import java.util.Map;
import java.util.TreeMap;
import java.util.regex.Pattern;
import org.json.JSONObject;

/**
 * The native side of {@code setWidgetData()} / {@code reloadWidgets()} from {@code denext/mobile},
 * reached from the web app as {@code window.Capacitor.Plugins.DenextWidgets}. {@code MainActivity}
 * registers it.
 *
 * <ul>
 *   <li>{@code setData({ kind, json, params? })}: stores {@code json} in the
 *       {@code denext_widgets} shared preferences under {@code kind} and updates that kind's
 *       widgets. With {@code params} (the values of an iOS configurable widget) the key is
 *       {@code <kind>?<name>=<value>&…}, names sorted: Android widgets are not configurable, so
 *       they read the snapshot stored without params.
 *   <li>{@code reload({ kind? })}: updates one kind's widgets, or all of this app's.
 * </ul>
 *
 * <p>A kind's widgets are the app's AppWidgetProviders named {@code <kind>Widget} (what
 * {@code denext mobile add widget --name <kind>} writes); they read the data with
 * {@link #data(Context, String)}.
 */
@CapacitorPlugin(name = "DenextWidgets")
public class DenextWidgetsPlugin extends Plugin {

    /** The shared preferences the data is stored in. */
    public static final String PREFS = "denext_widgets";
    private static final Pattern KIND = Pattern.compile("^[A-Za-z][A-Za-z0-9_.-]{0,63}$");
    private static final Pattern PARAM = Pattern.compile("^[A-Za-z][A-Za-z0-9_]{0,63}$");

    @PluginMethod
    public void setData(PluginCall call) {
        String kind = call.getString("kind");
        String json = call.getString("json");
        if (kind == null || !KIND.matcher(kind).matches()) {
            call.reject("kind must be a widget name such as Status", "invalid");
            return;
        }
        if (json == null) {
            call.reject("json must be the text of a JSON value", "invalid");
            return;
        }
        String key = key(kind, call.getObject("params"));
        if (key == null) {
            call.reject("params must map parameter names to enum values", "invalid");
            return;
        }
        Context context = getContext();
        context.getSharedPreferences(PREFS, Context.MODE_PRIVATE).edit().putString(key, json).apply();
        reload(context, kind);
        call.resolve();
    }

    @PluginMethod
    public void reload(PluginCall call) {
        String kind = call.getString("kind");
        if (kind != null && !KIND.matcher(kind).matches()) {
            call.reject("kind must be a widget name such as Status", "invalid");
            return;
        }
        reload(getContext(), kind);
        call.resolve();
    }

    /** The preferences key for {@code kind} and {@code params}, or null for bad params. */
    @Nullable
    private static String key(String kind, @Nullable JSObject params) {
        if (params == null || params.length() == 0) return kind;
        TreeMap<String, String> sorted = new TreeMap<>();
        Iterator<String> names = params.keys();
        while (names.hasNext()) {
            String name = names.next();
            Object value = params.opt(name);
            if (!(value instanceof String) || !PARAM.matcher(name).matches()
                    || !PARAM.matcher((String) value).matches()) {
                return null;
            }
            sorted.put(name, (String) value);
        }
        StringBuilder query = new StringBuilder();
        for (Map.Entry<String, String> entry : sorted.entrySet()) {
            if (query.length() > 0) query.append('&');
            query.append(entry.getKey()).append('=').append(entry.getValue());
        }
        return kind + "?" + query;
    }

    /** Ask every placed widget of {@code kind} (null: of this app) to update. */
    public static void reload(Context context, @Nullable String kind) {
        AppWidgetManager manager = AppWidgetManager.getInstance(context);
        if (manager == null) return;
        String suffix = kind == null ? null : "." + kind + "Widget";
        for (AppWidgetProviderInfo info : manager.getInstalledProviders()) {
            ComponentName provider = info.provider;
            if (!provider.getPackageName().equals(context.getPackageName())) continue;
            if (suffix != null && !provider.getClassName().endsWith(suffix)) continue;
            int[] ids = manager.getAppWidgetIds(provider);
            if (ids == null || ids.length == 0) continue;
            Intent intent = new Intent(AppWidgetManager.ACTION_APPWIDGET_UPDATE);
            intent.setComponent(provider);
            intent.putExtra(AppWidgetManager.EXTRA_APPWIDGET_IDS, ids);
            context.sendBroadcast(intent);
        }
    }

    /** The JSON object {@code setWidgetData(kind, …)} stored, or null. */
    @Nullable
    public static JSONObject data(Context context, String kind) {
        String json = context.getSharedPreferences(PREFS, Context.MODE_PRIVATE).getString(kind, null);
        if (json == null) return null;
        try {
            return new JSONObject(json);
        } catch (Exception e) {
            return null;
        }
    }
}
