// denext-app-extension-template: 1 sha256=f8bdfd57eda17124f8ecb2789177d98c82378f6c02df1f51b593a8f11b4a91a8
// Generated by denext mobile add widget (denext app extensions). Safe to commit and to
// edit (denext then keeps your version); re-run it after upgrading denext (then ship a new binary).
// See https://denext.dev/docs/desktop.

package dev.denext.widgets;

import android.app.PendingIntent;
import android.appwidget.AppWidgetManager;
import android.appwidget.AppWidgetProvider;
import android.content.Context;
import android.content.Intent;
import android.widget.RemoteViews;
import com.brainwires.denext.mobile.R;
import org.json.JSONObject;

/**
 * The Status home-screen widget: shows what {@code setWidgetData("Status", data)} stored
 * ({@code title} and {@code body}, as a starting point). Its layout is
 * {@code res/layout/denext_widget_status.xml}, its size and preview
 * {@code res/xml/denext_widget_status_info.xml}. Edit freely.
 */
public class StatusWidget extends AppWidgetProvider {

    /** The widget kind setWidgetData / reloadWidgets name. */
    public static final String KIND = "Status";

    @Override
    public void onUpdate(Context context, AppWidgetManager manager, int[] ids) {
        JSONObject data = DenextWidgetsPlugin.data(context, KIND);
        String title = data == null ? KIND : data.optString("title", KIND);
        String body = data == null ? "Open the app to load this widget." : data.optString("body", "");
        Intent launch = context.getPackageManager().getLaunchIntentForPackage(context.getPackageName());
        PendingIntent open = launch == null ? null : PendingIntent.getActivity(
            context, 0, launch, PendingIntent.FLAG_IMMUTABLE | PendingIntent.FLAG_UPDATE_CURRENT);
        for (int id : ids) {
            RemoteViews views = new RemoteViews(context.getPackageName(), R.layout.denext_widget_status);
            views.setTextViewText(R.id.denext_widget_title, title);
            views.setTextViewText(R.id.denext_widget_body, body);
            if (open != null) views.setOnClickPendingIntent(R.id.denext_widget_root, open);
            manager.updateAppWidget(id, views);
        }
    }
}
