// denext-app-extension-template: 1 sha256=12d2fd5d2d995ce70bcd19eac88c15caa1113db9a933b461054d4f517ea3779e
// Generated by denext mobile add widget (denext app extensions). Safe to commit; re-run it after upgrading denext (then ship a new binary).
// See https://denext.dev/docs/desktop.

@preconcurrency import Capacitor
import Foundation
import WidgetKit

/// The native side of setWidgetData() / reloadWidgets() from denext/mobile, reached from the
/// web app as window.Capacitor.Plugins.DenextWidgets. DenextBridgeViewController registers it.
///
/// - setData({ kind, json, params? }): stores json (the text of a JSON value) in the App Group's
///   shared defaults under denext.widget.<kind> (with params, a configurable widget's chosen
///   values: denext.widget.<kind>?<name>=<value>&… sorted by name; the widget extension reads it
///   through DenextWidgetStore) and reloads that kind's timelines. Rejects with code invalid for
///   a bad kind or params, unavailable without the App Group (Info.plist DenextAppGroup + the
///   application-groups entitlement).
/// - reload({ kind? }): reloads one kind's timelines, or every widget's. A kind's timelines
///   include "<kind>.static", the pre-iOS 17 face of a configurable widget.
@objc(DenextWidgetsPlugin)
public class DenextWidgetsPlugin: CAPPlugin, CAPBridgedPlugin, @unchecked Sendable {
    public let identifier = "DenextWidgetsPlugin"
    public let jsName = "DenextWidgets"
    public let pluginMethods: [CAPPluginMethod] = [
        CAPPluginMethod(name: "setData", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "reload", returnType: CAPPluginReturnPromise)
    ]

    @objc func setData(_ call: CAPPluginCall) {
        guard let kind = call.getString("kind"), Self.isKind(kind) else {
            call.reject("kind must be a widget name such as Status", "invalid")
            return
        }
        guard let json = call.getString("json") else {
            call.reject("json must be the text of a JSON value", "invalid")
            return
        }
        guard let group = Bundle.main.object(forInfoDictionaryKey: "DenextAppGroup") as? String,
              !group.isEmpty, let defaults = UserDefaults(suiteName: group) else {
            call.reject("the App Group is unavailable (Info.plist DenextAppGroup and the application-groups entitlement)", "unavailable")
            return
        }
        var params: [String: String] = [:]
        for (name, value) in call.getObject("params") ?? [:] {
            guard let text = value as? String, Self.isParam(name), Self.isParam(text) else {
                call.reject("params must map parameter names to enum values", "invalid")
                return
            }
            params[name] = text
        }
        let query = params.sorted { $0.key < $1.key }.map { "\($0.key)=\($0.value)" }
            .joined(separator: "&")
        defaults.set(json, forKey: query.isEmpty ? "denext.widget.\(kind)" : "denext.widget.\(kind)?\(query)")
        Self.reloadKind(kind)
        call.resolve()
    }

    @objc func reload(_ call: CAPPluginCall) {
        if let kind = call.getString("kind") {
            guard Self.isKind(kind) else {
                call.reject("kind must be a widget name such as Status", "invalid")
                return
            }
            Self.reloadKind(kind)
        } else {
            WidgetCenter.shared.reloadAllTimelines()
        }
        call.resolve()
    }

    /// Reload kind's timelines and those of its pre-iOS 17 static face.
    private static func reloadKind(_ kind: String) {
        WidgetCenter.shared.reloadTimelines(ofKind: kind)
        WidgetCenter.shared.reloadTimelines(ofKind: "\(kind).static")
    }

    private static func isKind(_ kind: String) -> Bool {
        return kind.range(of: "^[A-Za-z][A-Za-z0-9_.-]{0,63}$", options: .regularExpression) != nil
    }

    private static func isParam(_ text: String) -> Bool {
        return text.range(of: "^[A-Za-z][A-Za-z0-9_]{0,63}$", options: .regularExpression) != nil
    }
}
