// denext-settings-template: 3 sha256=b24923b02a3c73f72c42c766bed80a1e77bc49d41dc7a4b42616152baf1177d5
// Generated by `denext mobile add permissions` (denext app settings). Safe to commit;
// re-run it after upgrading denext (then ship a new binary). See https://denext.dev/docs/mobile.

@preconcurrency import Capacitor
import Foundation
import UIKit
import UserNotifications

/// The native side of `openAppSettings()` from `denext/mobile`, reached from the web app as
/// `window.Capacitor.Plugins.DenextSettings`. `DenextBridgeViewController` registers it.
///
/// - `open()`: opens the app's own page in the Settings app
///   (`UIApplication.openSettingsURLString`), where the user can change a permission they
///   refused. Rejects with code `unavailable` when the system does not open it.
/// - `deliveredNotifications()`: the app's notifications in Notification Center, local and remote
///   alike, as `{ notifications: [{ id, threadId?, title?, data? }] }`: the request identifier,
///   the content's `threadIdentifier` (APNs `aps.thread-id`), and the payload (a local
///   notification's `extra`, else a push's keys other than `aps`).
/// - `removeDeliveredNotifications({ notifications: [{ id }] })`: removes those from Notification
///   Center (`removeDeliveredNotifications(withIdentifiers:)`). Rejects with code `invalid`
///   without the array.
@objc(DenextSettingsPlugin)
public class DenextSettingsPlugin: CAPPlugin, CAPBridgedPlugin, @unchecked Sendable {
    public let identifier = "DenextSettingsPlugin"
    public let jsName = "DenextSettings"
    public let pluginMethods: [CAPPluginMethod] = [
        CAPPluginMethod(name: "open", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "deliveredNotifications", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "removeDeliveredNotifications", returnType: CAPPluginReturnPromise)
    ]

    @objc func open(_ call: CAPPluginCall) {
        DispatchQueue.main.async {
            guard let url = URL(string: UIApplication.openSettingsURLString) else {
                call.reject("The app's settings page is unavailable.", "unavailable")
                return
            }
            UIApplication.shared.open(url, options: [:]) { opened in
                if opened {
                    call.resolve()
                } else {
                    call.reject("The system did not open the app's settings.", "unavailable")
                }
            }
        }
    }

    @objc func deliveredNotifications(_ call: CAPPluginCall) {
        UNUserNotificationCenter.current().getDeliveredNotifications { delivered in
            let list = delivered.map { DenextSettingsPlugin.deliveredObject($0.request) }
            call.resolve(["notifications": list])
        }
    }

    @objc func removeDeliveredNotifications(_ call: CAPPluginCall) {
        guard let list = call.getArray("notifications", JSObject.self) else {
            call.reject("notifications must be an array.", "invalid")
            return
        }
        let ids = list.compactMap { $0["id"] as? String }
        if !ids.isEmpty {
            UNUserNotificationCenter.current().removeDeliveredNotifications(withIdentifiers: ids)
        }
        call.resolve()
    }

    /// One delivered notification for `deliveredNotifications()`.
    static func deliveredObject(_ request: UNNotificationRequest) -> JSObject {
        let content = request.content
        var out: JSObject = ["id": request.identifier]
        if !content.threadIdentifier.isEmpty { out["threadId"] = content.threadIdentifier }
        if !content.title.isEmpty { out["title"] = content.title }
        if var info = JSTypes.coerceDictionaryToJSObject(content.userInfo) {
            if let extra = info["cap_extra"] {
                // @capacitor/local-notifications keeps the notification's `extra` there.
                out["data"] = extra
            } else {
                info.removeValue(forKey: "aps")
                if !info.isEmpty { out["data"] = info }
            }
        }
        return out
    }
}
