// denext-app-extension-template: 1 sha256=3ac34197a084b960c54851210d967dcfc223a50f8e0ae8f080040d674cc43707
// Generated by denext mobile add share-extension (denext app extensions). Safe to commit;
// re-run it after upgrading denext (then ship a new binary). See https://denext.dev/docs/desktop.

@preconcurrency import Capacitor
import Foundation
import UIKit

/// The native side of onShareReceived() from denext/mobile, reached from the web app as
/// window.Capacitor.Plugins.DenextShareReceive. DenextBridgeViewController registers it.
///
/// - consume() → { items }: every share the extension queued in the App Group container
///   (DenextShareInbox), oldest first, removed from the queue. Rejects with code unavailable when
///   the App Group container cannot be opened (Info.plist DenextAppGroup, or the
///   application-groups entitlement, is missing).
/// - event shareReceived: a share is waiting (fired when the app becomes active with one queued);
///   the web side then calls consume().
@objc(DenextShareReceivePlugin)
public class DenextShareReceivePlugin: CAPPlugin, CAPBridgedPlugin, @unchecked Sendable {
    public let identifier = "DenextShareReceivePlugin"
    public let jsName = "DenextShareReceive"
    public let pluginMethods: [CAPPluginMethod] = [
        CAPPluginMethod(name: "consume", returnType: CAPPluginReturnPromise)
    ]

    override public func load() {
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(appDidBecomeActive),
            name: UIApplication.didBecomeActiveNotification,
            object: nil
        )
    }

    deinit {
        NotificationCenter.default.removeObserver(self)
    }

    @objc private func appDidBecomeActive() {
        if DenextShareInbox.hasPending() {
            notifyListeners("shareReceived", data: [:])
        }
    }

    @objc func consume(_ call: CAPPluginCall) {
        guard DenextShareInbox.container() != nil else {
            call.reject(
                "the App Group container is unavailable (Info.plist DenextAppGroup and the application-groups entitlement)",
                "unavailable"
            )
            return
        }
        call.resolve(["items": DenextShareInbox.take()])
    }
}
