// denext-settings-template: 2 sha256=0e55c5659ee210162a2f4bbab36d43fcc456ce68263347527990cbfb5263c7e9
// Generated by `denext mobile add permissions` (denext app settings). Safe to commit;
// re-run it after upgrading denext (then ship a new binary). See https://denext.dev/docs/mobile.

@preconcurrency import Capacitor
import Foundation
import UIKit

/// The native side of `openAppSettings()` from `denext/mobile`, reached from the web app as
/// `window.Capacitor.Plugins.DenextSettings`. `DenextBridgeViewController` registers it.
///
/// - `open()`: opens the app's own page in the Settings app
///   (`UIApplication.openSettingsURLString`), where the user can change a permission they
///   refused. Rejects with code `unavailable` when the system does not open it.
@objc(DenextSettingsPlugin)
public class DenextSettingsPlugin: CAPPlugin, CAPBridgedPlugin, @unchecked Sendable {
    public let identifier = "DenextSettingsPlugin"
    public let jsName = "DenextSettings"
    public let pluginMethods: [CAPPluginMethod] = [
        CAPPluginMethod(name: "open", returnType: CAPPluginReturnPromise)
    ]

    @objc func open(_ call: CAPPluginCall) {
        DispatchQueue.main.async {
            guard let url = URL(string: UIApplication.openSettingsURLString) else {
                call.reject("The app's settings page is unavailable.", "unavailable")
                return
            }
            UIApplication.shared.open(url, options: [:]) { opened in
                if opened {
                    call.resolve()
                } else {
                    call.reject("The system did not open the app's settings.", "unavailable")
                }
            }
        }
    }
}
