// denext-app-extension-template: 1 sha256=f782c5a6a723f607f0a421135d2a4b84b58f7ce6b6a9295e91ce090c29841dde
// Generated by denext mobile add live-activity (denext app extensions). Safe to commit; re-run it after upgrading denext (then ship a new binary).
// See https://denext.dev/docs/desktop.

@preconcurrency import Capacitor
import Foundation
#if canImport(ActivityKit)
import ActivityKit
#endif

/// The native side of the Live Activity functions of denext/mobile, reached from the web app as
/// window.Capacitor.Plugins.DenextLiveActivity. DenextBridgeViewController registers it.
/// ActivityKit needs iOS 16.1: on an older iOS every method rejects with code unsupported (the
/// app keeps its own deployment target).
///
/// - start({ name, attributes, state, push }) → { id }: attributes and state are the text of
///   JSON objects. push asks for an ActivityKit push token (the app needs the push entitlement).
///   Rejects with disabled (Live Activities are off for the app), invalid or failed.
/// - update({ id, state }), end({ id, state?, dismissal?, dismissalAt? }): not_found for an
///   unknown id. dismissalAt (ms since the epoch) removes the ended activity at that time.
/// - pushToken({ id, timeoutMs }) → { token }: the hex push token, waiting for it up to
///   timeoutMs; rejects with timeout.
/// - pushToStartToken({ timeoutMs }) → { supported, token? }: the hex push-to-start token
///   (iOS 17.2+; supported is false before), waiting for it up to timeoutMs; rejects with
///   timeout. A server starts an activity remotely with it (APNs push type liveactivity).
/// - list() → { activities: [{ id, name }] }: the running activities.
///
/// Events: "pushToken" { id, token } whenever ActivityKit issues a running activity a push
/// token, and "pushToStartToken" { token } whenever it issues the app a push-to-start token
/// (iOS 17.2+). Both are kept until the first listener takes them.
@objc(DenextLiveActivityPlugin)
public class DenextLiveActivityPlugin: CAPPlugin, CAPBridgedPlugin, @unchecked Sendable {
    public let identifier = "DenextLiveActivityPlugin"
    public let jsName = "DenextLiveActivity"
    public let pluginMethods: [CAPPluginMethod] = [
        CAPPluginMethod(name: "start", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "update", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "end", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "pushToken", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "pushToStartToken", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "list", returnType: CAPPluginReturnPromise)
    ]

    /// The ids of the activities whose push tokens are observed.
    private let observedLock = NSLock()
    private var observed = Set<String>()

    override public func load() {
        if #available(iOS 16.1, *) {
            for activity in Activity<DenextActivityAttributes>.activities { observe(activity) }
            Task { [weak self] in
                for await activity in Activity<DenextActivityAttributes>.activityUpdates {
                    self?.observe(activity)
                }
            }
        }
        if #available(iOS 17.2, *) {
            Task { [weak self] in
                for await token in Activity<DenextActivityAttributes>.pushToStartTokenUpdates {
                    self?.notifyListeners("pushToStartToken", data: ["token": Self.hex(token)], retainUntilConsumed: true)
                }
            }
        }
    }

    /// Post a "pushToken" event for each push token ActivityKit issues activity (once per id).
    @available(iOS 16.1, *)
    private func observe(_ activity: Activity<DenextActivityAttributes>) {
        let id = activity.id
        observedLock.lock()
        let fresh = observed.insert(id).inserted
        observedLock.unlock()
        guard fresh else { return }
        Task { [weak self] in
            for await token in activity.pushTokenUpdates {
                self?.notifyListeners("pushToken", data: ["id": id, "token": Self.hex(token)], retainUntilConsumed: true)
            }
        }
    }

    @objc func start(_ call: CAPPluginCall) {
        guard #available(iOS 16.1, *) else { return Self.unsupported(call) }
        guard let name = call.getString("name"), !name.isEmpty,
              let attributes = Self.object(call.getString("attributes")),
              let state = Self.object(call.getString("state")) else {
            call.reject("name, attributes and state are required (attributes and state as JSON objects)", "invalid")
            return
        }
        guard ActivityAuthorizationInfo().areActivitiesEnabled else {
            call.reject("Live Activities are turned off for this app", "disabled")
            return
        }
        let push = call.getBool("push") ?? false
        let activityAttributes = DenextActivityAttributes(name: name, values: attributes)
        let contentState = DenextActivityAttributes.ContentState(values: state)
        do {
            let activity: Activity<DenextActivityAttributes>
            if #available(iOS 16.2, *) {
                activity = try Activity.request(
                    attributes: activityAttributes,
                    content: ActivityContent(state: contentState, staleDate: nil),
                    pushType: push ? .token : nil
                )
            } else {
                activity = try Activity.request(
                    attributes: activityAttributes,
                    contentState: contentState,
                    pushType: push ? .token : nil
                )
            }
            if push { observe(activity) }
            call.resolve(["id": activity.id])
        } catch {
            call.reject(error.localizedDescription, "failed")
        }
    }

    @objc func update(_ call: CAPPluginCall) {
        guard #available(iOS 16.1, *) else { return Self.unsupported(call) }
        guard let activity = Self.activity(call), let state = Self.object(call.getString("state")) else {
            return Self.missing(call)
        }
        let contentState = DenextActivityAttributes.ContentState(values: state)
        Task {
            if #available(iOS 16.2, *) {
                await activity.update(ActivityContent(state: contentState, staleDate: nil))
            } else {
                await activity.update(using: contentState)
            }
            call.resolve()
        }
    }

    @objc func end(_ call: CAPPluginCall) {
        guard #available(iOS 16.1, *) else { return Self.unsupported(call) }
        guard let activity = Self.activity(call) else { return Self.missing(call) }
        let state = Self.object(call.getString("state")).map { DenextActivityAttributes.ContentState(values: $0) }
        let policy: ActivityUIDismissalPolicy
        if let at = call.getDouble("dismissalAt") {
            policy = .after(Date(timeIntervalSince1970: at / 1000))
        } else {
            policy = call.getString("dismissal") == "immediate" ? .immediate : .default
        }
        Task {
            if #available(iOS 16.2, *) {
                let content = state.map { ActivityContent(state: $0, staleDate: nil) }
                await activity.end(content, dismissalPolicy: policy)
            } else {
                await activity.end(using: state, dismissalPolicy: policy)
            }
            call.resolve()
        }
    }

    @objc func pushToken(_ call: CAPPluginCall) {
        guard #available(iOS 16.1, *) else { return Self.unsupported(call) }
        guard let activity = Self.activity(call) else { return Self.missing(call) }
        if let token = activity.pushToken {
            call.resolve(["token": Self.hex(token)])
            return
        }
        Self.wait(
            call,
            for: activity.pushTokenUpdates,
            result: [:],
            ended: "the Live Activity ended without a push token",
            timedOut: "no push token yet (was it started with push: true?)"
        )
    }

    @objc func pushToStartToken(_ call: CAPPluginCall) {
        guard #available(iOS 17.2, *) else {
            call.resolve(["supported": false])
            return
        }
        if let token = Activity<DenextActivityAttributes>.pushToStartToken {
            call.resolve(["supported": true, "token": Self.hex(token)])
            return
        }
        Self.wait(
            call,
            for: Activity<DenextActivityAttributes>.pushToStartTokenUpdates,
            result: ["supported": true],
            ended: "ActivityKit issued no push-to-start token",
            timedOut: "no push-to-start token yet (does the app have the push entitlement?)"
        )
    }

    @objc func list(_ call: CAPPluginCall) {
        guard #available(iOS 16.1, *) else {
            call.resolve(["activities": [[String: String]]()])
            return
        }
        let running = Activity<DenextActivityAttributes>.activities.filter {
            $0.activityState != .ended && $0.activityState != .dismissed
        }
        call.resolve(["activities": running.map { ["id": $0.id, "name": $0.attributes.name] }])
    }

    /// Resolve call with result plus the first token updates yields (as hex), or reject it with
    /// code timeout once timeoutMs (default 10 000) passes or the sequence ends.
    @available(iOS 16.1, *)
    private static func wait(
        _ call: CAPPluginCall,
        for updates: Activity<DenextActivityAttributes>.PushTokenUpdates,
        result: [String: Any],
        ended: String,
        timedOut: String
    ) {
        let timeout = max(call.getDouble("timeoutMs") ?? 10_000, 0) / 1000
        let settled = Settled()
        let waiter = Task {
            for await token in updates {
                if settled.claim() { call.resolve(result.merging(["token": hex(token)]) { $1 }) }
                return
            }
            if settled.claim() { call.reject(ended, "timeout") }
        }
        DispatchQueue.main.asyncAfter(deadline: .now() + timeout) {
            if settled.claim() {
                waiter.cancel()
                call.reject(timedOut, "timeout")
            }
        }
    }

    /// A one-shot flag: the first claim wins.
    private final class Settled: @unchecked Sendable {
        private let lock = NSLock()
        private var done = false

        func claim() -> Bool {
            lock.lock()
            defer { lock.unlock() }
            if done { return false }
            done = true
            return true
        }
    }

    @available(iOS 16.1, *)
    private static func activity(_ call: CAPPluginCall) -> Activity<DenextActivityAttributes>? {
        guard let id = call.getString("id") else { return nil }
        return Activity<DenextActivityAttributes>.activities.first { $0.id == id }
    }

    private static func object(_ json: String?) -> [String: DenextJSONValue]? {
        guard let data = json?.data(using: .utf8) else { return nil }
        return try? JSONDecoder().decode([String: DenextJSONValue].self, from: data)
    }

    private static func hex(_ data: Data) -> String {
        return data.map { String(format: "%02x", $0) }.joined()
    }

    private static func unsupported(_ call: CAPPluginCall) {
        call.reject("Live Activities need iOS 16.1 or later", "unsupported")
    }

    private static func missing(_ call: CAPPluginCall) {
        call.reject("no Live Activity with that id (or a missing state)", "not_found")
    }
}
