// denext-app-extension-template: 2 sha256=2c4dce19198927c82383b78178305c766f95b4e99018634a600a775902ae754f
// Generated by denext (denext mobile add). Safe to commit; re-run it after upgrading denext
// (then ship a new binary). denext mobile add-ota replaces this file with one that also serves
// the over-the-air UI. See https://denext.dev/docs/desktop.

@preconcurrency import Capacitor
import UIKit

/// A CAPBridgeViewController that registers denext's native plugins before the first page.
///
/// Use it where the app would use CAPBridgeViewController: Main.storyboard's view controller
/// class and SceneDelegate's root view controller (the installer sets both when they still name
/// CAPBridgeViewController). An app with its own bridge subclass changes that subclass's
/// superclass to DenextBridgeViewController and calls super from any capacitorDidLoad()
/// override.
class DenextBridgeViewController: CAPBridgeViewController {
    override func capacitorDidLoad() {
        super.capacitorDidLoad()
        // denext durable storage: openKeyValueStore() in denext/mobile.
        bridge?.registerPluginInstance(DenextStoragePlugin())
    }
}
