// denext-storage-template: 1 sha256=8b9a5b408f20225454f81ca995a9f225bb45522c81a0db5fbcd34d87b09b299f
// Generated by `denext mobile add storage` (denext durable key-value storage). Safe to
// commit; re-run it after upgrading denext (then ship a new binary). See https://denext.dev/docs/mobile.

@preconcurrency import Capacitor
import Foundation
import SQLite3

/// The native side of `openKeyValueStore()` from `denext/mobile` (and React Native mode's
/// AsyncStorage and MMKV), reached from the web app as `window.Capacitor.Plugins.DenextStorage`.
/// `DenextBridgeViewController` registers it.
///
/// One SQLite file, `Library/Application Support/denext/kv.sqlite`: the app's own data, which
/// iOS does not purge the way it may purge a WKWebView's website data. Table
/// `kv (store, key, value)`; every method is one batch, run on a serial queue.
@objc(DenextStoragePlugin)
public class DenextStoragePlugin: CAPPlugin, CAPBridgedPlugin, @unchecked Sendable {
    public let identifier = "DenextStoragePlugin"
    public let jsName = "DenextStorage"
    public let pluginMethods: [CAPPluginMethod] = [
        CAPPluginMethod(name: "getMany", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "setMany", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "removeMany", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "keys", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "clear", returnType: CAPPluginReturnPromise)
    ]

    private struct StorageError: Error, CustomStringConvertible {
        let description: String
    }

    /// SQLite copies bound text (SQLITE_TRANSIENT).
    private static let transient = unsafeBitCast(-1, to: sqlite3_destructor_type.self)

    private let queue = DispatchQueue(label: "dev.denext.storage")
    private var db: OpaquePointer?

    deinit {
        if let db = db { sqlite3_close(db) }
    }

    /// The database, opened (and created) on first use. Runs on `queue`.
    private func database() throws -> OpaquePointer {
        if let db = db { return db }
        let fm = FileManager.default
        let dir = try fm.url(for: .applicationSupportDirectory, in: .userDomainMask, appropriateFor: nil, create: true)
            .appendingPathComponent("denext", isDirectory: true)
        try fm.createDirectory(at: dir, withIntermediateDirectories: true)
        var handle: OpaquePointer?
        let flags = SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE | SQLITE_OPEN_FULLMUTEX
        let path = dir.appendingPathComponent("kv.sqlite").path
        guard sqlite3_open_v2(path, &handle, flags, nil) == SQLITE_OK, let opened = handle else {
            let message = handle.map { String(cString: sqlite3_errmsg($0)) } ?? "cannot open \(path)"
            if let handle = handle { sqlite3_close(handle) }
            throw StorageError(description: message)
        }
        try exec(opened, "PRAGMA journal_mode=WAL")
        try exec(opened, "CREATE TABLE IF NOT EXISTS kv (store TEXT NOT NULL, key TEXT NOT NULL, " +
            "value TEXT NOT NULL, PRIMARY KEY (store, key)) WITHOUT ROWID")
        db = opened
        return opened
    }

    private func failure(_ db: OpaquePointer) -> StorageError {
        StorageError(description: String(cString: sqlite3_errmsg(db)))
    }

    private func exec(_ db: OpaquePointer, _ sql: String) throws {
        guard sqlite3_exec(db, sql, nil, nil, nil) == SQLITE_OK else { throw failure(db) }
    }

    private func prepare(_ db: OpaquePointer, _ sql: String) throws -> OpaquePointer {
        var stmt: OpaquePointer?
        guard sqlite3_prepare_v2(db, sql, -1, &stmt, nil) == SQLITE_OK, let prepared = stmt else {
            throw failure(db)
        }
        return prepared
    }

    private func bind(_ stmt: OpaquePointer, _ index: Int32, _ text: String) {
        sqlite3_bind_text(stmt, index, text, -1, DenextStoragePlugin.transient)
    }

    /// Run `statement` once per item of `items` inside one transaction.
    private func batch<T>(_ db: OpaquePointer, _ sql: String, _ items: [T], _ fill: (OpaquePointer, T) -> Void) throws {
        try exec(db, "BEGIN IMMEDIATE")
        do {
            let stmt = try prepare(db, sql)
            defer { sqlite3_finalize(stmt) }
            for item in items {
                fill(stmt, item)
                guard sqlite3_step(stmt) == SQLITE_DONE else { throw failure(db) }
                sqlite3_reset(stmt)
                sqlite3_clear_bindings(stmt)
            }
            try exec(db, "COMMIT")
        } catch {
            sqlite3_exec(db, "ROLLBACK", nil, nil, nil)
            throw error
        }
    }

    private func run(_ call: CAPPluginCall, _ work: @escaping @Sendable (OpaquePointer) throws -> [String: Any]) {
        queue.async {
            do {
                call.resolve(try work(try self.database()))
            } catch {
                call.reject("\(error)", "STORAGE_ERROR")
            }
        }
    }

    private func storeName(_ call: CAPPluginCall) -> String {
        call.getString("store") ?? "default"
    }

    private func strings(_ call: CAPPluginCall, _ key: String) -> [String] {
        (call.getArray(key) ?? []).compactMap { $0 as? String }
    }

    @objc func getMany(_ call: CAPPluginCall) {
        let store = storeName(call)
        let keys = strings(call, "keys")
        run(call) { db in
            let stmt = try self.prepare(db, "SELECT value FROM kv WHERE store = ?1 AND key = ?2")
            defer { sqlite3_finalize(stmt) }
            var values: [Any] = []
            for key in keys {
                self.bind(stmt, 1, store)
                self.bind(stmt, 2, key)
                if sqlite3_step(stmt) == SQLITE_ROW, let text = sqlite3_column_text(stmt, 0) {
                    values.append(String(cString: text))
                } else {
                    values.append(NSNull())
                }
                sqlite3_reset(stmt)
                sqlite3_clear_bindings(stmt)
            }
            return ["values": values]
        }
    }

    @objc func setMany(_ call: CAPPluginCall) {
        let store = storeName(call)
        let entries: [(String, String)] = (call.getArray("entries") ?? []).compactMap { entry in
            guard let pair = entry as? [Any], pair.count == 2,
                  let key = pair[0] as? String, let value = pair[1] as? String else { return nil }
            return (key, value)
        }
        run(call) { db in
            try self.batch(db, "INSERT OR REPLACE INTO kv (store, key, value) VALUES (?1, ?2, ?3)", entries) { stmt, entry in
                self.bind(stmt, 1, store)
                self.bind(stmt, 2, entry.0)
                self.bind(stmt, 3, entry.1)
            }
            return [:]
        }
    }

    @objc func removeMany(_ call: CAPPluginCall) {
        let store = storeName(call)
        let keys = strings(call, "keys")
        run(call) { db in
            try self.batch(db, "DELETE FROM kv WHERE store = ?1 AND key = ?2", keys) { stmt, key in
                self.bind(stmt, 1, store)
                self.bind(stmt, 2, key)
            }
            return [:]
        }
    }

    @objc func keys(_ call: CAPPluginCall) {
        let store = storeName(call)
        run(call) { db in
            let stmt = try self.prepare(db, "SELECT key FROM kv WHERE store = ?1 ORDER BY key")
            defer { sqlite3_finalize(stmt) }
            self.bind(stmt, 1, store)
            var keys: [String] = []
            while sqlite3_step(stmt) == SQLITE_ROW {
                if let text = sqlite3_column_text(stmt, 0) { keys.append(String(cString: text)) }
            }
            return ["keys": keys]
        }
    }

    @objc func clear(_ call: CAPPluginCall) {
        let store = storeName(call)
        run(call) { db in
            try self.batch(db, "DELETE FROM kv WHERE store = ?1", [store]) { stmt, name in
                self.bind(stmt, 1, name)
            }
            return [:]
        }
    }
}
