// denext-app-extension-template: 2 sha256=31156671526ac7eff9a8a587ad61c6fd887e7089fe26a6dd460c36308d5e2907
// Generated by denext (denext mobile add). Safe to commit; re-run it after upgrading denext
// (then ship a new binary). denext mobile add-ota replaces this file with one that also serves
// the over-the-air UI. See https://denext.dev/docs/desktop.

@preconcurrency import Capacitor
import UIKit
import WebKit

/// A CAPBridgeViewController that registers denext's native plugins before the first page.
///
/// Use it where the app would use CAPBridgeViewController: Main.storyboard's view controller
/// class and SceneDelegate's root view controller (the installer sets both when they still name
/// CAPBridgeViewController). An app with its own bridge subclass changes that subclass's
/// superclass to DenextBridgeViewController and calls super from any capacitorDidLoad()
/// override.
class DenextBridgeViewController: CAPBridgeViewController {
    override func capacitorDidLoad() {
        super.capacitorDidLoad()
        // denext: native plugin calls are accepted from the app's main frame only.
        DenextMainFrameBridgeGuard.install(on: bridge)
        // denext durable storage: openKeyValueStore() in denext/mobile.
        bridge?.registerPluginInstance(DenextStoragePlugin())
    }
}

/// Drops native bridge calls that do not come from the app's main frame.
///
/// WebKit delivers the bridge script message from every frame of the page, and Capacitor's
/// handler does not check which frame sent it, so an iframe (an embedded site, an ad, a widget)
/// could call any installed plugin. Capacitor injects its JS bridge into the main frame only,
/// so a message from another frame is never the app's own. This handler takes Capacitor's place
/// under the same name and forwards main-frame messages to it unchanged.
@MainActor
final class DenextMainFrameBridgeGuard: NSObject, WKScriptMessageHandler {
    /// The name Capacitor registers its handler under (WebViewDelegationHandler.handlerName).
    private static let handlerName = "bridge"
    /// Capacitor's own handler, which the bridge owns.
    private weak var target: WKScriptMessageHandler?
    /// The frame origins already logged, so a looping frame cannot flood the log.
    private var logged = Set<String>()

    private init(target: WKScriptMessageHandler) {
        self.target = target
    }

    /// Puts the guard in front of Capacitor's bridge handler. Call it from capacitorDidLoad(),
    /// which runs before the first page loads.
    static func install(on bridge: CAPBridgeProtocol?) {
        guard let bridge = bridge as? CapacitorBridge else {
            NSLog("[denext] could not guard the native bridge: the bridge is not a CapacitorBridge")
            return
        }
        let handler = bridge.webViewDelegationHandler
        let controller = handler.contentController
        controller.removeScriptMessageHandler(forName: handlerName)
        controller.add(DenextMainFrameBridgeGuard(target: handler), name: handlerName)
    }

    func userContentController(
        _ userContentController: WKUserContentController,
        didReceive message: WKScriptMessage
    ) {
        guard message.frameInfo.isMainFrame else {
            let origin = message.frameInfo.securityOrigin
            let from = origin.host.isEmpty ? origin.protocol : "\(origin.protocol)://\(origin.host)"
            if logged.count < 16, logged.insert(from).inserted {
                NSLog("[denext] refused a native plugin call from a non-main frame (%@)", from)
            }
            return
        }
        target?.userContentController(userContentController, didReceive: message)
    }
}
