#!/usr/bin/env -S deno run --allow-read --allow-write
// Bump the denext version across every "current version" spot in one shot.
//
// A version bump touches several files. This replaces the OLD version (read from the
// root deno.json "version" field, the source of truth) with a NEW one in the
// CURRENT-version spots ONLY — it never rewrites CHANGELOG release headers or README
// minimum-version prose, which are historical and must stay put.
//
//   deno task bump 2.0.0-rc.4          # apply
//   deno task bump 2.0.0-rc.4 --dry    # preview only, write nothing
//
// Spots updated (each: replace every occurrence of the old version, digit/dot-bounded
// so an embedded number is never partially rewritten):
//   - deno.json              root "version"
//   - mod.ts                 export const VERSION
//   - packages/*/deno.json   the @denext/denext peer-dependency pins (all subpaths)
//   - ROADMAP.md             the "development is <version>" status line
//
// Intentionally NOT touched (printed as a reminder): CHANGELOG.md files (add a release
// section by hand), packages/*/README.md (minimum-version prose), and deno.lock
// (regenerated by Deno on the next build/cache). For a full release, also regenerate
// the API reference (`deno task docs:api`) and roll the CHANGELOG's [Unreleased]
// section — this tool deliberately stays limited to the version-string pins.

import { walk } from "@std/fs";
import { dirname, fromFileUrl, join } from "@std/path";

const ROOT = dirname(dirname(fromFileUrl(import.meta.url)));

/** A semver core with an optional prerelease/build tail (e.g. 2.0.0-rc.4, 1.4.0). */
const SEMVER_RE = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/;

/** Escape a string for literal use inside a RegExp. */
function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** A semver core with an optional prerelease/build tail. Reused by the release wrapper. */
export const VERSION_RE = SEMVER_RE;

/** The repo root (two levels up from this script). Reused by the release wrapper. */
export const REPO_ROOT = ROOT;

/** Read the current version from the root deno.json "version" field. */
export async function readCurrentVersion(): Promise<string> {
  const text = await Deno.readTextFile(join(ROOT, "deno.json"));
  const version = (JSON.parse(text) as { version?: string }).version;
  if (!version) throw new Error('root deno.json has no "version" field');
  return version;
}

/** The fixed set of files whose CURRENT-version references should be bumped. */
async function targetFiles(): Promise<string[]> {
  const files = [
    join(ROOT, "deno.json"),
    join(ROOT, "mod.ts"),
    join(ROOT, "ROADMAP.md"),
  ];
  // Every packages/*/deno.json (the workspace members' peer pins).
  for await (
    const entry of walk(join(ROOT, "packages"), {
      includeDirs: false,
      match: [/packages\/[^/]+\/deno\.json$/],
      maxDepth: 2,
    })
  ) {
    files.push(entry.path);
  }
  return files;
}

/** The outcome of a bump: which files changed and by how much. */
export interface BumpResult {
  oldVersion: string;
  newVersion: string;
  /** Files that had at least one replacement (repo-relative path + hit count). */
  changed: { file: string; hits: number }[];
  /** Target files with no occurrence of the old version (repo-relative). */
  zeroHits: string[];
  /** Total occurrences replaced. */
  total: number;
}

/**
 * Replace every current-version reference (`oldVersion` from root deno.json) with
 * `newVersion` across the fixed target-file list. Writes files unless `opts.dry`.
 * Throws if the current version already equals `newVersion`.
 */
export async function bumpVersion(
  newVersion: string,
  opts: { dry?: boolean } = {},
): Promise<BumpResult> {
  const oldVersion = await readCurrentVersion();
  if (oldVersion === newVersion) {
    throw new Error(`current version is already ${newVersion} — nothing to do`);
  }
  // Match the old version only when it is not part of a longer number (so bumping
  // "2.0.0-rc.3" never mangles a hypothetical "2.0.0-rc.30", and a core like "0.1.0"
  // is not matched inside "10.1.0").
  const re = new RegExp(`(?<![\\d.])${escapeRe(oldVersion)}(?![\\d.])`, "g");
  const changed: { file: string; hits: number }[] = [];
  const zeroHits: string[] = [];
  let total = 0;

  for (const file of await targetFiles()) {
    let text: string;
    try {
      text = await Deno.readTextFile(file);
    } catch {
      continue; // a listed file may not exist in every checkout
    }
    const hits = text.match(re)?.length ?? 0;
    const rel = file.slice(ROOT.length + 1);
    if (hits === 0) {
      zeroHits.push(rel);
      continue;
    }
    total += hits;
    changed.push({ file: rel, hits });
    if (!opts.dry) await Deno.writeTextFile(file, text.replace(re, newVersion));
  }
  return { oldVersion, newVersion, changed, zeroHits, total };
}

async function main(): Promise<void> {
  const args = Deno.args.filter((a) => a !== "--dry");
  const dry = Deno.args.includes("--dry");
  const newVersion = args[0];

  if (!newVersion) {
    console.error("usage: deno task bump <new-version> [--dry]");
    Deno.exit(2);
  }
  if (!SEMVER_RE.test(newVersion)) {
    console.error(`error: "${newVersion}" is not a valid semver (e.g. 2.0.0-rc.4)`);
    Deno.exit(2);
  }

  let result: BumpResult;
  try {
    result = await bumpVersion(newVersion, { dry });
  } catch (err) {
    console.error(`error: ${err instanceof Error ? err.message : err}`);
    Deno.exit(1);
  }

  console.log(`Bumping ${result.oldVersion} → ${newVersion}${dry ? "  (dry run)" : ""}\n`);
  for (const { file, hits } of result.changed) {
    console.log(`  ${file.padEnd(34)} ${hits} replacement${hits === 1 ? "" : "s"}`);
  }
  console.log(`\n${dry ? "Would change" : "Changed"} ${result.total} occurrence(s).`);
  if (result.zeroHits.length) {
    console.log(
      `\nNote: no match in ${result.zeroHits.join(", ")} — expected if that file carries ` +
        `no current-version reference (or the spot moved; check by hand).`,
    );
  }
  console.log(
    "\nReminders (not handled by this tool):\n" +
      "  • deno.lock — regenerate with a build/`deno cache` if you rely on it\n" +
      "  • CHANGELOG.md — add the release section by hand\n" +
      "  • deno task docs:api — regenerate the API reference before a release tag\n" +
      "  (or run `deno task release <version>` to do all of the above + tag)",
  );
}

if (import.meta.main) await main();
