// Regenerate `src/compat/next/font/font-metrics.ts` — the vertical metrics + average glyph
// width of every Google Fonts family (and the two local fallback faces, Arial and Times New
// Roman), which `next/font`'s `adjustFontFallback` needs to emit a metric-matched fallback
// `@font-face` (`size-adjust` / `ascent-override` / `descent-override` / `line-gap-override`).
//
// The data is Capsize's font-metrics set (seek-oss/capsize, MIT), in the compiled form Next
// ships as `next/dist/server/capsize-font-metrics.json`, so denext computes the SAME overrides
// Next does for the same family. A guessed table would mis-size the fallback; this one is real.
//
//   deno task gen:font-metrics -- --from <path/to/capsize-font-metrics.json>   # a local Next
//   deno task gen:font-metrics                                                 # fetch from the npm CDN
//
// The output is sorted and deterministic; commit it.

import { fromFileUrl } from "@std/path";

const OUT = fromFileUrl(new URL("../src/compat/next/font/font-metrics.ts", import.meta.url));
const CDN = "https://cdn.jsdelivr.net/npm/next@16/dist/server/capsize-font-metrics.json";

/** One family's entry in Capsize's set (the fields the override math reads). */
interface CapsizeEntry {
  familyName: string;
  category: string;
  ascent: number;
  descent: number;
  lineGap: number;
  unitsPerEm: number;
  xWidthAvg: number;
}

/** The compact tuple the generated table stores per family. */
export type MetricsTuple = [
  family: string,
  category: string,
  unitsPerEm: number,
  ascent: number,
  descent: number,
  lineGap: number,
  xWidthAvg: number,
];

async function loadCapsize(path: string | null): Promise<Record<string, CapsizeEntry>> {
  if (path) return JSON.parse(await Deno.readTextFile(path));
  const res = await fetch(CDN);
  if (!res.ok) throw new Error(`${CDN}: HTTP ${res.status}`);
  return await res.json();
}

/** Whether a Capsize entry carries the fields the override math reads. */
function usable(e: CapsizeEntry | undefined): e is CapsizeEntry {
  return typeof e?.familyName === "string" && e.unitsPerEm > 0;
}

/** Tuples for every family with the fields the math needs, sorted by family name. */
export function toTuples(data: Record<string, CapsizeEntry>): MetricsTuple[] {
  return Object.values(data)
    .filter(usable)
    .map((e): MetricsTuple => [
      e.familyName,
      e.category,
      e.unitsPerEm,
      e.ascent,
      e.descent,
      e.lineGap,
      e.xWidthAvg,
    ])
    .sort((a, b) => a[0].localeCompare(b[0], "en"));
}

function render(rows: MetricsTuple[]): string {
  const body = rows.map((r) => `  ${JSON.stringify(r)},`).join("\n");
  return `// GENERATED by scripts/gen-font-metrics.ts — do not edit by hand.
// Capsize font metrics (seek-oss/capsize, MIT; the set Next ships as
// next/dist/server/capsize-font-metrics.json) for ${rows.length} families, incl. the local
// fallback faces Arial and Times New Roman. Tuple: [family, category, unitsPerEm, ascent,
// descent, lineGap, xWidthAvg]. Read by src/compat/next/font/fallback.ts.

/** \`[family, category, unitsPerEm, ascent, descent, lineGap, xWidthAvg]\` per family. */
export const FONT_METRICS: readonly (readonly [
  string,
  string,
  number,
  number,
  number,
  number,
  number,
])[] = [
${body}
];
`;
}

if (import.meta.main) {
  const fromIdx = Deno.args.indexOf("--from");
  const data = await loadCapsize(fromIdx >= 0 ? Deno.args[fromIdx + 1] : null);
  const rows = toTuples(data);
  await Deno.writeTextFile(OUT, render(rows));
  console.log(`wrote ${OUT} (${rows.length} families)`);
}
