// The package-manager manifests for a denext release, generated from its SHA256SUMS by the
// `release` job of .github/workflows/publish.yml and attached to the GitHub release:
//
//   denext.rb                              a Homebrew formula (macOS + Linux, arm64 + x86_64)
//   denext.json                            a Scoop manifest (Windows x64), with checkver/autoupdate
//   Brainwires.denext.yaml                 the winget manifest set (Windows x64, a portable zip:
//   Brainwires.denext.installer.yaml         winget unpacks it and puts `denext` on PATH)
//   Brainwires.denext.locale.en-US.yaml
//
// Nothing here publishes them. Getting them to users is an outward step the maintainer takes per
// stable release (see CONTRIBUTING.md → "Package managers"): commit `denext.rb` to a Homebrew tap
// repo, `denext.json` to a Scoop bucket, and the winget set as a PR to microsoft/winget-pkgs
// (manifests/b/Brainwires/denext/<version>/).
//
//   deno run -A scripts/gen-package-manifests.ts --version v3.0.2 --sums dist/SHA256SUMS --out dist

import { join } from "@std/path";

/** The repository the release assets live in. */
export const REPO = "Brainwires/denext";

/** The release's archives, by the platform each manifest names. */
export const MANIFEST_TARGETS = {
  macArm: "aarch64-apple-darwin",
  macIntel: "x86_64-apple-darwin",
  linuxArm: "aarch64-unknown-linux-gnu",
  linuxIntel: "x86_64-unknown-linux-gnu",
  windows: "x86_64-pc-windows-msvc",
} as const;

const DESCRIPTION =
  "The denext CLI: Next.js's App Router for Deno, for the web, the desktop and mobile";
const HOMEPAGE = "https://denext.dev";

/** The archive name of a target (`.zip` on Windows, `.tar.gz` elsewhere). */
export function archiveName(target: string): string {
  return `denext-${target}.${target.includes("windows") ? "zip" : "tar.gz"}`;
}

/** `sha256sum`-format lines → archive name → hex digest. */
export function parseSums(text: string): Map<string, string> {
  const out = new Map<string, string>();
  for (const line of text.split("\n")) {
    const m = /^([0-9a-fA-F]{64})\s+\*?(\S+)$/.exec(line.trim());
    if (m) out.set(m[2], m[1].toLowerCase());
  }
  return out;
}

/** What every manifest is generated from. */
export interface ReleaseInfo {
  /** The tag (`v3.0.2`). */
  readonly tag: string;
  /** archive name → SHA-256 hex. */
  readonly sums: ReadonlyMap<string, string>;
}

/** The download URL of a release archive. */
function url(r: ReleaseInfo, target: string): string {
  return `https://github.com/${REPO}/releases/download/${r.tag}/${archiveName(target)}`;
}

/** The digest of a target's archive; throws when SHA256SUMS does not list it. */
function sha(r: ReleaseInfo, target: string): string {
  const digest = r.sums.get(archiveName(target));
  if (!digest) throw new Error(`SHA256SUMS lists no ${archiveName(target)}`);
  return digest;
}

/** The version without the tag's `v`. */
function bare(tag: string): string {
  return tag.replace(/^v/, "");
}

/** The Homebrew formula (`denext.rb`). */
export function homebrewFormula(r: ReleaseInfo): string {
  const t = MANIFEST_TARGETS;
  const block = (target: string) =>
    `      url "${url(r, target)}"\n      sha256 "${sha(r, target)}"`;
  return `# Generated by scripts/gen-package-manifests.ts for denext ${r.tag}. Do not edit by hand.
class Denext < Formula
  desc "${DESCRIPTION}"
  homepage "${HOMEPAGE}"
  version "${bare(r.tag)}"
  license "MIT"

  on_macos do
    on_arm do
${block(t.macArm)}
    end
    on_intel do
${block(t.macIntel)}
    end
  end

  on_linux do
    on_arm do
${block(t.linuxArm)}
    end
    on_intel do
${block(t.linuxIntel)}
    end
  end

  def install
    bin.install "denext"
  end

  def caveats
    <<~EOS
      denext runs every verb that loads a project (dev, build, start, ...) in a \`deno\` child:
        brew install deno
    EOS
  end

  test do
    assert_match "denext #{version} (binary)", shell_output("#{bin}/denext --version")
  end
end
`;
}

/** The Scoop manifest (`denext.json`). */
export function scoopManifest(r: ReleaseInfo): string {
  const w = MANIFEST_TARGETS.windows;
  const manifest = {
    version: bare(r.tag),
    description: DESCRIPTION,
    homepage: HOMEPAGE,
    license: "MIT",
    architecture: { "64bit": { url: url(r, w), hash: sha(r, w) } },
    bin: "denext.exe",
    suggest: { deno: "deno" },
    checkver: { github: `https://github.com/${REPO}` },
    autoupdate: {
      architecture: {
        "64bit": {
          url: `https://github.com/${REPO}/releases/download/v$version/${archiveName(w)}`,
        },
      },
      hash: { url: "$baseurl/SHA256SUMS" },
    },
  };
  return JSON.stringify(manifest, null, 2) + "\n";
}

const WINGET_ID = "Brainwires.denext";
const WINGET_SCHEMA = "1.6.0";

/** The winget manifest set: file name → YAML. */
export function wingetManifests(r: ReleaseInfo): Record<string, string> {
  const w = MANIFEST_TARGETS.windows;
  const head = `# Generated by scripts/gen-package-manifests.ts for denext ${r.tag}.\n` +
    `PackageIdentifier: ${WINGET_ID}\nPackageVersion: "${bare(r.tag)}"\n`;
  const tail = (type: string) => `ManifestType: ${type}\nManifestVersion: ${WINGET_SCHEMA}\n`;
  return {
    [`${WINGET_ID}.yaml`]: head + "DefaultLocale: en-US\n" + tail("version"),
    [`${WINGET_ID}.installer.yaml`]: head +
      "InstallerType: zip\n" +
      "NestedInstallerType: portable\n" +
      "NestedInstallerFiles:\n" +
      "  - RelativeFilePath: denext.exe\n" +
      "    PortableCommandAlias: denext\n" +
      "Installers:\n" +
      "  - Architecture: x64\n" +
      `    InstallerUrl: ${url(r, w)}\n` +
      `    InstallerSha256: "${sha(r, w).toUpperCase()}"\n` +
      tail("installer"),
    [`${WINGET_ID}.locale.en-US.yaml`]: head +
      "PackageLocale: en-US\n" +
      "Publisher: Brainwires\n" +
      "PackageName: denext\n" +
      `PackageUrl: ${HOMEPAGE}\n` +
      "License: MIT\n" +
      `LicenseUrl: https://github.com/${REPO}/blob/main/LICENSE\n` +
      `ShortDescription: ${JSON.stringify(DESCRIPTION)}\n` +
      `ReleaseNotesUrl: https://github.com/${REPO}/releases/tag/${r.tag}\n` +
      tail("defaultLocale"),
  };
}

/** Every manifest file: name → contents. */
export function packageManifests(r: ReleaseInfo): Record<string, string> {
  return {
    "denext.rb": homebrewFormula(r),
    "denext.json": scoopManifest(r),
    ...wingetManifests(r),
  };
}

/** `--name value` from argv. */
function arg(argv: readonly string[], name: string): string {
  const i = argv.indexOf(`--${name}`);
  const v = i === -1 ? undefined : argv[i + 1];
  if (!v) throw new Error(`gen-package-manifests: --${name} is required`);
  return v;
}

if (import.meta.main) {
  const tag = arg(Deno.args, "version");
  const sums = parseSums(await Deno.readTextFile(arg(Deno.args, "sums")));
  const out = arg(Deno.args, "out");
  await Deno.mkdir(out, { recursive: true });
  for (const [name, text] of Object.entries(packageManifests({ tag, sums }))) {
    await Deno.writeTextFile(join(out, name), text);
    console.log(`wrote ${join(out, name)}`);
  }
}
