// Generate the config key list + JSON Schema from the `DenextConfig` TypeScript type.
//
// The TS type IS the schema (`defineConfig` type-checks against it), but the runtime
// needs a plain list of its keys (the validator's unknown-key warning, the loader's field
// copy) and editors/tools want a JSON Schema. Both used to be hand-maintained copies of
// the interface; this script derives them from one `deno doc --json` pass over
// src/server/config.ts so they cannot drift:
//
//   src/server/config-keys.generated.ts  — import-free runtime module: the top-level
//                                          `DenextConfig` keys + the `experimental.*` keys
//   denext.config.schema.json            — JSON Schema (draft 2020-12), build-time
//                                          artifact for editors/tools; never bundled
//
//   deno task gen:config-schema   # regenerate both (also runs inside `deno task docs:api`)
//
// tests/config-schema.test.ts re-runs `generate()` and fails when either file is stale.
// Zero-npm: only `deno doc` and `deno fmt` (so the output is fmt-stable) are used.
//
// The type → schema mapping itself lives in scripts/lib/ts-to-schema.ts (shared with the
// plugin catalog's options schemas). What is specific to the config schema:
//   `additionalProperties: false` is set exactly where the runtime WARNS on unknown keys
//   (the root and `experimental`); nested objects are left open, as the loader passes
//   them through untouched. `@default` / `@minimum` / `@maximum` tags are added to a
//   config field only where config-validate.ts enforces that exact bound, and
//   `@widget textarea` marks a multi-line string (`spa.head`, `spa.loading`).

import { denoDocJson } from "./deno-doc.ts";
import {
  description,
  interfaceSchema,
  propertyNames,
  type Schema,
  type SchemaContext,
  type SymbolTable,
  symbolTable,
} from "./lib/ts-to-schema.ts";

/** The repo root (this script lives in `scripts/`). */
const ROOT = new URL("../", import.meta.url).pathname;
/** The module whose `DenextConfig` / `ExperimentalConfig` interfaces are the source. */
export const CONFIG_SOURCE = `${ROOT}src/server/config.ts`;
/** Sibling modules whose exported interfaces `DenextConfig` fields reference. */
const CONFIG_TYPE_SOURCES = [
  new URL("../src/server/i18n.ts", import.meta.url).pathname,
  new URL("../src/server/segment-config.ts", import.meta.url).pathname,
  new URL("../src/server/cache.ts", import.meta.url).pathname,
  new URL("../src/plugin/mod.ts", import.meta.url).pathname,
  // `commands[].flags` / `commands[].positionals` (`FlagSpec` / `PositionalSpec`).
  new URL("../src/cli/command.ts", import.meta.url).pathname,
];
/** Output: the import-free runtime key list. */
export const KEYS_OUT = `${ROOT}src/server/config-keys.generated.ts`;
/** Output: the JSON Schema. */
export const SCHEMA_OUT = `${ROOT}denext.config.schema.json`;

/** The JSON Schema document for `DenextConfig` (unformatted JSON text). */
export function renderSchema(table: SymbolTable): string {
  const ctx: SchemaContext = { table, stack: [] };
  const root = interfaceSchema("DenextConfig", ctx);
  const properties = root.properties as Record<string, Schema>;
  // Closed exactly where the runtime validator warns on unknown keys (config-validate.ts).
  const experimental = properties.experimental;
  if (experimental?.properties) experimental.additionalProperties = false;
  const schema: Schema = {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "denext.config",
    description: `${description(table.get("DenextConfig")?.jsDoc?.doc)} ` +
      "Generated from the `DenextConfig` TypeScript type by scripts/gen-config-schema.ts; " +
      "unknown top-level and `experimental.*` keys are rejected here because denext warns " +
      "on them at runtime and ignores them.",
    type: "object",
    properties,
    ...(root.required ? { required: root.required } : {}),
    additionalProperties: false,
  };
  return JSON.stringify(schema, null, 2) + "\n";
}

/** The import-free TS module exporting the key lists (unformatted source text). */
export function renderKeysModule(configKeys: string[], experimentalKeys: string[]): string {
  const list = (keys: string[]) => keys.map((k) => `  ${JSON.stringify(k)},`).join("\n");
  return `// @generated by scripts/gen-config-schema.ts — do not edit.
//
// Derived from the \`DenextConfig\` and \`ExperimentalConfig\` interfaces in ./config.ts via
// \`deno doc --json\`. Regenerate with \`deno task gen:config-schema\` (also part of
// \`deno task docs:api\`); tests/config-schema.test.ts fails when this file is stale.
// Import-free on purpose: it is the runtime validator's and config loader's key list.

/**
 * Every top-level \`DenextConfig\` property name, in declaration order (a readonly tuple,
 * assignable to \`readonly string[]\`). The config loader copies exactly these fields and
 * the validator warns on any other, so a field exists at runtime only if it is listed here —
 * which is why the list is generated from the type rather than maintained by hand.
 */
export const CONFIG_KEYS = [
${list(configKeys)}
] as const;

/**
 * Every \`ExperimentalConfig\` property name — the recognized \`experimental.*\` sub-keys —
 * in declaration order. The validator warns on any other \`experimental.*\` key.
 */
export const EXPERIMENTAL_KEYS = [
${list(experimentalKeys)}
] as const;
`;
}

/** Format generated text with the repo's `deno fmt` settings, so the output is fmt-stable. */
export async function formatWith(text: string, ext: "ts" | "json"): Promise<string> {
  const cmd = new Deno.Command(Deno.execPath(), {
    args: ["fmt", "--config", `${ROOT}deno.json`, "--ext", ext, "-"],
    cwd: ROOT,
    stdin: "piped",
    stdout: "piped",
    stderr: "piped",
  }).spawn();
  const writer = cmd.stdin.getWriter();
  await writer.write(new TextEncoder().encode(text));
  await writer.close();
  const { code, stdout, stderr } = await cmd.output();
  if (code !== 0) throw new Error(`deno fmt failed: ${new TextDecoder().decode(stderr)}`);
  return new TextDecoder().decode(stdout);
}

/** Both artifacts, as the exact text the committed files should contain. */
export async function generate(): Promise<{ keysModule: string; schema: string }> {
  // `DenextConfig` references interfaces declared in sibling modules (`I18nConfig`,
  // `CspSetting`, …); doc those too so the schema expands them instead of leaving `{}`.
  const table = symbolTable(await denoDocJson(CONFIG_SOURCE));
  for (const extra of CONFIG_TYPE_SOURCES) {
    for (const [name, decl] of symbolTable(await denoDocJson(extra))) {
      if (!table.has(name)) table.set(name, decl);
    }
  }
  const keys = renderKeysModule(
    propertyNames(table, "DenextConfig"),
    propertyNames(table, "ExperimentalConfig"),
  );
  const [keysModule, schema] = await Promise.all([
    formatWith(keys, "ts"),
    formatWith(renderSchema(table), "json"),
  ]);
  return { keysModule, schema };
}

if (import.meta.main) {
  const { keysModule, schema } = await generate();
  await Deno.writeTextFile(KEYS_OUT, keysModule);
  await Deno.writeTextFile(SCHEMA_OUT, schema);
  console.log(`wrote ${KEYS_OUT}\nwrote ${SCHEMA_OUT}`);
}
