// Regenerate `src/compat/next/font/google-families.ts` — every Google Fonts family name, the
// list the compat bundler turns into `next/font/google` named exports (Next exports one loader
// per family; denext's hand-written `denext/next/font/google` keeps a curated subset, so a
// migrated app importing `Noto_Sans_Hebrew` needs this full list at bundle time).
//
//   deno task gen:google-fonts                    # fetch the live Google Fonts catalogue
//   deno task gen:google-fonts -- --from <path>   # read Next's compiled font-data.json instead
//
// The output is sorted and deterministic; commit it.

import { fromFileUrl } from "@std/path";

const OUT = fromFileUrl(new URL("../src/compat/next/font/google-families.ts", import.meta.url));
const METADATA = "https://fonts.google.com/metadata/fonts";

/** Family names from Next's `font-data.json` (an object keyed by family). */
async function familiesFromFile(path: string): Promise<string[]> {
  const data = JSON.parse(await Deno.readTextFile(path)) as Record<string, unknown>;
  return Object.keys(data);
}

/** Family names from Google's catalogue endpoint (a `)]}'`-prefixed JSON document). */
async function familiesFromGoogle(): Promise<string[]> {
  const res = await fetch(METADATA);
  if (!res.ok) throw new Error(`${METADATA}: HTTP ${res.status}`);
  const text = (await res.text()).replace(/^\)\]\}'\s*/, "");
  const data = JSON.parse(text) as { familyMetadataList: Array<{ family: string }> };
  return data.familyMetadataList.map((f) => f.family);
}

/** Next's export-name rule: spaces become `_`; anything that isn't an identifier is dropped. */
export function fontExportName(family: string): string | null {
  const name = family.replace(/ /g, "_");
  return /^[A-Za-z_$][\w$]*$/.test(name) ? name : null;
}

function render(families: string[]): string {
  const sorted = [...new Set(families)].filter((f) => fontExportName(f)).sort();
  const body = sorted.map((f) => `  ${JSON.stringify(f)},`).join("\n");
  return `// GENERATED by scripts/gen-google-fonts.ts — do not edit by hand.
// Every Google Fonts family (${sorted.length}); the compat bundler exposes each as a
// \`next/font/google\` named export (\`Family Name\` → \`Family_Name\`).

export const GOOGLE_FONT_FAMILIES: readonly string[] = [
${body}
];
`;
}

if (import.meta.main) {
  const fromIdx = Deno.args.indexOf("--from");
  const families = fromIdx >= 0
    ? await familiesFromFile(Deno.args[fromIdx + 1])
    : await familiesFromGoogle();
  await Deno.writeTextFile(OUT, render(families));
  console.log(`wrote ${OUT} (${families.length} families)`);
}
