// The "Expo APIs" table of /docs/react-native, generated from src/expo/manifest.ts (EXPO_SHIMS)
// so the docs and the shims cannot drift: tests/expo-shims-docs.test.ts fails when the page's
// table differs. The twin of scripts/gen-rn-community-docs.ts (the "Community packages" table).
//
//   deno run -A scripts/gen-expo-shim-docs.ts          # rewrite the table in place
//   deno run -A scripts/gen-expo-shim-docs.ts --check  # exit 1 when it is stale

import { EXPO_SHIMS } from "../src/expo/manifest.ts";
import {
  markdownTable,
  refreshGeneratedTable,
  tableCells,
  type TableMarkers,
  tableReader,
} from "./lib/generated-table.ts";

export { tableCells };

/** The page the table lives in, repo-relative. */
export const DOCS_PAGE = "apps/web/app/docs/react-native/content.md";

/** The markers around the generated table. */
export const START = "<!-- expo-shims:start (generated by scripts/gen-expo-shim-docs.ts) -->";
/** The end marker. */
export const END = "<!-- expo-shims:end -->";

/** The page and markers, for the shared table helpers. */
export const TABLE: TableMarkers = { page: DOCS_PAGE, start: START, end: END };

/** The page's current table (between the markers), or null when the markers are missing. */
export const currentTable: (page: string) => string | null = tableReader(TABLE);

/**
 * One piece of prose outside code spans: HTML-like tags and tokens Markdown would read as
 * emphasis (`*Sync`, `__DENEXT_EXPO_CONFIG__`) become code; trailing punctuation stays prose.
 */
function prose(text: string): string {
  return text
    .replace(/<[^<>`]+>/g, (tag) => `\`${tag}\``)
    .replace(/(^|\s)([^\s`]*(?:\*|__)[^\s`]*?)([.,;:)]*)(?=\s|$)/g, "$1`$2`$3");
}

/** A table cell's text: code spans kept, prose made safe, pipes escaped, on one line. */
function cell(text: string): string {
  return text.split(/(`[^`]*`)/).map((part, i) => i % 2 ? part : prose(part)).join("")
    .replace(/\|/g, "\\|").replace(/\s+/g, " ").trim();
}

/** The generated table (Markdown), one row per manifest key, in the manifest's order. */
export function expoShimsTable(): string {
  const rows = Object.entries(EXPO_SHIMS).map(([pkg, shim]) => {
    const omitted = shim.omitted?.length
      ? ` Not provided: ${shim.omitted.map((name) => `\`${name}\``).join(", ")}.`
      : "";
    return `| \`${pkg}\` | ${shim.pinned} | ${shim.status} | ${cell(shim.notes ?? "")}${omitted} |`;
  });
  return markdownTable(["Package", "Matched", "Status", "Notes"], rows);
}

if (import.meta.main) await refreshGeneratedTable(TABLE, expoShimsTable());
