// The "Community packages" table of /docs/react-native, generated from
// src/react-native-compat/manifest.ts (COMMUNITY_ALIASES) so the docs and the aliases cannot
// drift: tests/react-native-aliases-docs.test.ts fails when the page's table differs.
//
//   deno run -A scripts/gen-rn-community-docs.ts          # rewrite the table in place
//   deno run -A scripts/gen-rn-community-docs.ts --check  # exit 1 when it is stale

import { COMMUNITY_ALIASES } from "../src/react-native-compat/manifest.ts";

/** The page the table lives in, repo-relative. */
export const DOCS_PAGE = "apps/web/app/docs/react-native/content.md";

/** The markers around the generated table. */
export const START =
  "<!-- community-packages:start (generated by scripts/gen-rn-community-docs.ts) -->";
/** The end marker. */
export const END = "<!-- community-packages:end -->";

/** A table cell's text: HTML-like tags as code, pipes escaped, on one line. */
function cell(text: string): string {
  return text.replace(/<[^<>`]+>/g, (tag) => `\`${tag}\``).replace(/\|/g, "\\|")
    .replace(/\s+/g, " ").trim();
}

/** The generated table (Markdown), one row per aliased package, by name. */
export function communityPackagesTable(): string {
  const rows = Object.entries(COMMUNITY_ALIASES)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([pkg, alias]) => {
      const omitted = alias.omitted?.length
        ? ` Not provided: ${alias.omitted.map((name) => `\`${name}\``).join(", ")}.`
        : "";
      const caps = alias.capabilities?.length
        ? ` Capacitor: \`denext mobile add ${alias.capabilities.join(" ")}\`.`
        : "";
      return `| \`${pkg}\` | ${cell(alias.implementation)} | ${alias.status} | ${
        cell(`${alias.notes ?? ""}${omitted}${caps}`)
      } |`;
    });
  return [
    "| Package | denext implementation | Status | Notes |",
    "| --- | --- | --- | --- |",
    ...rows,
  ].join("\n");
}

/** A Markdown table reduced to its cells, so `deno fmt`'s column padding does not matter. */
export function tableCells(markdown: string): string[][] {
  return markdown.split("\n")
    .map((line) => line.trim())
    .filter((line) => line.startsWith("|") && !/^\|[\s|:-]+\|$/.test(line))
    .map((line) => line.slice(1, -1).split(/(?<!\\)\|/).map((c) => c.trim().replace(/\s+/g, " ")));
}

/** The page's current table (between the markers), or null when the markers are missing. */
export function currentTable(page: string): string | null {
  const start = page.indexOf(START);
  const end = page.indexOf(END);
  if (start < 0 || end < start) return null;
  return page.slice(start + START.length, end).trim();
}

if (import.meta.main) {
  const path = new URL(`../${DOCS_PAGE}`, import.meta.url);
  const page = await Deno.readTextFile(path);
  const current = currentTable(page);
  if (current === null) {
    console.error(`${DOCS_PAGE}: the ${START} / ${END} markers are missing`);
    Deno.exit(1);
  }
  const table = communityPackagesTable();
  const fresh = JSON.stringify(tableCells(current)) === JSON.stringify(tableCells(table));
  if (Deno.args.includes("--check")) {
    if (!fresh) {
      console.error(`${DOCS_PAGE}: the community packages table is stale — run this script`);
      Deno.exit(1);
    }
  } else if (!fresh) {
    const start = page.indexOf(START) + START.length;
    const end = page.indexOf(END);
    await Deno.writeTextFile(path, `${page.slice(0, start)}\n\n${table}\n\n${page.slice(end)}`);
    console.log(`wrote ${DOCS_PAGE}`);
  }
}
