// The "Community packages" table of /docs/react-native, generated from
// src/react-native-compat/manifest.ts (COMMUNITY_ALIASES) so the docs and the aliases cannot
// drift: tests/react-native-aliases-manifest.test.ts fails when the page's table differs.
//
//   deno run -A scripts/gen-rn-community-docs.ts          # rewrite the table in place
//   deno run -A scripts/gen-rn-community-docs.ts --check  # exit 1 when it is stale

import { COMMUNITY_ALIASES } from "../src/react-native-compat/manifest.ts";
import {
  markdownTable,
  refreshGeneratedTable,
  tableCells,
  type TableMarkers,
  tableReader,
} from "./lib/generated-table.ts";

export { tableCells };

/** The page the table lives in, repo-relative. */
export const DOCS_PAGE = "apps/web/app/docs/react-native/content.md";

/** The markers around the generated table. */
export const START =
  "<!-- community-packages:start (generated by scripts/gen-rn-community-docs.ts) -->";
/** The end marker. */
export const END = "<!-- community-packages:end -->";

/** The page and markers, for the shared table helpers. */
export const TABLE: TableMarkers = { page: DOCS_PAGE, start: START, end: END };

/** The page's current table (between the markers), or null when the markers are missing. */
export const currentTable: (page: string) => string | null = tableReader(TABLE);

/** A table cell's text: HTML-like tags as code, pipes escaped, on one line. */
function cell(text: string): string {
  return text.replace(/<[^<>`]+>/g, (tag) => `\`${tag}\``).replace(/\|/g, "\\|")
    .replace(/\s+/g, " ").trim();
}

/** The generated table (Markdown), one row per aliased package, by name. */
export function communityPackagesTable(): string {
  const rows = Object.entries(COMMUNITY_ALIASES)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([pkg, alias]) => {
      const omitted = alias.omitted?.length
        ? ` Not provided: ${alias.omitted.map((name) => `\`${name}\``).join(", ")}.`
        : "";
      const caps = alias.capabilities?.length
        ? ` Capacitor: \`denext mobile add ${alias.capabilities.join(" ")}\`.`
        : "";
      return `| \`${pkg}\` | ${cell(alias.implementation)} | ${alias.status} | ${
        cell(`${alias.notes ?? ""}${omitted}${caps}`)
      } |`;
    });
  return markdownTable(["Package", "denext implementation", "Status", "Notes"], rows);
}

if (import.meta.main) await refreshGeneratedTable(TABLE, communityPackagesTable());
