// Generated by `denext openapi types` from "Pets API" 1.0.0.
// Do not edit — regenerate. Types only; no imports.
//
// `paths`/`components` is the openapi-typescript shape (openapi-fetch and friends).
// `ApiSchema` is denext's shape — a typed client from any TypeScript project:
//   import { createApiClient } from "jsr:@denext/denext";
//   const api = createApiClient<ApiSchema>({ base: "https://api.example.com" });
//
// Wire format: plain JSON, except a value holding a Date, Map, Set, BigInt, URL, undefined,
// NaN, ±Infinity or -0, which arrives `$`-tagged ({"$":"D","v":"…"}) with the response header
// `x-denext-wire: 1`. `createApiClient` decodes those; a plain fetch must do so itself.

export interface paths {
  "/api/login": {
    post: {
      parameters: Record<never, never>;
      requestBody: {
        content: {
          "application/json": {
            username: string;
            password: string;
          };
        };
      };
      responses: {
        "200": {
          content: {
            "application/json": {
              token: string;
            };
          };
        };
        "400": {
          content: {
            "application/json": (components["schemas"]["ApiError"] & {
              error?: {
                code?: "validation" | "bad_request";
              };
            });
          };
        };
        "401": {
          content: {
            "application/json": (components["schemas"]["ApiError"] & {
              error?: {
                code?: "invalid_credentials";
              };
            });
          };
        };
        default: {
          content: {
            "application/json": components["schemas"]["ApiError"];
          };
        };
      };
    };
  };
  "/api/pets": {
    get: {
      parameters: {
        query?: {
          species?: "cat" | "dog" | "bird";
        };
      };
      responses: {
        "200": {
          content: {
            "application/json": {
              id: string;
              name: string;
              species: "cat" | "dog" | "bird";
              adopted: boolean;
            }[];
          };
        };
        "400": {
          content: {
            "application/json": (components["schemas"]["ApiError"] & {
              error?: {
                code?: "validation";
              };
            });
          };
        };
        default: {
          content: {
            "application/json": components["schemas"]["ApiError"];
          };
        };
      };
    };
    post: {
      parameters: Record<never, never>;
      requestBody: {
        content: {
          "application/json": {
            name: string;
            species: "cat" | "dog" | "bird";
          };
        };
      };
      responses: {
        "200": {
          content: {
            "application/json": {
              id: string;
              name: string;
              species: "cat" | "dog" | "bird";
              adopted: boolean;
            };
          };
        };
        "400": {
          content: {
            "application/json": (components["schemas"]["ApiError"] & {
              error?: {
                code?: "validation" | "bad_request";
              };
            });
          };
        };
        "409": {
          content: {
            "application/json": (components["schemas"]["ApiError"] & {
              error?: {
                code?: "duplicate";
              };
            });
          };
        };
        default: {
          content: {
            "application/json": components["schemas"]["ApiError"];
          };
        };
      };
    };
  };
  "/api/pets/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        "200": {
          content: {
            "application/json": {
              id: string;
              name: string;
              species: "cat" | "dog" | "bird";
              adopted: boolean;
            };
          };
        };
        "400": {
          content: {
            "application/json": (components["schemas"]["ApiError"] & {
              error?: {
                code?: "validation";
              };
            });
          };
        };
        "404": {
          content: {
            "application/json": (components["schemas"]["ApiError"] & {
              error?: {
                code?: "not_found";
              };
            });
          };
        };
        default: {
          content: {
            "application/json": components["schemas"]["ApiError"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        "200": { content?: never };
        "400": {
          content: {
            "application/json": (components["schemas"]["ApiError"] & {
              error?: {
                code?: "validation";
              };
            });
          };
        };
        "404": {
          content: {
            "application/json": (components["schemas"]["ApiError"] & {
              error?: {
                code?: "not_found";
              };
            });
          };
        };
        default: {
          content: {
            "application/json": components["schemas"]["ApiError"];
          };
        };
      };
    };
    patch: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            adopted: boolean;
          };
        };
      };
      responses: {
        "200": {
          content: {
            "application/json": {
              id: string;
              name: string;
              species: "cat" | "dog" | "bird";
              adopted: boolean;
            };
          };
        };
        "400": {
          content: {
            "application/json": (components["schemas"]["ApiError"] & {
              error?: {
                code?: "validation" | "bad_request";
              };
            });
          };
        };
        "404": {
          content: {
            "application/json": (components["schemas"]["ApiError"] & {
              error?: {
                code?: "not_found";
              };
            });
          };
        };
        default: {
          content: {
            "application/json": components["schemas"]["ApiError"];
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    ApiError: {
      error: {
        code: string;
        status: number;
        message: string;
        data?: unknown;
        fieldErrors?: Record<string, string>;
        digest?: string;
      };
    };
  };
}

export type ApiSchema = {
  "/api/login": {
    POST: {
      body: {
        username: string;
        password: string;
      };
      response: {
        token: string;
      };
      errors: "validation" | "bad_request" | "invalid_credentials";
    };
  };
  "/api/pets": {
    GET: {
      query: {
        species?: "cat" | "dog" | "bird";
      };
      response: {
        id: string;
        name: string;
        species: "cat" | "dog" | "bird";
        adopted: boolean;
      }[];
      errors: "validation";
    };
    POST: {
      body: {
        name: string;
        species: "cat" | "dog" | "bird";
      };
      response: {
        id: string;
        name: string;
        species: "cat" | "dog" | "bird";
        adopted: boolean;
      };
      errors: "validation" | "bad_request" | "duplicate";
    };
  };
  "/api/pets/[id]": {
    GET: {
      params: {
        id: string;
      };
      response: {
        id: string;
        name: string;
        species: "cat" | "dog" | "bird";
        adopted: boolean;
      };
      errors: "validation" | "not_found";
    };
    DELETE: {
      params: {
        id: string;
      };
      errors: "validation" | "not_found";
    };
    PATCH: {
      params: {
        id: string;
      };
      body: {
        adopted: boolean;
      };
      response: {
        id: string;
        name: string;
        species: "cat" | "dog" | "bird";
        adopted: boolean;
      };
      errors: "validation" | "bad_request" | "not_found";
    };
  };
};

