// generated by `denext migrate` — safe to edit; re-running may overwrite
import type { CapacitorConfig } from "@capacitor/cli";

const config: CapacitorConfig = {
  // The template's bundle identifier is unset (Expo's `ios.bundleIdentifier`): set here.
  appId: "com.brainwires.denext.expoapp",
  appName: "denext Expo",
  // denext's static export (`deno task export`) writes here; Capacitor bundles it.
  webDir: "out",
};

export default config;
