// generated by `denext migrate` — safe to edit; re-running may overwrite
import type { DenextConfig } from "denext/server";

export default {
  mode: "spa",
  compatibilityMode: true,
  reactNative: true,
  spa: {
    entry: "./index.web.ts",
    title: "HelloWorld",
    head:
      '<script>globalThis.__DENEXT_EXPO_CONFIG__={"name":"HelloWorld","slug":"expo-template-default","version":"1.0.0","scheme":"helloworld","orientation":"portrait","userInterfaceStyle":"automatic"}</script>',
    // The Capacitor shell loads files as they are: no .gz siblings.
    precompress: false,
  },
} satisfies DenextConfig;
