// generated by `denext migrate` — safe to edit; re-running may overwrite
// index.web.ts — expo-router's web entry (expo-router/entry-classic) without
// @expo/metro-runtime, Metro's own runtime. denext generates the route context from app/.
import { App } from "expo-router/build/qualified-entry";
import { renderRootComponent } from "expo-router/build/renderRootComponent";

renderRootComponent(App);
