// denext-native-views-template: 1 sha256=ad8a3abe11ca05ed916d2be37a6a6d184ee82057631fea4a6c0960165f908fdb
// Generated by denext mobile add native-views (denext native views). Safe to commit; re-run it
// after upgrading denext (then ship a new binary). See https://denext.dev/docs/mobile.

package dev.denext.nativeviews;

import androidx.annotation.Nullable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/** The registry of native view types. */
public final class DenextNativeViews {
    private static final Map<String, DenextNativeViewFactory> FACTORIES = new HashMap<>();

    private DenextNativeViews() {}

    /** Make {@code type} available to NativeViewSlot (replacing a factory registered for it before). */
    public static synchronized void register(String type, DenextNativeViewFactory factory) {
        FACTORIES.put(type, factory);
    }

    /** The factory for {@code type}, or null. */
    @Nullable
    public static synchronized DenextNativeViewFactory get(String type) {
        return FACTORIES.get(type);
    }

    /** Every registered type, sorted. */
    public static synchronized List<String> types() {
        List<String> types = new ArrayList<>(FACTORIES.keySet());
        Collections.sort(types);
        return types;
    }
}
