// denext-native-views-template: 3 sha256=702851d198b9c4d97e1ddbbda84385551c110c3cf264acbfb4a1915aa0ed82b5
// Generated by denext mobile add native-map (denext native views). Safe to commit; re-run it
// after upgrading denext (then ship a new binary). See https://denext.dev/docs/mobile.

package dev.denext.nativeviews;

import android.annotation.SuppressLint;
import android.view.View;
import com.getcapacitor.JSObject;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.WeakHashMap;
import org.json.JSONArray;
import org.json.JSONObject;
import org.osmdroid.config.Configuration;
import org.osmdroid.events.DelayedMapListener;
import org.osmdroid.events.MapListener;
import org.osmdroid.events.ScrollEvent;
import org.osmdroid.events.ZoomEvent;
import org.osmdroid.tileprovider.tilesource.TileSourceFactory;
import org.osmdroid.util.GeoPoint;
import org.osmdroid.views.CustomZoomButtonsController;
import org.osmdroid.views.MapView;
import org.osmdroid.views.overlay.Marker;
import org.osmdroid.views.overlay.Overlay;

/**
 * The "map" native view on Android: an osmdroid MapView over OpenStreetMap tiles (no API key).
 * OpenStreetMap's tile servers are for light use; point a production app at its own tile
 * source (see https://operations.osmfoundation.org/policies/tiles/).
 *
 * <p>Props: latitude, longitude, zoom (0-20; default 12), markers [{ latitude, longitude,
 * title }], interactive (default true). The center moves only when latitude, longitude or zoom
 * change. Events: regionChange { latitude, longitude, zoom }, markerPress { index, title }.
 * Commands: setRegion { latitude, longitude, zoom, animated }. DenextNativeViewsPlugin finds this
 * class by name and registers it as "map".
 */
public class DenextOsmMapFactory implements DenextNativeViewFactory {

    private final Map<MapView, DenextNativeViewContext> contexts = new WeakHashMap<>();

    @Override
    public View create(DenextNativeViewContext context, JSObject props) {
        Configuration.getInstance().setUserAgentValue(context.getActivity().getPackageName());
        MapView map = new MapView(context.getActivity());
        map.setTileSource(TileSourceFactory.MAPNIK);
        map.setMultiTouchControls(true);
        map.getZoomController().setVisibility(CustomZoomButtonsController.Visibility.NEVER);
        map.setTag(new double[] { Double.NaN, Double.NaN, Double.NaN });
        map.addMapListener(new DelayedMapListener(new MapListener() {
            @Override
            public boolean onScroll(ScrollEvent event) {
                emitRegion(context, map);
                return false;
            }

            @Override
            public boolean onZoom(ZoomEvent event) {
                emitRegion(context, map);
                return false;
            }
        }, 150));
        contexts.put(map, context);
        apply(map, props);
        map.onResume();
        return map;
    }

    private static void emitRegion(DenextNativeViewContext context, MapView map) {
        JSObject region = new JSObject();
        region.put("latitude", map.getMapCenter().getLatitude());
        region.put("longitude", map.getMapCenter().getLongitude());
        region.put("zoom", map.getZoomLevelDouble());
        context.emit("regionChange", region);
    }

    @Override
    public void update(View view, JSObject props) {
        if (view instanceof MapView) apply((MapView) view, props);
    }

    @SuppressLint("ClickableViewAccessibility")
    private void apply(MapView map, JSONObject props) {
        double lat = props.optDouble("latitude", Double.NaN);
        double lon = props.optDouble("longitude", Double.NaN);
        double zoom = props.optDouble("zoom", 12);
        double[] last = (double[]) map.getTag();
        if (!Double.isNaN(lat) && !Double.isNaN(lon) && (last[0] != lat || last[1] != lon || last[2] != zoom)) {
            map.setTag(new double[] { lat, lon, zoom });
            map.getController().setZoom(zoom);
            map.getController().setCenter(new GeoPoint(lat, lon));
        }
        boolean interactive = props.optBoolean("interactive", true);
        map.setOnTouchListener(interactive ? null : (v, e) -> true);
        List<Overlay> old = new ArrayList<>();
        for (Overlay overlay : map.getOverlays()) {
            if (overlay instanceof Marker) old.add(overlay);
        }
        map.getOverlays().removeAll(old);
        JSONArray markers = props.optJSONArray("markers");
        for (int i = 0; markers != null && i < markers.length(); i++) {
            JSONObject m = markers.optJSONObject(i);
            if (m == null || !m.has("latitude") || !m.has("longitude")) continue;
            Marker marker = new Marker(map);
            marker.setPosition(new GeoPoint(m.optDouble("latitude"), m.optDouble("longitude")));
            marker.setTitle(m.optString("title", ""));
            marker.setAnchor(Marker.ANCHOR_CENTER, Marker.ANCHOR_BOTTOM);
            final int index = i;
            marker.setOnMarkerClickListener((clicked, mapView) -> {
                DenextNativeViewContext context = contextOf(mapView);
                if (context != null) {
                    JSObject press = new JSObject();
                    press.put("index", index);
                    press.put("title", clicked.getTitle());
                    context.emit("markerPress", press);
                }
                return true;
            });
            map.getOverlays().add(marker);
        }
        map.invalidate();
    }

    private DenextNativeViewContext contextOf(MapView map) {
        return contexts.get(map);
    }

    @Override
    public JSObject command(View view, String name, JSObject args) {
        if (!(view instanceof MapView) || !"setRegion".equals(name)) return null;
        MapView map = (MapView) view;
        double lat = args.optDouble("latitude", Double.NaN);
        double lon = args.optDouble("longitude", Double.NaN);
        if (Double.isNaN(lat) || Double.isNaN(lon)) return new JSObject();
        map.getController().setZoom(args.optDouble("zoom", map.getZoomLevelDouble()));
        GeoPoint center = new GeoPoint(lat, lon);
        if (args.optBoolean("animated", true)) map.getController().animateTo(center);
        else map.getController().setCenter(center);
        return new JSObject();
    }

    @Override
    public void lifecycle(View view, boolean resumed) {
        if (!(view instanceof MapView)) return;
        if (resumed) ((MapView) view).onResume();
        else ((MapView) view).onPause();
    }

    @Override
    public void destroy(View view) {
        if (!(view instanceof MapView)) return;
        contexts.remove(view);
        ((MapView) view).onDetach();
    }
}
