// denext-native-views-template: 3 sha256=9eeace69fafc1ea0fe96bf90070f1431431b8cb630457fc4d1b37d272d13a014
// Generated by denext mobile add native-views (denext native views). Safe to commit; re-run it
// after upgrading denext (then ship a new binary). See https://denext.dev/docs/mobile.

package dev.denext.nativeviews;

import android.view.View;
import com.getcapacitor.JSObject;

/**
 * A native view type the page places with NativeViewSlot. Every method runs on the main thread.
 * Register one with {@code DenextNativeViews.register("chart", new ChartViewFactory())} before
 * the page makes a view (MainActivity.onCreate), or list its class name under
 * {@code plugins.DenextNativeViews.factories} in capacitor.config (it needs a public no-argument
 * constructor).
 */
public interface DenextNativeViewFactory {
    /** Make the view for {@code props} (the slot's props). */
    View create(DenextNativeViewContext context, JSObject props);

    /** Apply new props to a view this factory made. */
    void update(View view, JSObject props);

    /** Run a command from the page (the slot's {@code command(name, args)}); the result resolves it. */
    default JSObject command(View view, String name, JSObject args) {
        return null;
    }

    /** The activity paused ({@code resumed} false) or resumed: pause or resume what the view runs. */
    default void lifecycle(View view, boolean resumed) {}

    /** The view is leaving the page: stop what it runs. */
    default void destroy(View view) {}
}
