// denext-native-views-template: 1 sha256=a1d0322c24254b2a3968ea71d69b551e514298ecbbe1a139b0b1d981f63a8c89
// Generated by denext mobile add native-views (denext native views). Safe to commit; re-run it
// after upgrading denext (then ship a new binary). See https://denext.dev/docs/mobile.

package dev.denext.nativeviews;

import android.media.MediaPlayer;
import android.net.Uri;
import android.view.Gravity;
import android.view.View;
import android.widget.FrameLayout;
import android.widget.MediaController;
import android.widget.VideoView;
import com.getcapacitor.JSObject;
import java.util.Map;
import java.util.WeakHashMap;

/**
 * The built-in "video" native view: a VideoView (with a MediaController while {@code controls}).
 *
 * <p>Props: src (an absolute http(s), file or content URL), autoplay, loop, muted, controls
 * (default true). Events: ready { duration }, play, pause, ended, error { message }. Commands:
 * play, pause, seek { seconds }, status → { currentTime, duration, playing }.
 */
public class DenextVideoViewFactory implements DenextNativeViewFactory {

    /** One video view. Main-thread only. */
    private static final class Player {
        final DenextNativeViewContext context;
        final VideoView video;
        MediaController controller;
        MediaPlayer media;
        String src;
        boolean loop;
        boolean muted;
        boolean autoplay;

        Player(DenextNativeViewContext context, VideoView video) {
            this.context = context;
            this.video = video;
        }

        void sound() {
            if (media == null) return;
            float volume = muted ? 0f : 1f;
            media.setVolume(volume, volume);
            media.setLooping(loop);
        }
    }

    private final Map<View, Player> players = new WeakHashMap<>();

    @Override
    public View create(DenextNativeViewContext context, JSObject props) {
        FrameLayout box = new FrameLayout(context.getActivity());
        box.setBackgroundColor(0xFF000000);
        VideoView video = new VideoView(context.getActivity());
        box.addView(video, new FrameLayout.LayoutParams(FrameLayout.LayoutParams.MATCH_PARENT, FrameLayout.LayoutParams.MATCH_PARENT, Gravity.CENTER));
        Player player = new Player(context, video);
        video.setOnPreparedListener((mp) -> {
            player.media = mp;
            player.sound();
            JSObject ready = new JSObject();
            ready.put("duration", video.getDuration() / 1000.0);
            context.emit("ready", ready);
            if (player.autoplay) play(player);
        });
        video.setOnCompletionListener((mp) -> context.emit("ended", null));
        video.setOnErrorListener((mp, what, extra) -> {
            JSObject error = new JSObject();
            error.put("message", "the video could not be played (" + what + ", " + extra + ")");
            context.emit("error", error);
            return true;
        });
        players.put(box, player);
        update(box, props);
        return box;
    }

    @Override
    public void update(View view, JSObject props) {
        Player player = players.get(view);
        if (player == null) return;
        player.loop = props.optBoolean("loop", false);
        player.muted = props.optBoolean("muted", false);
        player.autoplay = props.optBoolean("autoplay", false);
        player.sound();
        if (props.optBoolean("controls", true)) {
            if (player.controller == null) {
                player.controller = new MediaController(player.context.getActivity());
                player.controller.setAnchorView(view);
            }
            player.video.setMediaController(player.controller);
        } else {
            player.video.setMediaController(null);
        }
        String src = props.optString("src", "");
        if (!src.isEmpty() && !src.equals(player.src)) {
            player.src = src;
            player.media = null;
            player.video.setVideoURI(Uri.parse(src));
        }
    }

    private static void play(Player player) {
        player.video.start();
        player.context.emit("play", null);
    }

    @Override
    public JSObject command(View view, String name, JSObject args) {
        Player player = players.get(view);
        if (player == null) return null;
        switch (name) {
            case "play":
                play(player);
                break;
            case "pause":
                player.video.pause();
                player.context.emit("pause", null);
                break;
            case "seek":
                player.video.seekTo((int) Math.round(args.optDouble("seconds", 0) * 1000));
                break;
            default:
                break;
        }
        JSObject status = new JSObject();
        status.put("currentTime", player.video.getCurrentPosition() / 1000.0);
        status.put("duration", Math.max(0, player.video.getDuration()) / 1000.0);
        status.put("playing", player.video.isPlaying());
        return status;
    }

    @Override
    public void lifecycle(View view, boolean resumed) {
        Player player = players.get(view);
        if (player != null && !resumed && player.video.isPlaying()) player.video.pause();
    }

    @Override
    public void destroy(View view) {
        Player player = players.remove(view);
        if (player == null) return;
        if (player.controller != null) player.controller.hide();
        player.video.stopPlayback();
    }
}
