// denext-native-views-template: 1 sha256=8e449120145111a0c18c0819fbc0ee5c6524dbe4950ea8129255af0582744316
// Generated by denext mobile add native-views (denext native views). Safe to commit; re-run it
// after upgrading denext (then ship a new binary). See https://denext.dev/docs/mobile.

package dev.denext.nativeviews;

import android.annotation.SuppressLint;
import android.app.Activity;
import android.graphics.Color;
import android.graphics.RectF;
import android.os.Handler;
import android.os.Looper;
import android.view.MotionEvent;
import android.view.View;
import android.view.ViewGroup;
import android.webkit.WebView;
import android.widget.FrameLayout;
import androidx.annotation.Nullable;
import com.getcapacitor.JSArray;
import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 * The native side of NativeViewSlot / useNativeViewSlot from denext/mobile, reached from the
 * web app as {@code window.Capacitor.Plugins.DenextNativeViews}. MainActivity registers it.
 *
 * <ul>
 *   <li>{@code types() → { types }}: the registered view types.
 *   <li>{@code create({ id, type, props, placement }) → { placement }}: makes the view. Android
 *       draws it {@code "under"} the WebView (made transparent) or {@code "over"} it; {@code
 *       "embed"} (iOS only) becomes {@code "over"}.
 *   <li>{@code update({ frames, dpr })}: moves, clips and hides the views (visual viewport CSS
 *       px, times {@code dpr}).
 *   <li>{@code setProps}, {@code command}, {@code destroy}; event {@code nativeViewEvent}.
 * </ul>
 *
 * <p>Touches: a layer above the WebView holds the "over" views and takes a touch only when it
 * lands on one's visible, uncovered part (else the WebView gets it). A touch listener on the
 * WebView hands a gesture that starts over an "under" view's visible part to that view.
 */
@CapacitorPlugin(name = "DenextNativeViews")
public class DenextNativeViewsPlugin extends Plugin {

    /** A view on the page. Main-thread only. */
    private static final class Slot {
        final String id;
        final String placement;
        final DenextNativeViewFactory factory;
        final View view;
        final FrameLayout host;
        boolean visible = false;
        boolean interactive = true;
        final List<RectF> passthrough = new ArrayList<>();
        /** The last frame from the page, re-applied when the document scrolls. */
        @Nullable
        JSONObject frame;

        Slot(String id, String placement, DenextNativeViewFactory factory, View view, FrameLayout host) {
            this.id = id;
            this.placement = placement;
            this.factory = factory;
            this.view = view;
            this.host = host;
        }

        /** Whether a touch at (x, y) in the layer's coordinates belongs to this view. */
        boolean takes(float x, float y) {
            if (!visible || !interactive) return false;
            float lx = x - host.getX();
            float ly = y - host.getY();
            if (lx < 0 || ly < 0 || lx >= host.getWidth() || ly >= host.getHeight()) return false;
            for (RectF r : passthrough) {
                if (r.contains(lx, ly)) return false;
            }
            return true;
        }
    }

    /** The layer above the WebView: it takes a gesture only when it starts on an "over" view. */
    private final class Router extends FrameLayout {
        private boolean routing = false;

        Router(Activity activity) {
            super(activity);
        }

        @Override
        public boolean dispatchTouchEvent(MotionEvent event) {
            int action = event.getActionMasked();
            if (action == MotionEvent.ACTION_DOWN) routing = hit(event.getX(), event.getY(), "over") != null;
            if (!routing) return false;
            super.dispatchTouchEvent(event);
            if (action == MotionEvent.ACTION_UP || action == MotionEvent.ACTION_CANCEL) routing = false;
            return true;
        }
    }

    /** Factories denext may install, found by class name when present (native-map). */
    private static final String[][] BUILT_IN = { { "map", "dev.denext.nativeviews.DenextOsmMapFactory" } };

    private final Handler main = new Handler(Looper.getMainLooper());
    /** Main-thread only. Creation order: the last one is on top. */
    private final LinkedHashMap<String, Slot> slots = new LinkedHashMap<>();
    @Nullable
    private FrameLayout underLayer;
    @Nullable
    private Router router;
    /** Main-thread only. The page's device pixel ratio, from its last update. */
    private float dpr = 1f;
    /** Main-thread only. The "under" view the current WebView gesture goes to. */
    @Nullable
    private Slot touchTarget;

    @Override
    public void load() {
        if (DenextNativeViews.get("video") == null) DenextNativeViews.register("video", new DenextVideoViewFactory());
        for (String[] builtIn : BUILT_IN) registerByName(builtIn[0], builtIn[1]);
        JSONObject configured = getConfig().getObject("factories");
        if (configured == null) return;
        Iterator<String> types = configured.keys();
        while (types.hasNext()) {
            String type = types.next();
            String name = configured.optString(type, "");
            if (!name.isEmpty()) registerByName(type, name);
        }
    }

    /** Register {@code type} from a factory class name, when the class is in the app. */
    private static void registerByName(String type, String name) {
        if (DenextNativeViews.get(type) != null) return;
        try {
            Object factory = Class.forName(name).getDeclaredConstructor().newInstance();
            if (factory instanceof DenextNativeViewFactory) DenextNativeViews.register(type, (DenextNativeViewFactory) factory);
        } catch (ReflectiveOperationException | RuntimeException ignored) {
            // Not installed (native-map not added) or not constructible: the type stays unknown.
        }
    }

    @PluginMethod
    public void types(PluginCall call) {
        JSObject result = new JSObject();
        result.put("types", new JSArray(DenextNativeViews.types()));
        call.resolve(result);
    }

    @PluginMethod
    public void create(PluginCall call) {
        String id = call.getString("id");
        String type = call.getString("type");
        if (id == null || type == null) {
            call.reject("id and type are required", "invalid");
            return;
        }
        JSObject props = call.getObject("props", new JSObject());
        String placement = "under".equals(call.getString("placement")) ? "under" : "over";
        main.post(() -> make(call, id, type, props, placement));
    }

    @PluginMethod
    public void update(PluginCall call) {
        JSArray frames = call.getArray("frames", new JSArray());
        double dpr = call.getDouble("dpr", 1.0);
        main.post(() -> {
            for (int i = 0; i < frames.length(); i++) {
                JSONObject frame = frames.optJSONObject(i);
                if (frame != null) apply(frame, (float) dpr);
            }
            call.resolve();
        });
    }

    @PluginMethod
    public void setProps(PluginCall call) {
        String id = call.getString("id", "");
        JSObject props = call.getObject("props", new JSObject());
        main.post(() -> {
            Slot slot = slots.get(id);
            if (slot == null) {
                call.reject("no native view " + id, "not-found");
                return;
            }
            slot.factory.update(slot.view, props);
            call.resolve();
        });
    }

    @PluginMethod
    public void command(PluginCall call) {
        String id = call.getString("id", "");
        String name = call.getString("name", "");
        JSObject args = call.getObject("args", new JSObject());
        main.post(() -> {
            Slot slot = slots.get(id);
            if (slot == null) {
                call.reject("no native view " + id, "not-found");
                return;
            }
            JSObject result = slot.factory.command(slot.view, name, args);
            call.resolve(result == null ? new JSObject() : result);
        });
    }

    @PluginMethod
    public void destroy(PluginCall call) {
        String id = call.getString("id", "");
        main.post(() -> {
            remove(slots.remove(id));
            call.resolve();
        });
    }

    @Override
    protected void handleOnPause() {
        super.handleOnPause();
        for (Slot slot : slots.values()) slot.factory.lifecycle(slot.view, false);
    }

    @Override
    protected void handleOnResume() {
        super.handleOnResume();
        for (Slot slot : slots.values()) slot.factory.lifecycle(slot.view, true);
    }

    @Override
    protected void handleOnDestroy() {
        for (Slot slot : new ArrayList<>(slots.values())) remove(slot);
        slots.clear();
        super.handleOnDestroy();
    }

    // Making and placing views (main thread).

    private void make(PluginCall call, String id, String type, JSObject props, String placement) {
        DenextNativeViewFactory factory = DenextNativeViews.get(type);
        Activity activity = getActivity();
        if (factory == null || activity == null) {
            call.reject("no native view type " + type + " is registered", "unknown-type");
            return;
        }
        if (slots.containsKey(id)) {
            call.reject("a native view " + id + " already exists", "busy");
            return;
        }
        DenextNativeViewContext context = new DenextNativeViewContext(id, activity, (name, data) -> emit(id, name, data));
        View view = factory.create(context, props);
        FrameLayout host = new FrameLayout(activity);
        host.setClipChildren(true);
        host.setVisibility(View.INVISIBLE);
        host.addView(view, new FrameLayout.LayoutParams(1, 1));
        ensureLayers(activity);
        FrameLayout layer = "under".equals(placement) ? underLayer : router;
        if (layer == null) {
            call.reject("the WebView has no parent to draw native views in", "unsupported");
            return;
        }
        layer.addView(host, new FrameLayout.LayoutParams(1, 1));
        if ("under".equals(placement)) bridge.getWebView().setBackgroundColor(Color.TRANSPARENT);
        slots.put(id, new Slot(id, placement, factory, view, host));
        JSObject result = new JSObject();
        result.put("placement", placement);
        call.resolve(result);
    }

    private void emit(String id, String name, JSObject data) {
        JSObject event = new JSObject();
        event.put("id", id);
        event.put("name", name);
        event.put("data", data);
        notifyListeners("nativeViewEvent", event);
    }

    /** The layers under and over the WebView, added to its parent the first time. */
    @SuppressLint("ClickableViewAccessibility")
    private void ensureLayers(Activity activity) {
        WebView web = bridge.getWebView();
        if (!(web.getParent() instanceof ViewGroup)) return;
        ViewGroup parent = (ViewGroup) web.getParent();
        ViewGroup.LayoutParams fill = new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
        if (underLayer == null) {
            underLayer = new FrameLayout(activity);
            parent.addView(underLayer, parent.indexOfChild(web), fill);
        }
        if (router == null) {
            router = new Router(activity);
            parent.addView(router, parent.indexOfChild(web) + 1, new ViewGroup.LayoutParams(fill));
            web.setOnTouchListener((v, event) -> routeUnder(web, event));
            // A document scroll moves the views in the same frame (a scrolling element inside the
            // page has no native scroll view here: the page's measurements place those).
            web.setOnScrollChangeListener((v, x, y, oldX, oldY) -> {
                for (Slot slot : slots.values()) place(slot);
            });
        }
    }

    /** The WebView's touch listener: a gesture that starts on an "under" view goes to it. */
    private boolean routeUnder(WebView web, MotionEvent event) {
        FrameLayout layer = underLayer;
        if (layer == null) return false;
        float dx = web.getLeft() - layer.getLeft();
        float dy = web.getTop() - layer.getTop();
        int action = event.getActionMasked();
        if (action == MotionEvent.ACTION_DOWN) touchTarget = hit(event.getX() + dx, event.getY() + dy, "under");
        if (touchTarget == null) return false;
        MotionEvent copy = MotionEvent.obtain(event);
        copy.offsetLocation(dx, dy);
        layer.dispatchTouchEvent(copy);
        copy.recycle();
        if (action == MotionEvent.ACTION_UP || action == MotionEvent.ACTION_CANCEL) touchTarget = null;
        return true;
    }

    /** The top-most {@code placement} view that takes a touch at (x, y), or null. */
    @Nullable
    private Slot hit(float x, float y, String placement) {
        List<Slot> all = new ArrayList<>(slots.values());
        for (int i = all.size() - 1; i >= 0; i--) {
            Slot slot = all.get(i);
            if (slot.placement.equals(placement) && slot.takes(x, y)) return slot;
        }
        return null;
    }

    /** Apply one frame from the page. */
    private void apply(JSONObject frame, float dpr) {
        Slot slot = slots.get(frame.optString("id"));
        if (slot == null) return;
        slot.frame = frame;
        this.dpr = dpr;
        place(slot);
    }

    /**
     * Place a view from its last frame. A slot that scrolls with the document is placed from its
     * content box and the WebView's own scroll offset (so it follows a document scroll in the same
     * frame, from onScrollChange); one inside a scrolling element from the box the page measured.
     */
    private void place(Slot slot) {
        JSONObject frame = slot.frame;
        if (frame == null) return;
        WebView web = bridge.getWebView();
        JSONObject scroller = frame.optJSONObject("scroller");
        boolean document = scroller != null && "document".equals(scroller.optString("kind"));
        slot.interactive = frame.optBoolean("interactive", true);
        RectF box;
        RectF visible;
        if (document) {
            JSONObject content = frame.optJSONObject("content");
            box = scaled(content, dpr);
            box.offset(-web.getScrollX(), -web.getScrollY());
            JSONObject local = frame.optJSONObject("localClip");
            visible = local == null ? null : scaled(local, dpr);
            if (visible != null) {
                visible.offset(box.left, box.top);
                if (!visible.intersect(box) || !visible.intersect(0, 0, web.getWidth(), web.getHeight())) visible = null;
            }
        } else {
            box = scaled(frame, dpr);
            JSONObject clip = frame.optJSONObject("clip");
            visible = clip == null ? null : scaled(clip, dpr);
        }
        slot.visible = visible != null && !frame.optBoolean("hidden", false);
        if (!slot.visible) {
            slot.host.setVisibility(View.INVISIBLE);
            return;
        }
        resize(slot.host, visible.width(), visible.height());
        resize(slot.view, box.width(), box.height());
        slot.host.setX(web.getLeft() + visible.left);
        slot.host.setY(web.getTop() + visible.top);
        slot.view.setX(box.left - visible.left);
        slot.view.setY(box.top - visible.top);
        slot.passthrough.clear();
        JSONArray passthrough = frame.optJSONArray("passthrough");
        for (int i = 0; passthrough != null && i < passthrough.length(); i++) {
            JSONObject r = passthrough.optJSONObject(i);
            if (r == null) continue;
            RectF local = scaled(r, dpr);
            local.offset(box.left - visible.left, box.top - visible.top);
            slot.passthrough.add(local);
        }
        slot.host.setVisibility(View.VISIBLE);
    }

    /** {@code { x, y, width, height }} (CSS px) times {@code dpr}. */
    private static RectF scaled(@Nullable JSONObject o, float dpr) {
        if (o == null) return new RectF();
        float x = (float) o.optDouble("x", 0) * dpr;
        float y = (float) o.optDouble("y", 0) * dpr;
        return new RectF(x, y, x + (float) o.optDouble("width", 0) * dpr, y + (float) o.optDouble("height", 0) * dpr);
    }

    /** Set {@code view}'s layout size (px), re-laying it out only when it changed. */
    private static void resize(View view, float width, float height) {
        ViewGroup.LayoutParams lp = view.getLayoutParams();
        int w = Math.max(1, (int) Math.round(width));
        int h = Math.max(1, (int) Math.round(height));
        if (lp.width == w && lp.height == h) return;
        lp.width = w;
        lp.height = h;
        view.setLayoutParams(lp);
    }

    private void remove(@Nullable Slot slot) {
        if (slot == null) return;
        if (touchTarget == slot) touchTarget = null;
        if (slot.host.getParent() instanceof ViewGroup) ((ViewGroup) slot.host.getParent()).removeView(slot.host);
        slot.factory.destroy(slot.view);
    }
}
