// denext-native-views-template: 1 sha256=23e8fc1c7087a6902f19d79983270d000005c96d5899a7b5e3e12ce4d3db7611
// Generated by denext mobile add native-views (denext native views). Safe to commit; re-run it
// after upgrading denext (then ship a new binary). See https://denext.dev/docs/mobile.

package dev.denext.nativeviews;

import android.app.Activity;
import com.getcapacitor.JSObject;

/** What a factory gets to make a view: its id, the activity, and a way to send events to the page. */
public final class DenextNativeViewContext {
    /** Receives a view's events. */
    public interface Sink {
        void emit(String name, JSObject data);
    }

    private final String id;
    private final Activity activity;
    private final Sink sink;

    DenextNativeViewContext(String id, Activity activity, Sink sink) {
        this.id = id;
        this.activity = activity;
        this.sink = sink;
    }

    public String getId() {
        return id;
    }

    public Activity getActivity() {
        return activity;
    }

    /** Send an event to the page: NativeViewSlot's onEvent(name, data). */
    public void emit(String name, JSObject data) {
        sink.emit(name, data == null ? new JSObject() : data);
    }
}
