// The shipped docs corpus (src/mcp/docs-corpus.json, generated by `deno task docs:corpus`):
// every docs-site page chunked by h2/h3, the root guides, and one chunk per API symbol. It is a
// DYNAMIC json import with a literal specifier, so it stays in the JSR module graph (offline,
// cached by `deno cache`) without being loaded by every `denext` CLI start — only the first
// docs search/read pays for it.

/** One docs page (or root guide) in the corpus. */
export interface DocPage {
  slug: string;
  title: string;
  lead?: string;
  /** Present only when the page is NOT served at `/docs/<slug>` (a GitHub URL). */
  url?: string;
}

/** One chunk: a guide section (`kind: "guide"`) or an API symbol (any other kind). */
export interface DocChunk {
  id: string;
  kind: string;
  title: string;
  text: string;
  /** Guide sections: the page slug, heading anchor and level (1 = intro, 2 = h2, 3 = h3). */
  page?: string;
  anchor?: string;
  level?: number;
  /** API symbols: the module (`denext/server`) and whether it has no React/Next equivalent. */
  module?: string;
  denextOnly?: boolean;
}

/** The loaded corpus plus derived lookups. */
export interface Corpus {
  pages: DocPage[];
  chunks: DocChunk[];
  pageBySlug: Map<string, DocPage>;
  /** A page's sections in document order. */
  sectionsOf: Map<string, DocChunk[]>;
  byId: Map<string, DocChunk>;
  /** For an h3 section, the h2 it sits under (for "Page › Section › Sub" labels). */
  parentOf: Map<string, DocChunk>;
}

/** The public docs origin a corpus URL is relative to. */
export const DOCS_ORIGIN = "https://denext.dev";

let loaded: Promise<Corpus> | null = null;

/** Index the raw corpus json. */
function build(raw: { pages: DocPage[]; chunks: DocChunk[] }): Corpus {
  const pageBySlug = new Map(raw.pages.map((p) => [p.slug, p]));
  const sectionsOf = new Map<string, DocChunk[]>();
  const byId = new Map<string, DocChunk>();
  const parentOf = new Map<string, DocChunk>();
  let lastH2: DocChunk | undefined;
  for (const c of raw.chunks) {
    byId.set(c.id, c);
    if (c.kind !== "guide" || !c.page) continue;
    const list = sectionsOf.get(c.page) ?? [];
    if (list.length === 0) lastH2 = undefined;
    list.push(c);
    sectionsOf.set(c.page, list);
    if (c.level === 2) lastH2 = c;
    else if (c.level === 3 && lastH2) parentOf.set(c.id, lastH2);
  }
  return { pages: raw.pages, chunks: raw.chunks, pageBySlug, sectionsOf, byId, parentOf };
}

/** Load (once) and index the shipped docs corpus. */
export function loadCorpus(): Promise<Corpus> {
  loaded ??= import("../docs-corpus.json", { with: { type: "json" } }).then((m) =>
    build(m.default as { pages: DocPage[]; chunks: DocChunk[] })
  );
  return loaded;
}

/** `true` for a guide section, `false` for an API symbol. */
export const isGuide = (c: DocChunk): boolean => c.kind === "guide";

/** The site-relative (or absolute, for a GitHub-hosted guide) URL of a chunk. */
export function chunkUrl(corpus: Corpus, c: DocChunk): string {
  if (!isGuide(c)) {
    const rest = c.id.slice("api:".length);
    return `/docs/api/${rest}`;
  }
  const page = corpus.pageBySlug.get(c.page!);
  const base = page?.url ?? `/docs/${c.page}`;
  return c.anchor ? `${base}#${c.anchor}` : base;
}

/** The reference `denext_read_docs` accepts for a chunk (`desktop#desktop-notifications`). */
export function chunkRef(c: DocChunk): string {
  return isGuide(c) ? c.id.slice("doc:".length) : c.id;
}

/** "Page › Section › Sub" for a guide section; the symbol name for an API chunk. */
export function chunkLabel(corpus: Corpus, c: DocChunk): string {
  if (!isGuide(c)) return c.title;
  const page = corpus.pageBySlug.get(c.page!)?.title ?? c.page!;
  const parent = corpus.parentOf.get(c.id);
  return [page, parent?.title, c.title].filter(Boolean).join(" › ").replace(/\*\*/g, "");
}
