/**
 * `@denext/content-collections/codegen` (internal) — generate `.denext/content.ts`, the type module
 * that registers the app's `content.config.ts` so `getCollection`/`getEntry` are typed to its
 * collections and schemas. Pure function of the config's path (the TypeScript compiler does the
 * inference — no `deno doc`, no subprocess), mirroring denext's `.denext/routes.ts` + `api.ts`.
 *
 * @module
 */

import { relative } from "@std/path";

/**
 * The source of `.denext/content.ts`. Imports the config's default-export TYPE and registers it on
 * `RegisteredContent`, so importing this file (`import "./.denext/content.ts"`) types the query API.
 *
 * @param outDir Absolute `.denext` output dir (the file lives here; the import is relative to it).
 * @param configPath Absolute path to the app's `content.config.ts`.
 */
export function generateContentTypes(outDir: string, configPath: string): string {
  const rel = relative(outDir, configPath).replaceAll("\\", "/");
  const spec = rel.startsWith(".") ? rel : `./${rel}`;
  // `import type * as cfg` + `(typeof cfg)["default"]` mirrors denext's own `.denext/api.ts`
  // generator: TypeScript infers the config (and its schemas) from the module's type — no subprocess.
  return `// AUTO-GENERATED by @denext/content-collections — DO NOT EDIT.
// Regenerated on \`denext build\` / \`denext dev\`. Import this file (e.g.
// \`import "./.denext/content.ts";\`) to type \`getCollection\`/\`getEntry\` against your collections.
import type * as cfg from ${JSON.stringify(spec)};

declare module "@denext/content-collections/runtime" {
  interface RegisteredContent {
    config: (typeof cfg)["default"];
  }
}
`;
}
