// denext-settings-template: 1 sha256=ef8b726efddc15b0c3f1f7fc15c649334705221255d27724fbea30d763cd959a
// Generated by `denext mobile add permissions` (denext app settings). Safe to commit;
// re-run it after upgrading denext (then ship a new binary). See https://denext.dev/docs/mobile.

package dev.denext.settings;

import android.content.ActivityNotFoundException;
import android.content.Intent;
import android.net.Uri;
import android.provider.Settings;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;

/**
 * The native side of {@code openAppSettings()} from {@code denext/mobile}, reached from the web
 * app as {@code window.Capacitor.Plugins.DenextSettings}. {@code MainActivity} registers it
 * ({@code registerPlugin(DenextSettingsPlugin.class)} before {@code super.onCreate}).
 *
 * <p>{@code open()} starts {@code Settings.ACTION_APPLICATION_DETAILS_SETTINGS} for the app's
 * package: the "App info" screen, where the user can change a permission they refused. Rejects
 * with code {@code unavailable} when no activity handles it.
 */
@CapacitorPlugin(name = "DenextSettings")
public class DenextSettingsPlugin extends Plugin {

    @PluginMethod
    public void open(PluginCall call) {
        Intent intent = new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS);
        intent.setData(Uri.fromParts("package", getContext().getPackageName(), null));
        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        try {
            getContext().startActivity(intent);
            call.resolve();
        } catch (ActivityNotFoundException e) {
            call.reject("The app's settings page is unavailable.", "unavailable");
        }
    }
}
