// denext-settings-template: 3 sha256=ffea011e37b00e3abd62bd848688a96f0a1a949f74c62e6eb04661d9f01e0084
// Generated by `denext mobile add permissions` (denext app settings). Safe to commit;
// re-run it after upgrading denext (then ship a new binary). See https://denext.dev/docs/mobile.

package dev.denext.settings;

import android.app.Notification;
import android.app.NotificationManager;
import android.content.ActivityNotFoundException;
import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.provider.Settings;
import android.service.notification.StatusBarNotification;
import com.getcapacitor.JSArray;
import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 * The native side of {@code openAppSettings()} from {@code denext/mobile}, reached from the web
 * app as {@code window.Capacitor.Plugins.DenextSettings}. {@code MainActivity} registers it
 * ({@code registerPlugin(DenextSettingsPlugin.class)} before {@code super.onCreate}).
 *
 * <p>{@code open()} starts {@code Settings.ACTION_APPLICATION_DETAILS_SETTINGS} for the app's
 * package: the "App info" screen, where the user can change a permission they refused. Rejects
 * with code {@code unavailable} when no activity handles it, {@code failed} when Android refuses
 * to start it.
 *
 * <p>{@code sendIntent({ action, extras? })} starts an activity for {@code action} (React
 * Native's {@code Linking.sendIntent}): each extra is {@code { key, value }}, a string, a number
 * (put as a double, as React Native does) or a boolean. Rejects with code {@code invalid} for an
 * empty action or another extra type, {@code unavailable} when no activity handles it, and
 * {@code failed} when Android refuses to start it (a {@code SecurityException}: an action that
 * needs a permission the app lacks, such as {@code ACTION_CALL}).
 *
 * <p>{@code deliveredNotifications()} lists the app's notifications in the shade, local and pushed
 * alike ({@code NotificationManager.getActiveNotifications()}), as {@code { notifications: [{ id,
 * tag?, threadId?, title?, summary? }] }}: the id (as a string), the tag, the group key, the title
 * and whether it is a group summary. {@code removeDeliveredNotifications({ notifications: [{ id,
 * tag? }] })} cancels each ({@code cancel(tag, id)}); an entry whose id is not an integer is
 * skipped. Rejects with code {@code invalid} without the array, {@code failed} when Android
 * refuses to list them.
 */
@CapacitorPlugin(name = "DenextSettings")
public class DenextSettingsPlugin extends Plugin {

    @PluginMethod
    public void open(PluginCall call) {
        Intent intent = new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS);
        intent.setData(Uri.fromParts("package", getContext().getPackageName(), null));
        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        try {
            getContext().startActivity(intent);
            call.resolve();
        } catch (ActivityNotFoundException e) {
            call.reject("The app's settings page is unavailable.", "unavailable");
        } catch (Exception e) {
            // Never let it escape: Capacitor's Bridge turns a plugin method's exception into a crash.
            call.reject("The app's settings page could not be opened.", "failed");
        }
    }

    @PluginMethod
    public void sendIntent(PluginCall call) {
        String action = call.getString("action");
        if (action == null || action.isEmpty()) {
            call.reject("Invalid Action: " + action + ".", "invalid");
            return;
        }
        Intent intent = new Intent(action);
        JSArray extras = call.getArray("extras", null);
        String error = putExtras(intent, extras);
        if (error != null) {
            call.reject(error, "invalid");
            return;
        }
        android.app.Activity activity = getActivity();
        if (activity == null) intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        try {
            if (activity != null) activity.startActivity(intent);
            else getContext().startActivity(intent);
            call.resolve();
        } catch (ActivityNotFoundException e) {
            call.reject("Could not launch Intent with action " + action + ".", "unavailable");
        } catch (Exception e) {
            // A SecurityException (ACTION_CALL without CALL_PHONE, an activity that is not
            // exported) or anything else: React Native's IntentModule catches every exception and
            // rejects; letting it escape would crash the app through Capacitor's Bridge.
            call.reject("Could not launch Intent with action " + action + ".", "failed");
        }
    }

    @PluginMethod
    public void deliveredNotifications(PluginCall call) {
        JSArray list = new JSArray();
        NotificationManager manager = notificationManager();
        try {
            if (manager != null) {
                for (StatusBarNotification sbn : manager.getActiveNotifications()) {
                    list.put(deliveredObject(sbn));
                }
            }
        } catch (Exception e) {
            // Never let it escape: Capacitor's Bridge turns a plugin method's exception into a crash.
            call.reject("The delivered notifications could not be read.", "failed");
            return;
        }
        JSObject out = new JSObject();
        out.put("notifications", list);
        call.resolve(out);
    }

    @PluginMethod
    public void removeDeliveredNotifications(PluginCall call) {
        JSArray list = call.getArray("notifications", null);
        if (list == null) {
            call.reject("notifications must be an array.", "invalid");
            return;
        }
        NotificationManager manager = notificationManager();
        for (int i = 0; manager != null && i < list.length(); i++) {
            JSONObject entry = list.optJSONObject(i);
            Integer id = entry == null ? null : parseId(entry.optString("id", ""));
            if (id == null) continue;
            String tag = entry.optString("tag", "");
            if (tag.isEmpty()) manager.cancel(id);
            else manager.cancel(tag, id);
        }
        call.resolve();
    }

    private NotificationManager notificationManager() {
        return (NotificationManager) getContext().getSystemService(Context.NOTIFICATION_SERVICE);
    }

    /** One delivered notification for {@code deliveredNotifications()}. */
    static JSObject deliveredObject(StatusBarNotification sbn) {
        JSObject out = new JSObject();
        out.put("id", String.valueOf(sbn.getId()));
        if (sbn.getTag() != null) out.put("tag", sbn.getTag());
        Notification n = sbn.getNotification();
        if (n == null) return out;
        if (n.getGroup() != null) out.put("threadId", n.getGroup());
        if ((n.flags & Notification.FLAG_GROUP_SUMMARY) != 0) out.put("summary", true);
        CharSequence title = n.extras == null ? null : n.extras.getCharSequence(Notification.EXTRA_TITLE);
        if (title != null) out.put("title", title.toString());
        return out;
    }

    /** A notification id from its string form, or null when it is not an integer. */
    static Integer parseId(String id) {
        try {
            return Integer.valueOf(id);
        } catch (NumberFormatException e) {
            return null;
        }
    }

    /**
     * Put React Native's intent extras on {@code intent}: {@code { key, value }} each, the value a
     * string, a number (a double: JavaScript does not say whether it is an integer) or a boolean.
     * Returns null when every extra was put, else the reason the call is refused.
     */
    static String putExtras(Intent intent, JSONArray extras) {
        if (extras == null) return null;
        for (int i = 0; i < extras.length(); i++) {
            JSONObject extra = extras.optJSONObject(i);
            String key = extra == null ? null : extra.optString("key", null);
            if (key == null) return "Extra " + i + " has no key.";
            Object value = extra.opt("value");
            if (value instanceof String) intent.putExtra(key, (String) value);
            else if (value instanceof Boolean) intent.putExtra(key, ((Boolean) value).booleanValue());
            else if (value instanceof Number) intent.putExtra(key, ((Number) value).doubleValue());
            else return "Extra type for " + key + " not supported.";
        }
        return null;
    }
}
