// Navigating `denext.config.schema.json` (JSON Schema draft 2020-12, generated by
// `scripts/gen-config-schema.ts`): resolve the node at a dotted form path, unwrap an array's
// item schema, and pick a union branch for a value.
//
// STUB — J4c implements these. The module names, signatures and types are final so the rest of
// the UI can be written against them today.

/** The subset of JSON Schema the config schema actually uses, plus denext's `x-denext` hints. */
export interface SchemaNode {
  /** `"object"`, `"array"`, `"string"`, … (or a nullable union of those). */
  type?: string | string[];
  /** Object properties. */
  properties?: Record<string, SchemaNode>;
  /** Which properties are required. */
  required?: string[];
  /** Array item schema. */
  items?: SchemaNode;
  /** Allowed values (rendered as a select or a segmented control). */
  enum?: unknown[];
  /** Union branches (rendered behind a discriminator picker). */
  anyOf?: SchemaNode[];
  /** Record/map value schema. */
  additionalProperties?: boolean | SchemaNode;
  /** The JSDoc summary, rendered as field help. */
  description?: string;
  /** denext's generator hints (`widget`, `wrapper`). */
  "x-denext"?: { widget?: string; wrapper?: string };
}

/** The message every stub in `src/ui/form/**` throws until J4c lands. */
const TODO = "not implemented: J4c";

/**
 * Resolve the schema node a dotted form path addresses (`images.remotePatterns.0.hostname`).
 *
 * @param root The root schema.
 * @param path The dotted path.
 * @returns The node at that path.
 */
export function resolveAt(root: SchemaNode, path: string): SchemaNode {
  void root, path;
  throw new Error(TODO);
}

/**
 * The item schema of an array node (what one row of a list editor is a form over).
 *
 * @param node An array node.
 * @returns The item schema.
 */
export function itemSchema(node: SchemaNode): SchemaNode {
  void node;
  throw new Error(TODO);
}

/**
 * The `anyOf` branch that matches `value` — the discriminator picker's current selection.
 *
 * @param node A union node.
 * @param value The current value.
 * @returns The matching branch.
 */
export function branchFor(node: SchemaNode, value: unknown): SchemaNode {
  void node, value;
  throw new Error(TODO);
}
