// Navigating `denext.config.schema.json` (JSON Schema draft 2020-12, generated by
// `scripts/gen-config-schema.ts`): resolve the node at a form path, unwrap an array's item
// schema, pick a union branch for a value, and walk every node the schema contains.
//
// The schema ships with the framework, so it is imported as JSON rather than fetched — the UI
// works offline, from a JSR install, and inside `deno compile`.

import CONFIG_SCHEMA from "../../../denext.config.schema.json" with { type: "json" };
import { OVERRIDES } from "./schema-overrides.ts";

/** The subset of JSON Schema the config schema actually uses, plus denext's `x-denext` hints. */
export interface SchemaNode {
  /** `"object"`, `"array"`, `"string"`, … (or a nullable union of those). */
  type?: string | string[];
  /** Object properties. */
  properties?: Record<string, SchemaNode>;
  /** Which properties are required. */
  required?: string[];
  /** Array item schema. */
  items?: SchemaNode;
  /** Allowed values (rendered as a select or a segmented control). */
  enum?: unknown[];
  /** Union branches (rendered behind a discriminator picker). */
  anyOf?: SchemaNode[];
  /** Record/map value schema. */
  additionalProperties?: boolean | SchemaNode;
  /** The JSDoc summary, rendered as field help. */
  description?: string;
  /** Inclusive lower bound of a number field (from an `@minimum` JSDoc tag). */
  minimum?: number;
  /** Inclusive upper bound of a number field (from a `@maximum` JSDoc tag). */
  maximum?: number;
  /**
   * The value the key takes when it is absent, from a `@default` JSDoc tag.
   *
   * Only a key that is ON unless you say otherwise states one, and that is the whole point: a
   * toggle cannot tell "tick to switch on" from "tick to opt out" without it.
   */
  default?: unknown;
  /**
   * denext's generator hints: `widget: "textarea"` (from a `@widget textarea` JSDoc tag) for a
   * multi-line string, and `wrapper: "function"` for a list written back as `() => [...]`.
   */
  "x-denext"?: { widget?: "textarea"; wrapper?: "function" };
}

/**
 * The path segment that stands for "the value side of a map" — the map analogue of an array
 * index, since a map's keys are user data and cannot appear in a static path.
 */
export const MAP_SEGMENT = "*";

/**
 * The framework's generated config schema.
 *
 * @returns The root schema node of `denext.config.schema.json`.
 */
export function loadConfigSchema(): SchemaNode {
  return CONFIG_SCHEMA as SchemaNode;
}

/**
 * The stable key a path is known by: array indices and map keys collapse to `[]`, so
 * `["redirects", "2", "source"]` and `["redirects", "0", "source"]` are both
 * `redirects[].source`. This is the key `OVERRIDES` is written in.
 *
 * @param path The path segments.
 * @returns The dotted key.
 */
export function pathKey(path: readonly string[]): string {
  let key = "";
  for (const segment of path) {
    if (segment === MAP_SEGMENT || /^\d+$/.test(segment)) key += "[]";
    else key += key === "" ? segment : `.${segment}`;
  }
  return key;
}

/** `node` with its `OVERRIDES` patch (if any) shallow-merged over it. */
function patched(node: SchemaNode, key: string): SchemaNode {
  const override = OVERRIDES[key];
  return override ? { ...node, ...override } : node;
}

/**
 * True when `node` is a map: an object whose values are described by a schema (a `Record<…>` in
 * the source type), as opposed to a fixed set of properties or an opaque bag.
 *
 * @param node The node to test.
 * @returns Whether the node has a usable `additionalProperties` schema.
 */
export function mapValueSchema(node: SchemaNode): SchemaNode | undefined {
  const extra = node.additionalProperties;
  if (typeof extra !== "object" || extra === null) return undefined;
  return Object.keys(extra).length > 0 ? extra : undefined;
}

/** One step down: the child node `segment` addresses, or `undefined`. */
function descend(node: SchemaNode, segment: string): SchemaNode | undefined {
  const property = node.properties?.[segment];
  if (property) return property;
  if (node.items && (segment === MAP_SEGMENT || /^\d+$/.test(segment))) return node.items;
  const values = mapValueSchema(node);
  if (values && (segment === MAP_SEGMENT || node.properties === undefined)) return values;
  for (const branch of node.anyOf ?? []) {
    const found = descend(branch, segment);
    if (found) return found;
  }
  return undefined;
}

/**
 * Resolve the schema node a form path addresses. An array index (or `MAP_SEGMENT`) selects the
 * item schema, a map segment the value schema, and a union is searched branch by branch so
 * `["csp", "scriptSrc"]` resolves through `csp`'s object branch.
 *
 * @param root The root schema.
 * @param path The path segments.
 * @returns The node at that path, with its `OVERRIDES` patch applied.
 * @throws If no segment along the path resolves.
 */
export function resolveAt(root: SchemaNode, path: readonly string[]): SchemaNode {
  let node = patched(root, "");
  const walked: string[] = [];
  for (const segment of path) {
    const next = descend(node, segment);
    if (!next) throw new Error(`no schema at \`${pathKey([...walked, segment])}\``);
    walked.push(segment);
    node = patched(next, pathKey(walked));
  }
  return node;
}

/**
 * The item schema of an array node (what one row of a list editor is a form over).
 *
 * @param node An array node.
 * @returns The item schema, or an empty node when the array is untyped.
 */
export function itemSchema(node: SchemaNode): SchemaNode {
  return node.items ?? {};
}

/**
 * The `anyOf` branch that matches `value` — the discriminator picker's current selection.
 * An `enum` branch wins on an exact value match; otherwise the first branch whose JSON type
 * matches wins; otherwise the first branch.
 *
 * @param node A union node.
 * @param value The current value.
 * @returns The matching branch (the first branch when nothing matches).
 */
export function branchFor(node: SchemaNode, value: unknown): SchemaNode {
  const branches = node.anyOf ?? [];
  if (branches.length === 0) return node;
  const exact = branches.find((branch) => branch.enum?.some((option) => option === value));
  if (exact) return exact;
  const typed = branches.find((branch) => !branch.enum && branch.type === jsonTypeOf(value));
  return typed ?? branches[0];
}

/**
 * The index of the branch {@linkcode branchFor} would pick — what the discriminator radio group
 * posts, since branches have no names of their own.
 *
 * @param node A union node.
 * @param value The current value.
 * @returns The branch index (`0` when the node is not a union).
 */
export function branchIndexFor(node: SchemaNode, value: unknown): number {
  const index = (node.anyOf ?? []).indexOf(branchFor(node, value));
  return index < 0 ? 0 : index;
}

/** The JSON Schema `type` keyword a runtime value would be described by. */
function jsonTypeOf(value: unknown): string {
  if (Array.isArray(value)) return "array";
  if (value === null) return "null";
  return typeof value === "number" ? "number" : typeof value;
}

/**
 * Visit every node the schema contains, depth first: properties, array items, map values and
 * union branches. A union branch is visited at its parent's path (a branch is an alternative
 * shape for the same field, not a field of its own).
 *
 * @param root The root schema.
 * @param visit Called with each node and its path.
 */
export function walkSchema(
  root: SchemaNode,
  visit: (node: SchemaNode, path: readonly string[]) => void,
): void {
  const step = (node: SchemaNode, path: readonly string[]): void => {
    visit(node, path);
    for (const [name, child] of Object.entries(node.properties ?? {})) step(child, [...path, name]);
    if (node.items) step(node.items, [...path, "0"]);
    const values = mapValueSchema(node);
    if (values) step(values, [...path, MAP_SEGMENT]);
    for (const branch of node.anyOf ?? []) step(branch, path);
  };
  step(root, []);
}
