// denext-storage-template: 1 sha256=95fd0e82f5bf243f2b7cb011aedfcf42c5c0064c188a1dded1cff922fb8e4313
// Generated by `denext mobile add storage` (denext durable key-value storage). Safe to
// commit; re-run it after upgrading denext (then ship a new binary). See https://denext.dev/docs/mobile.

package dev.denext.storage;

import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.database.sqlite.SQLiteStatement;
import com.getcapacitor.JSArray;
import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 * The native side of {@code openKeyValueStore()} from {@code denext/mobile} (and React Native
 * mode's AsyncStorage and MMKV), reached from the web app as
 * {@code window.Capacitor.Plugins.DenextStorage}. {@code MainActivity} registers it
 * ({@code registerPlugin(DenextStoragePlugin.class)} before {@code super.onCreate}).
 *
 * <p>One SQLite database, the app's {@code databases/denext-kv.db}: app-private data that the
 * system does not clear the way it may clear a WebView's storage. Table
 * {@code kv (store, key, value)}; every method is one batch (a write batch is one transaction),
 * run on a single worker thread.
 */
@CapacitorPlugin(name = "DenextStorage")
public class DenextStoragePlugin extends Plugin {

    private static final class Helper extends SQLiteOpenHelper {
        Helper(Context context) {
            super(context, "denext-kv.db", null, 1);
            setWriteAheadLoggingEnabled(true);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            db.execSQL(
                "CREATE TABLE IF NOT EXISTS kv (store TEXT NOT NULL, key TEXT NOT NULL, "
                    + "value TEXT NOT NULL, PRIMARY KEY (store, key)) WITHOUT ROWID"
            );
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {}
    }

    private interface Work {
        JSObject run(SQLiteDatabase db) throws Exception;
    }

    private interface Fill<T> {
        void bind(SQLiteStatement stmt, T item);
    }

    private final ExecutorService executor = Executors.newSingleThreadExecutor();
    private Helper helper;

    @Override
    public void load() {
        helper = new Helper(getContext());
    }

    @Override
    protected void handleOnDestroy() {
        executor.shutdown();
        if (helper != null) helper.close();
    }

    private void run(PluginCall call, Work work) {
        executor.execute(() -> {
            try {
                call.resolve(work.run(helper.getWritableDatabase()));
            } catch (Exception e) {
                String message = e.getMessage() != null ? e.getMessage() : e.toString();
                call.reject(message, "STORAGE_ERROR", e);
            }
        });
    }

    private static <T> void batch(SQLiteDatabase db, String sql, Iterable<T> items, Fill<T> fill) {
        db.beginTransaction();
        try {
            SQLiteStatement stmt = db.compileStatement(sql);
            try {
                for (T item : items) {
                    stmt.clearBindings();
                    fill.bind(stmt, item);
                    stmt.execute();
                }
            } finally {
                stmt.close();
            }
            db.setTransactionSuccessful();
        } finally {
            db.endTransaction();
        }
    }

    private static String storeName(PluginCall call) {
        String store = call.getString("store");
        return store != null ? store : "default";
    }

    private static java.util.List<String> strings(PluginCall call, String name) {
        JSArray array = call.getArray(name, new JSArray());
        java.util.List<String> out = new java.util.ArrayList<>();
        for (int i = 0; i < array.length(); i++) {
            Object item = array.opt(i);
            if (item instanceof String) out.add((String) item);
        }
        return out;
    }

    @PluginMethod
    public void getMany(PluginCall call) {
        String store = storeName(call);
        JSArray keys = call.getArray("keys", new JSArray());
        run(call, db -> {
            JSArray values = new JSArray();
            for (int i = 0; i < keys.length(); i++) {
                Object key = keys.opt(i);
                if (!(key instanceof String)) {
                    values.put(JSONObject.NULL);
                    continue;
                }
                try (
                    Cursor cursor = db.rawQuery(
                        "SELECT value FROM kv WHERE store = ? AND key = ?",
                        new String[] { store, (String) key }
                    )
                ) {
                    values.put(cursor.moveToFirst() ? cursor.getString(0) : JSONObject.NULL);
                }
            }
            JSObject result = new JSObject();
            result.put("values", values);
            return result;
        });
    }

    @PluginMethod
    public void setMany(PluginCall call) {
        String store = storeName(call);
        JSArray entries = call.getArray("entries", new JSArray());
        java.util.List<String[]> pairs = new java.util.ArrayList<>();
        for (int i = 0; i < entries.length(); i++) {
            JSONArray pair = entries.optJSONArray(i);
            if (pair == null || pair.length() != 2) continue;
            Object key = pair.opt(0);
            Object value = pair.opt(1);
            if (key instanceof String && value instanceof String) {
                pairs.add(new String[] { (String) key, (String) value });
            }
        }
        run(call, db -> {
            batch(db, "INSERT OR REPLACE INTO kv (store, key, value) VALUES (?, ?, ?)", pairs, (stmt, pair) -> {
                stmt.bindString(1, store);
                stmt.bindString(2, pair[0]);
                stmt.bindString(3, pair[1]);
            });
            return new JSObject();
        });
    }

    @PluginMethod
    public void removeMany(PluginCall call) {
        String store = storeName(call);
        java.util.List<String> keys = strings(call, "keys");
        run(call, db -> {
            batch(db, "DELETE FROM kv WHERE store = ? AND key = ?", keys, (stmt, key) -> {
                stmt.bindString(1, store);
                stmt.bindString(2, key);
            });
            return new JSObject();
        });
    }

    @PluginMethod
    public void keys(PluginCall call) {
        String store = storeName(call);
        run(call, db -> {
            JSArray keys = new JSArray();
            try (
                Cursor cursor = db.rawQuery("SELECT key FROM kv WHERE store = ? ORDER BY key", new String[] { store })
            ) {
                while (cursor.moveToNext()) keys.put(cursor.getString(0));
            }
            JSObject result = new JSObject();
            result.put("keys", keys);
            return result;
        });
    }

    @PluginMethod
    public void clear(PluginCall call) {
        String store = storeName(call);
        run(call, db -> {
            db.delete("kv", "store = ?", new String[] { store });
            return new JSObject();
        });
    }
}
